// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewError creates a new instance of Error. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewError(t interface {
	mock.TestingT
	Cleanup(func())
}) *Error {
	mock := &Error{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Error is an autogenerated mock type for the Error type
type Error struct {
	mock.Mock
}

type Error_Expecter struct {
	mock *mock.Mock
}

func (_m *Error) EXPECT() *Error_Expecter {
	return &Error_Expecter{mock: &_m.Mock}
}

// As provides a mock function for the type Error
func (_mock *Error) As(typeParam *errors.Type) errors.Error {
	ret := _mock.Called(typeParam)

	if len(ret) == 0 {
		panic("no return value specified for As")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(*errors.Type) errors.Error); ok {
		r0 = returnFunc(typeParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Error_As_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'As'
type Error_As_Call struct {
	*mock.Call
}

// As is a helper method to define mock.On call
//   - typeParam *errors.Type
func (_e *Error_Expecter) As(typeParam any) *Error_As_Call {
	return &Error_As_Call{Call: _e.mock.On("As", typeParam)}
}

func (_c *Error_As_Call) Run(run func(typeParam *errors.Type)) *Error_As_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *errors.Type
		if args[0] != nil {
			arg0 = args[0].(*errors.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Error_As_Call) Return(error errors.Error) *Error_As_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Error_As_Call) RunAndReturn(run func(typeParam *errors.Type) errors.Error) *Error_As_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type Error
func (_mock *Error) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Error_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Error_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *Error_Expecter) Error() *Error_Error_Call {
	return &Error_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *Error_Error_Call) Run(run func()) *Error_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Error_Call) Return(s string) *Error_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Error_Error_Call) RunAndReturn(run func() string) *Error_Error_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type Error
func (_mock *Error) GetData() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// Error_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type Error_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *Error_Expecter) GetData() *Error_GetData_Call {
	return &Error_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *Error_GetData_Call) Run(run func()) *Error_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_GetData_Call) Return(ifaceVal interface{}) *Error_GetData_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *Error_GetData_Call) RunAndReturn(run func() interface{}) *Error_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function for the type Error
func (_mock *Error) GetType() *errors.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 *errors.Type
	if returnFunc, ok := ret.Get(0).(func() *errors.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.Type)
		}
	}
	return r0
}

// Error_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type Error_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *Error_Expecter) GetType() *Error_GetType_Call {
	return &Error_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *Error_GetType_Call) Run(run func()) *Error_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_GetType_Call) Return(typeParam *errors.Type) *Error_GetType_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *Error_GetType_Call) RunAndReturn(run func() *errors.Type) *Error_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function for the type Error
func (_mock *Error) Messages() errors.Messages {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 errors.Messages
	if returnFunc, ok := ret.Get(0).(func() errors.Messages); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Messages)
		}
	}
	return r0
}

// Error_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type Error_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *Error_Expecter) Messages() *Error_Messages_Call {
	return &Error_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *Error_Messages_Call) Run(run func()) *Error_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Messages_Call) Return(messages errors.Messages) *Error_Messages_Call {
	_c.Call.Return(messages)
	return _c
}

func (_c *Error_Messages_Call) RunAndReturn(run func() errors.Messages) *Error_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type Error
func (_mock *Error) Unwrap() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Error_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type Error_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *Error_Expecter) Unwrap() *Error_Unwrap_Call {
	return &Error_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *Error_Unwrap_Call) Run(run func()) *Error_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Unwrap_Call) Return(err error) *Error_Unwrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Error_Unwrap_Call) RunAndReturn(run func() error) *Error_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}
