// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewSubTaskMetaSorter creates a new instance of SubTaskMetaSorter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubTaskMetaSorter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubTaskMetaSorter {
	mock := &SubTaskMetaSorter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubTaskMetaSorter is an autogenerated mock type for the SubTaskMetaSorter type
type SubTaskMetaSorter struct {
	mock.Mock
}

type SubTaskMetaSorter_Expecter struct {
	mock *mock.Mock
}

func (_m *SubTaskMetaSorter) EXPECT() *SubTaskMetaSorter_Expecter {
	return &SubTaskMetaSorter_Expecter{mock: &_m.Mock}
}

// Sort provides a mock function for the type SubTaskMetaSorter
func (_mock *SubTaskMetaSorter) Sort() ([]plugin.SubTaskMeta, errors.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sort")
	}

	var r0 []plugin.SubTaskMeta
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func() ([]plugin.SubTaskMeta, errors.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []plugin.SubTaskMeta); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.SubTaskMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() errors.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// SubTaskMetaSorter_Sort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sort'
type SubTaskMetaSorter_Sort_Call struct {
	*mock.Call
}

// Sort is a helper method to define mock.On call
func (_e *SubTaskMetaSorter_Expecter) Sort() *SubTaskMetaSorter_Sort_Call {
	return &SubTaskMetaSorter_Sort_Call{Call: _e.mock.On("Sort")}
}

func (_c *SubTaskMetaSorter_Sort_Call) Run(run func()) *SubTaskMetaSorter_Sort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskMetaSorter_Sort_Call) Return(subTaskMetas []plugin.SubTaskMeta, error errors.Error) *SubTaskMetaSorter_Sort_Call {
	_c.Call.Return(subTaskMetas, error)
	return _c
}

func (_c *SubTaskMetaSorter_Sort_Call) RunAndReturn(run func() ([]plugin.SubTaskMeta, errors.Error)) *SubTaskMetaSorter_Sort_Call {
	_c.Call.Return(run)
	return _c
}
