// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reflect"

	mock "github.com/stretchr/testify/mock"
)

// NewColumnMeta creates a new instance of ColumnMeta. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewColumnMeta(t interface {
	mock.TestingT
	Cleanup(func())
}) *ColumnMeta {
	mock := &ColumnMeta{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ColumnMeta is an autogenerated mock type for the ColumnMeta type
type ColumnMeta struct {
	mock.Mock
}

type ColumnMeta_Expecter struct {
	mock *mock.Mock
}

func (_m *ColumnMeta) EXPECT() *ColumnMeta_Expecter {
	return &ColumnMeta_Expecter{mock: &_m.Mock}
}

// AutoIncrement provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) AutoIncrement() (bool, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoIncrement")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (bool, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_AutoIncrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoIncrement'
type ColumnMeta_AutoIncrement_Call struct {
	*mock.Call
}

// AutoIncrement is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) AutoIncrement() *ColumnMeta_AutoIncrement_Call {
	return &ColumnMeta_AutoIncrement_Call{Call: _e.mock.On("AutoIncrement")}
}

func (_c *ColumnMeta_AutoIncrement_Call) Run(run func()) *ColumnMeta_AutoIncrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_AutoIncrement_Call) Return(isAutoIncrement bool, ok bool) *ColumnMeta_AutoIncrement_Call {
	_c.Call.Return(isAutoIncrement, ok)
	return _c
}

func (_c *ColumnMeta_AutoIncrement_Call) RunAndReturn(run func() (bool, bool)) *ColumnMeta_AutoIncrement_Call {
	_c.Call.Return(run)
	return _c
}

// ColumnType provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) ColumnType() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ColumnType")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_ColumnType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ColumnType'
type ColumnMeta_ColumnType_Call struct {
	*mock.Call
}

// ColumnType is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) ColumnType() *ColumnMeta_ColumnType_Call {
	return &ColumnMeta_ColumnType_Call{Call: _e.mock.On("ColumnType")}
}

func (_c *ColumnMeta_ColumnType_Call) Run(run func()) *ColumnMeta_ColumnType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_ColumnType_Call) Return(columnType string, ok bool) *ColumnMeta_ColumnType_Call {
	_c.Call.Return(columnType, ok)
	return _c
}

func (_c *ColumnMeta_ColumnType_Call) RunAndReturn(run func() (string, bool)) *ColumnMeta_ColumnType_Call {
	_c.Call.Return(run)
	return _c
}

// Comment provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) Comment() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Comment")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_Comment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Comment'
type ColumnMeta_Comment_Call struct {
	*mock.Call
}

// Comment is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) Comment() *ColumnMeta_Comment_Call {
	return &ColumnMeta_Comment_Call{Call: _e.mock.On("Comment")}
}

func (_c *ColumnMeta_Comment_Call) Run(run func()) *ColumnMeta_Comment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_Comment_Call) Return(value string, ok bool) *ColumnMeta_Comment_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *ColumnMeta_Comment_Call) RunAndReturn(run func() (string, bool)) *ColumnMeta_Comment_Call {
	_c.Call.Return(run)
	return _c
}

// DatabaseTypeName provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) DatabaseTypeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseTypeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ColumnMeta_DatabaseTypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseTypeName'
type ColumnMeta_DatabaseTypeName_Call struct {
	*mock.Call
}

// DatabaseTypeName is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) DatabaseTypeName() *ColumnMeta_DatabaseTypeName_Call {
	return &ColumnMeta_DatabaseTypeName_Call{Call: _e.mock.On("DatabaseTypeName")}
}

func (_c *ColumnMeta_DatabaseTypeName_Call) Run(run func()) *ColumnMeta_DatabaseTypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_DatabaseTypeName_Call) Return(s string) *ColumnMeta_DatabaseTypeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ColumnMeta_DatabaseTypeName_Call) RunAndReturn(run func() string) *ColumnMeta_DatabaseTypeName_Call {
	_c.Call.Return(run)
	return _c
}

// DecimalSize provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) DecimalSize() (int64, int64, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DecimalSize")
	}

	var r0 int64
	var r1 int64
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func() (int64, int64, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() int64); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func() bool); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// ColumnMeta_DecimalSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecimalSize'
type ColumnMeta_DecimalSize_Call struct {
	*mock.Call
}

// DecimalSize is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) DecimalSize() *ColumnMeta_DecimalSize_Call {
	return &ColumnMeta_DecimalSize_Call{Call: _e.mock.On("DecimalSize")}
}

func (_c *ColumnMeta_DecimalSize_Call) Run(run func()) *ColumnMeta_DecimalSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_DecimalSize_Call) Return(precision int64, scale int64, ok bool) *ColumnMeta_DecimalSize_Call {
	_c.Call.Return(precision, scale, ok)
	return _c
}

func (_c *ColumnMeta_DecimalSize_Call) RunAndReturn(run func() (int64, int64, bool)) *ColumnMeta_DecimalSize_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultValue provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) DefaultValue() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultValue")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_DefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultValue'
type ColumnMeta_DefaultValue_Call struct {
	*mock.Call
}

// DefaultValue is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) DefaultValue() *ColumnMeta_DefaultValue_Call {
	return &ColumnMeta_DefaultValue_Call{Call: _e.mock.On("DefaultValue")}
}

func (_c *ColumnMeta_DefaultValue_Call) Run(run func()) *ColumnMeta_DefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_DefaultValue_Call) Return(value string, ok bool) *ColumnMeta_DefaultValue_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *ColumnMeta_DefaultValue_Call) RunAndReturn(run func() (string, bool)) *ColumnMeta_DefaultValue_Call {
	_c.Call.Return(run)
	return _c
}

// Length provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) Length() (int64, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 int64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (int64, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type ColumnMeta_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) Length() *ColumnMeta_Length_Call {
	return &ColumnMeta_Length_Call{Call: _e.mock.On("Length")}
}

func (_c *ColumnMeta_Length_Call) Run(run func()) *ColumnMeta_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_Length_Call) Return(length int64, ok bool) *ColumnMeta_Length_Call {
	_c.Call.Return(length, ok)
	return _c
}

func (_c *ColumnMeta_Length_Call) RunAndReturn(run func() (int64, bool)) *ColumnMeta_Length_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ColumnMeta_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ColumnMeta_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) Name() *ColumnMeta_Name_Call {
	return &ColumnMeta_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ColumnMeta_Name_Call) Run(run func()) *ColumnMeta_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_Name_Call) Return(s string) *ColumnMeta_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ColumnMeta_Name_Call) RunAndReturn(run func() string) *ColumnMeta_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Nullable provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) Nullable() (bool, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nullable")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (bool, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_Nullable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nullable'
type ColumnMeta_Nullable_Call struct {
	*mock.Call
}

// Nullable is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) Nullable() *ColumnMeta_Nullable_Call {
	return &ColumnMeta_Nullable_Call{Call: _e.mock.On("Nullable")}
}

func (_c *ColumnMeta_Nullable_Call) Run(run func()) *ColumnMeta_Nullable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_Nullable_Call) Return(nullable bool, ok bool) *ColumnMeta_Nullable_Call {
	_c.Call.Return(nullable, ok)
	return _c
}

func (_c *ColumnMeta_Nullable_Call) RunAndReturn(run func() (bool, bool)) *ColumnMeta_Nullable_Call {
	_c.Call.Return(run)
	return _c
}

// PrimaryKey provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) PrimaryKey() (bool, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrimaryKey")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (bool, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_PrimaryKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrimaryKey'
type ColumnMeta_PrimaryKey_Call struct {
	*mock.Call
}

// PrimaryKey is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) PrimaryKey() *ColumnMeta_PrimaryKey_Call {
	return &ColumnMeta_PrimaryKey_Call{Call: _e.mock.On("PrimaryKey")}
}

func (_c *ColumnMeta_PrimaryKey_Call) Run(run func()) *ColumnMeta_PrimaryKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_PrimaryKey_Call) Return(isPrimaryKey bool, ok bool) *ColumnMeta_PrimaryKey_Call {
	_c.Call.Return(isPrimaryKey, ok)
	return _c
}

func (_c *ColumnMeta_PrimaryKey_Call) RunAndReturn(run func() (bool, bool)) *ColumnMeta_PrimaryKey_Call {
	_c.Call.Return(run)
	return _c
}

// ScanType provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) ScanType() reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScanType")
	}

	var r0 reflect.Type
	if returnFunc, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}
	return r0
}

// ColumnMeta_ScanType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanType'
type ColumnMeta_ScanType_Call struct {
	*mock.Call
}

// ScanType is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) ScanType() *ColumnMeta_ScanType_Call {
	return &ColumnMeta_ScanType_Call{Call: _e.mock.On("ScanType")}
}

func (_c *ColumnMeta_ScanType_Call) Run(run func()) *ColumnMeta_ScanType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_ScanType_Call) Return(typeParam reflect.Type) *ColumnMeta_ScanType_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *ColumnMeta_ScanType_Call) RunAndReturn(run func() reflect.Type) *ColumnMeta_ScanType_Call {
	_c.Call.Return(run)
	return _c
}

// Unique provides a mock function for the type ColumnMeta
func (_mock *ColumnMeta) Unique() (bool, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unique")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (bool, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ColumnMeta_Unique_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unique'
type ColumnMeta_Unique_Call struct {
	*mock.Call
}

// Unique is a helper method to define mock.On call
func (_e *ColumnMeta_Expecter) Unique() *ColumnMeta_Unique_Call {
	return &ColumnMeta_Unique_Call{Call: _e.mock.On("Unique")}
}

func (_c *ColumnMeta_Unique_Call) Run(run func()) *ColumnMeta_Unique_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ColumnMeta_Unique_Call) Return(unique bool, ok bool) *ColumnMeta_Unique_Call {
	_c.Call.Return(unique, ok)
	return _c
}

func (_c *ColumnMeta_Unique_Call) RunAndReturn(run func() (bool, bool)) *ColumnMeta_Unique_Call {
	_c.Call.Return(run)
	return _c
}
