// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql"
	"reflect"

	"github.com/apache/devlake/core/dal"
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewDal creates a new instance of Dal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDal(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dal {
	mock := &Dal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Dal is an autogenerated mock type for the Dal type
type Dal struct {
	mock.Mock
}

type Dal_Expecter struct {
	mock *mock.Mock
}

func (_m *Dal) EXPECT() *Dal_Expecter {
	return &Dal_Expecter{mock: &_m.Mock}
}

// AddColumn provides a mock function for the type Dal
func (_mock *Dal) AddColumn(table string, columnName string, columnType dal.ColumnType) errors.Error {
	ret := _mock.Called(table, columnName, columnType)

	if len(ret) == 0 {
		panic("no return value specified for AddColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, dal.ColumnType) errors.Error); ok {
		r0 = returnFunc(table, columnName, columnType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_AddColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddColumn'
type Dal_AddColumn_Call struct {
	*mock.Call
}

// AddColumn is a helper method to define mock.On call
//   - table string
//   - columnName string
//   - columnType dal.ColumnType
func (_e *Dal_Expecter) AddColumn(table any, columnName any, columnType any) *Dal_AddColumn_Call {
	return &Dal_AddColumn_Call{Call: _e.mock.On("AddColumn", table, columnName, columnType)}
}

func (_c *Dal_AddColumn_Call) Run(run func(table string, columnName string, columnType dal.ColumnType)) *Dal_AddColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dal.ColumnType
		if args[2] != nil {
			arg2 = args[2].(dal.ColumnType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Dal_AddColumn_Call) Return(error errors.Error) *Dal_AddColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_AddColumn_Call) RunAndReturn(run func(table string, columnName string, columnType dal.ColumnType) errors.Error) *Dal_AddColumn_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type Dal
func (_mock *Dal) All(dst interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(dst, clauses)
	} else {
		tmpRet = _mock.Called(dst)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(dst, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type Dal_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - dst interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) All(dst any, clauses ...any) *Dal_All_Call {
	return &Dal_All_Call{Call: _e.mock.On("All",
		append([]any{dst}, clauses...)...)}
}

func (_c *Dal_All_Call) Run(run func(dst interface{}, clauses ...dal.Clause)) *Dal_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_All_Call) Return(error errors.Error) *Dal_All_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_All_Call) RunAndReturn(run func(dst interface{}, clauses ...dal.Clause) errors.Error) *Dal_All_Call {
	_c.Call.Return(run)
	return _c
}

// AllTables provides a mock function for the type Dal
func (_mock *Dal) AllTables() ([]string, errors.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllTables")
	}

	var r0 []string
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func() ([]string, errors.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() errors.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Dal_AllTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllTables'
type Dal_AllTables_Call struct {
	*mock.Call
}

// AllTables is a helper method to define mock.On call
func (_e *Dal_Expecter) AllTables() *Dal_AllTables_Call {
	return &Dal_AllTables_Call{Call: _e.mock.On("AllTables")}
}

func (_c *Dal_AllTables_Call) Run(run func()) *Dal_AllTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dal_AllTables_Call) Return(strings []string, error errors.Error) *Dal_AllTables_Call {
	_c.Call.Return(strings, error)
	return _c
}

func (_c *Dal_AllTables_Call) RunAndReturn(run func() ([]string, errors.Error)) *Dal_AllTables_Call {
	_c.Call.Return(run)
	return _c
}

// AutoMigrate provides a mock function for the type Dal
func (_mock *Dal) AutoMigrate(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AutoMigrate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_AutoMigrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoMigrate'
type Dal_AutoMigrate_Call struct {
	*mock.Call
}

// AutoMigrate is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) AutoMigrate(entity any, clauses ...any) *Dal_AutoMigrate_Call {
	return &Dal_AutoMigrate_Call{Call: _e.mock.On("AutoMigrate",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_AutoMigrate_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_AutoMigrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_AutoMigrate_Call) Return(error errors.Error) *Dal_AutoMigrate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_AutoMigrate_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_AutoMigrate_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type Dal
func (_mock *Dal) Begin() dal.Transaction {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 dal.Transaction
	if returnFunc, ok := ret.Get(0).(func() dal.Transaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Transaction)
		}
	}
	return r0
}

// Dal_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type Dal_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *Dal_Expecter) Begin() *Dal_Begin_Call {
	return &Dal_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *Dal_Begin_Call) Run(run func()) *Dal_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dal_Begin_Call) Return(transaction dal.Transaction) *Dal_Begin_Call {
	_c.Call.Return(transaction)
	return _c
}

func (_c *Dal_Begin_Call) RunAndReturn(run func() dal.Transaction) *Dal_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type Dal
func (_mock *Dal) Count(clauses ...dal.Clause) (int64, errors.Error) {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(clauses)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) (int64, errors.Error)); ok {
		return returnFunc(clauses...)
	}
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) int64); ok {
		r0 = returnFunc(clauses...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(...dal.Clause) errors.Error); ok {
		r1 = returnFunc(clauses...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Dal_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Dal_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Count(clauses ...any) *Dal_Count_Call {
	return &Dal_Count_Call{Call: _e.mock.On("Count",
		append([]any{}, clauses...)...)}
}

func (_c *Dal_Count_Call) Run(run func(clauses ...dal.Clause)) *Dal_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 0 {
			variadicArgs = args[0].([]dal.Clause)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Dal_Count_Call) Return(n int64, error errors.Error) *Dal_Count_Call {
	_c.Call.Return(n, error)
	return _c
}

func (_c *Dal_Count_Call) RunAndReturn(run func(clauses ...dal.Clause) (int64, errors.Error)) *Dal_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Dal
func (_mock *Dal) Create(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Dal_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Create(entity any, clauses ...any) *Dal_Create_Call {
	return &Dal_Create_Call{Call: _e.mock.On("Create",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_Create_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_Create_Call) Return(error errors.Error) *Dal_Create_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Create_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIfNotExist provides a mock function for the type Dal
func (_mock *Dal) CreateIfNotExist(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateIfNotExist")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_CreateIfNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIfNotExist'
type Dal_CreateIfNotExist_Call struct {
	*mock.Call
}

// CreateIfNotExist is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) CreateIfNotExist(entity any, clauses ...any) *Dal_CreateIfNotExist_Call {
	return &Dal_CreateIfNotExist_Call{Call: _e.mock.On("CreateIfNotExist",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_CreateIfNotExist_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_CreateIfNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_CreateIfNotExist_Call) Return(error errors.Error) *Dal_CreateIfNotExist_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_CreateIfNotExist_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_CreateIfNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdate provides a mock function for the type Dal
func (_mock *Dal) CreateOrUpdate(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type Dal_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) CreateOrUpdate(entity any, clauses ...any) *Dal_CreateOrUpdate_Call {
	return &Dal_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_CreateOrUpdate_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_CreateOrUpdate_Call) Return(error errors.Error) *Dal_CreateOrUpdate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_CreateOrUpdate_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithMap provides a mock function for the type Dal
func (_mock *Dal) CreateWithMap(entity interface{}, record map[string]interface{}) errors.Error {
	ret := _mock.Called(entity, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithMap")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, map[string]interface{}) errors.Error); ok {
		r0 = returnFunc(entity, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_CreateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithMap'
type Dal_CreateWithMap_Call struct {
	*mock.Call
}

// CreateWithMap is a helper method to define mock.On call
//   - entity interface{}
//   - record map[string]interface{}
func (_e *Dal_Expecter) CreateWithMap(entity any, record any) *Dal_CreateWithMap_Call {
	return &Dal_CreateWithMap_Call{Call: _e.mock.On("CreateWithMap", entity, record)}
}

func (_c *Dal_CreateWithMap_Call) Run(run func(entity interface{}, record map[string]interface{})) *Dal_CreateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dal_CreateWithMap_Call) Return(error errors.Error) *Dal_CreateWithMap_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_CreateWithMap_Call) RunAndReturn(run func(entity interface{}, record map[string]interface{}) errors.Error) *Dal_CreateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// Cursor provides a mock function for the type Dal
func (_mock *Dal) Cursor(clauses ...dal.Clause) (dal.Rows, errors.Error) {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(clauses)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Cursor")
	}

	var r0 dal.Rows
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) (dal.Rows, errors.Error)); ok {
		return returnFunc(clauses...)
	}
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) dal.Rows); ok {
		r0 = returnFunc(clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...dal.Clause) errors.Error); ok {
		r1 = returnFunc(clauses...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Dal_Cursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cursor'
type Dal_Cursor_Call struct {
	*mock.Call
}

// Cursor is a helper method to define mock.On call
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Cursor(clauses ...any) *Dal_Cursor_Call {
	return &Dal_Cursor_Call{Call: _e.mock.On("Cursor",
		append([]any{}, clauses...)...)}
}

func (_c *Dal_Cursor_Call) Run(run func(clauses ...dal.Clause)) *Dal_Cursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 0 {
			variadicArgs = args[0].([]dal.Clause)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Dal_Cursor_Call) Return(rows dal.Rows, error errors.Error) *Dal_Cursor_Call {
	_c.Call.Return(rows, error)
	return _c
}

func (_c *Dal_Cursor_Call) RunAndReturn(run func(clauses ...dal.Clause) (dal.Rows, errors.Error)) *Dal_Cursor_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Dal
func (_mock *Dal) Delete(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Dal_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Delete(entity any, clauses ...any) *Dal_Delete_Call {
	return &Dal_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_Delete_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_Delete_Call) Return(error errors.Error) *Dal_Delete_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Delete_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Dialect provides a mock function for the type Dal
func (_mock *Dal) Dialect() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dialect")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Dal_Dialect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dialect'
type Dal_Dialect_Call struct {
	*mock.Call
}

// Dialect is a helper method to define mock.On call
func (_e *Dal_Expecter) Dialect() *Dal_Dialect_Call {
	return &Dal_Dialect_Call{Call: _e.mock.On("Dialect")}
}

func (_c *Dal_Dialect_Call) Run(run func()) *Dal_Dialect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dal_Dialect_Call) Return(s string) *Dal_Dialect_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Dal_Dialect_Call) RunAndReturn(run func() string) *Dal_Dialect_Call {
	_c.Call.Return(run)
	return _c
}

// DropColumns provides a mock function for the type Dal
func (_mock *Dal) DropColumns(table string, columnName ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(columnName) > 0 {
		tmpRet = _mock.Called(table, columnName)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropColumns")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, columnName...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_DropColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropColumns'
type Dal_DropColumns_Call struct {
	*mock.Call
}

// DropColumns is a helper method to define mock.On call
//   - table string
//   - columnName ...string
func (_e *Dal_Expecter) DropColumns(table any, columnName ...any) *Dal_DropColumns_Call {
	return &Dal_DropColumns_Call{Call: _e.mock.On("DropColumns",
		append([]any{table}, columnName...)...)}
}

func (_c *Dal_DropColumns_Call) Run(run func(table string, columnName ...string)) *Dal_DropColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_DropColumns_Call) Return(error errors.Error) *Dal_DropColumns_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_DropColumns_Call) RunAndReturn(run func(table string, columnName ...string) errors.Error) *Dal_DropColumns_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndex provides a mock function for the type Dal
func (_mock *Dal) DropIndex(table string, columnNames ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(columnNames) > 0 {
		tmpRet = _mock.Called(table, columnNames)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropIndex")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, columnNames...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_DropIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndex'
type Dal_DropIndex_Call struct {
	*mock.Call
}

// DropIndex is a helper method to define mock.On call
//   - table string
//   - columnNames ...string
func (_e *Dal_Expecter) DropIndex(table any, columnNames ...any) *Dal_DropIndex_Call {
	return &Dal_DropIndex_Call{Call: _e.mock.On("DropIndex",
		append([]any{table}, columnNames...)...)}
}

func (_c *Dal_DropIndex_Call) Run(run func(table string, columnNames ...string)) *Dal_DropIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_DropIndex_Call) Return(error errors.Error) *Dal_DropIndex_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_DropIndex_Call) RunAndReturn(run func(table string, columnNames ...string) errors.Error) *Dal_DropIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndexes provides a mock function for the type Dal
func (_mock *Dal) DropIndexes(table string, indexes ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(indexes) > 0 {
		tmpRet = _mock.Called(table, indexes)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropIndexes")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, indexes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_DropIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndexes'
type Dal_DropIndexes_Call struct {
	*mock.Call
}

// DropIndexes is a helper method to define mock.On call
//   - table string
//   - indexes ...string
func (_e *Dal_Expecter) DropIndexes(table any, indexes ...any) *Dal_DropIndexes_Call {
	return &Dal_DropIndexes_Call{Call: _e.mock.On("DropIndexes",
		append([]any{table}, indexes...)...)}
}

func (_c *Dal_DropIndexes_Call) Run(run func(table string, indexes ...string)) *Dal_DropIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_DropIndexes_Call) Return(error errors.Error) *Dal_DropIndexes_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_DropIndexes_Call) RunAndReturn(run func(table string, indexes ...string) errors.Error) *Dal_DropIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// DropTables provides a mock function for the type Dal
func (_mock *Dal) DropTables(dst ...interface{}) errors.Error {
	var tmpRet mock.Arguments
	if len(dst) > 0 {
		tmpRet = _mock.Called(dst)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropTables")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) errors.Error); ok {
		r0 = returnFunc(dst...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_DropTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropTables'
type Dal_DropTables_Call struct {
	*mock.Call
}

// DropTables is a helper method to define mock.On call
//   - dst ...interface{}
func (_e *Dal_Expecter) DropTables(dst ...any) *Dal_DropTables_Call {
	return &Dal_DropTables_Call{Call: _e.mock.On("DropTables",
		append([]any{}, dst...)...)}
}

func (_c *Dal_DropTables_Call) Run(run func(dst ...interface{})) *Dal_DropTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Dal_DropTables_Call) Return(error errors.Error) *Dal_DropTables_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_DropTables_Call) RunAndReturn(run func(dst ...interface{}) errors.Error) *Dal_DropTables_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type Dal
func (_mock *Dal) Exec(query string, params ...interface{}) errors.Error {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(query, params)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) errors.Error); ok {
		r0 = returnFunc(query, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Dal_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - params ...interface{}
func (_e *Dal_Expecter) Exec(query any, params ...any) *Dal_Exec_Call {
	return &Dal_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{query}, params...)...)}
}

func (_c *Dal_Exec_Call) Run(run func(query string, params ...interface{})) *Dal_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_Exec_Call) Return(error errors.Error) *Dal_Exec_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Exec_Call) RunAndReturn(run func(query string, params ...interface{}) errors.Error) *Dal_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type Dal
func (_mock *Dal) Fetch(cursor dal.Rows, dst interface{}) errors.Error {
	ret := _mock.Called(cursor, dst)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(dal.Rows, interface{}) errors.Error); ok {
		r0 = returnFunc(cursor, dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Dal_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - cursor dal.Rows
//   - dst interface{}
func (_e *Dal_Expecter) Fetch(cursor any, dst any) *Dal_Fetch_Call {
	return &Dal_Fetch_Call{Call: _e.mock.On("Fetch", cursor, dst)}
}

func (_c *Dal_Fetch_Call) Run(run func(cursor dal.Rows, dst interface{})) *Dal_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.Rows
		if args[0] != nil {
			arg0 = args[0].(dal.Rows)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dal_Fetch_Call) Return(error errors.Error) *Dal_Fetch_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Fetch_Call) RunAndReturn(run func(cursor dal.Rows, dst interface{}) errors.Error) *Dal_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// First provides a mock function for the type Dal
func (_mock *Dal) First(dst interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(dst, clauses)
	} else {
		tmpRet = _mock.Called(dst)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(dst, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_First_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'First'
type Dal_First_Call struct {
	*mock.Call
}

// First is a helper method to define mock.On call
//   - dst interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) First(dst any, clauses ...any) *Dal_First_Call {
	return &Dal_First_Call{Call: _e.mock.On("First",
		append([]any{dst}, clauses...)...)}
}

func (_c *Dal_First_Call) Run(run func(dst interface{}, clauses ...dal.Clause)) *Dal_First_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_First_Call) Return(error errors.Error) *Dal_First_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_First_Call) RunAndReturn(run func(dst interface{}, clauses ...dal.Clause) errors.Error) *Dal_First_Call {
	_c.Call.Return(run)
	return _c
}

// GetColumns provides a mock function for the type Dal
func (_mock *Dal) GetColumns(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error) {
	ret := _mock.Called(dst, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetColumns")
	}

	var r0 []dal.ColumnMeta
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error)); ok {
		return returnFunc(dst, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) []dal.ColumnMeta); ok {
		r0 = returnFunc(dst, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dal.ColumnMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) errors.Error); ok {
		r1 = returnFunc(dst, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Dal_GetColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColumns'
type Dal_GetColumns_Call struct {
	*mock.Call
}

// GetColumns is a helper method to define mock.On call
//   - dst dal.Tabler
//   - filter func(columnMeta dal.ColumnMeta) bool
func (_e *Dal_Expecter) GetColumns(dst any, filter any) *Dal_GetColumns_Call {
	return &Dal_GetColumns_Call{Call: _e.mock.On("GetColumns", dst, filter)}
}

func (_c *Dal_GetColumns_Call) Run(run func(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool)) *Dal_GetColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.Tabler
		if args[0] != nil {
			arg0 = args[0].(dal.Tabler)
		}
		var arg1 func(columnMeta dal.ColumnMeta) bool
		if args[1] != nil {
			arg1 = args[1].(func(columnMeta dal.ColumnMeta) bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dal_GetColumns_Call) Return(cms []dal.ColumnMeta, err errors.Error) *Dal_GetColumns_Call {
	_c.Call.Return(cms, err)
	return _c
}

func (_c *Dal_GetColumns_Call) RunAndReturn(run func(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error)) *Dal_GetColumns_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrimaryKeyFields provides a mock function for the type Dal
func (_mock *Dal) GetPrimaryKeyFields(t reflect.Type) []reflect.StructField {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimaryKeyFields")
	}

	var r0 []reflect.StructField
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []reflect.StructField); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reflect.StructField)
		}
	}
	return r0
}

// Dal_GetPrimaryKeyFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrimaryKeyFields'
type Dal_GetPrimaryKeyFields_Call struct {
	*mock.Call
}

// GetPrimaryKeyFields is a helper method to define mock.On call
//   - t reflect.Type
func (_e *Dal_Expecter) GetPrimaryKeyFields(t any) *Dal_GetPrimaryKeyFields_Call {
	return &Dal_GetPrimaryKeyFields_Call{Call: _e.mock.On("GetPrimaryKeyFields", t)}
}

func (_c *Dal_GetPrimaryKeyFields_Call) Run(run func(t reflect.Type)) *Dal_GetPrimaryKeyFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dal_GetPrimaryKeyFields_Call) Return(structFields []reflect.StructField) *Dal_GetPrimaryKeyFields_Call {
	_c.Call.Return(structFields)
	return _c
}

func (_c *Dal_GetPrimaryKeyFields_Call) RunAndReturn(run func(t reflect.Type) []reflect.StructField) *Dal_GetPrimaryKeyFields_Call {
	_c.Call.Return(run)
	return _c
}

// HasColumn provides a mock function for the type Dal
func (_mock *Dal) HasColumn(table interface{}, columnName string) bool {
	ret := _mock.Called(table, columnName)

	if len(ret) == 0 {
		panic("no return value specified for HasColumn")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(interface{}, string) bool); ok {
		r0 = returnFunc(table, columnName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Dal_HasColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasColumn'
type Dal_HasColumn_Call struct {
	*mock.Call
}

// HasColumn is a helper method to define mock.On call
//   - table interface{}
//   - columnName string
func (_e *Dal_Expecter) HasColumn(table any, columnName any) *Dal_HasColumn_Call {
	return &Dal_HasColumn_Call{Call: _e.mock.On("HasColumn", table, columnName)}
}

func (_c *Dal_HasColumn_Call) Run(run func(table interface{}, columnName string)) *Dal_HasColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dal_HasColumn_Call) Return(b bool) *Dal_HasColumn_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Dal_HasColumn_Call) RunAndReturn(run func(table interface{}, columnName string) bool) *Dal_HasColumn_Call {
	_c.Call.Return(run)
	return _c
}

// HasTable provides a mock function for the type Dal
func (_mock *Dal) HasTable(table interface{}) bool {
	ret := _mock.Called(table)

	if len(ret) == 0 {
		panic("no return value specified for HasTable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = returnFunc(table)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Dal_HasTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasTable'
type Dal_HasTable_Call struct {
	*mock.Call
}

// HasTable is a helper method to define mock.On call
//   - table interface{}
func (_e *Dal_Expecter) HasTable(table any) *Dal_HasTable_Call {
	return &Dal_HasTable_Call{Call: _e.mock.On("HasTable", table)}
}

func (_c *Dal_HasTable_Call) Run(run func(table interface{})) *Dal_HasTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dal_HasTable_Call) Return(b bool) *Dal_HasTable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Dal_HasTable_Call) RunAndReturn(run func(table interface{}) bool) *Dal_HasTable_Call {
	_c.Call.Return(run)
	return _c
}

// IsDuplicationError provides a mock function for the type Dal
func (_mock *Dal) IsDuplicationError(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicationError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Dal_IsDuplicationError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicationError'
type Dal_IsDuplicationError_Call struct {
	*mock.Call
}

// IsDuplicationError is a helper method to define mock.On call
//   - err error
func (_e *Dal_Expecter) IsDuplicationError(err any) *Dal_IsDuplicationError_Call {
	return &Dal_IsDuplicationError_Call{Call: _e.mock.On("IsDuplicationError", err)}
}

func (_c *Dal_IsDuplicationError_Call) Run(run func(err error)) *Dal_IsDuplicationError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dal_IsDuplicationError_Call) Return(b bool) *Dal_IsDuplicationError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Dal_IsDuplicationError_Call) RunAndReturn(run func(err error) bool) *Dal_IsDuplicationError_Call {
	_c.Call.Return(run)
	return _c
}

// IsErrorNotFound provides a mock function for the type Dal
func (_mock *Dal) IsErrorNotFound(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsErrorNotFound")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Dal_IsErrorNotFound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsErrorNotFound'
type Dal_IsErrorNotFound_Call struct {
	*mock.Call
}

// IsErrorNotFound is a helper method to define mock.On call
//   - err error
func (_e *Dal_Expecter) IsErrorNotFound(err any) *Dal_IsErrorNotFound_Call {
	return &Dal_IsErrorNotFound_Call{Call: _e.mock.On("IsErrorNotFound", err)}
}

func (_c *Dal_IsErrorNotFound_Call) Run(run func(err error)) *Dal_IsErrorNotFound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dal_IsErrorNotFound_Call) Return(b bool) *Dal_IsErrorNotFound_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Dal_IsErrorNotFound_Call) RunAndReturn(run func(err error) bool) *Dal_IsErrorNotFound_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyColumnType provides a mock function for the type Dal
func (_mock *Dal) ModifyColumnType(table string, columnName string, columnType string) errors.Error {
	ret := _mock.Called(table, columnName, columnType)

	if len(ret) == 0 {
		panic("no return value specified for ModifyColumnType")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) errors.Error); ok {
		r0 = returnFunc(table, columnName, columnType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_ModifyColumnType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyColumnType'
type Dal_ModifyColumnType_Call struct {
	*mock.Call
}

// ModifyColumnType is a helper method to define mock.On call
//   - table string
//   - columnName string
//   - columnType string
func (_e *Dal_Expecter) ModifyColumnType(table any, columnName any, columnType any) *Dal_ModifyColumnType_Call {
	return &Dal_ModifyColumnType_Call{Call: _e.mock.On("ModifyColumnType", table, columnName, columnType)}
}

func (_c *Dal_ModifyColumnType_Call) Run(run func(table string, columnName string, columnType string)) *Dal_ModifyColumnType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Dal_ModifyColumnType_Call) Return(error errors.Error) *Dal_ModifyColumnType_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_ModifyColumnType_Call) RunAndReturn(run func(table string, columnName string, columnType string) errors.Error) *Dal_ModifyColumnType_Call {
	_c.Call.Return(run)
	return _c
}

// Pluck provides a mock function for the type Dal
func (_mock *Dal) Pluck(column string, dest interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(column, dest, clauses)
	} else {
		tmpRet = _mock.Called(column, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Pluck")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(column, dest, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Pluck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pluck'
type Dal_Pluck_Call struct {
	*mock.Call
}

// Pluck is a helper method to define mock.On call
//   - column string
//   - dest interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Pluck(column any, dest any, clauses ...any) *Dal_Pluck_Call {
	return &Dal_Pluck_Call{Call: _e.mock.On("Pluck",
		append([]any{column, dest}, clauses...)...)}
}

func (_c *Dal_Pluck_Call) Run(run func(column string, dest interface{}, clauses ...dal.Clause)) *Dal_Pluck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 2 {
			variadicArgs = args[2].([]dal.Clause)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Dal_Pluck_Call) Return(error errors.Error) *Dal_Pluck_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Pluck_Call) RunAndReturn(run func(column string, dest interface{}, clauses ...dal.Clause) errors.Error) *Dal_Pluck_Call {
	_c.Call.Return(run)
	return _c
}

// RawCursor provides a mock function for the type Dal
func (_mock *Dal) RawCursor(query string, params ...interface{}) (*sql.Rows, errors.Error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(query, params)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RawCursor")
	}

	var r0 *sql.Rows
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, errors.Error)); ok {
		return returnFunc(query, params...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = returnFunc(query, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...interface{}) errors.Error); ok {
		r1 = returnFunc(query, params...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Dal_RawCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawCursor'
type Dal_RawCursor_Call struct {
	*mock.Call
}

// RawCursor is a helper method to define mock.On call
//   - query string
//   - params ...interface{}
func (_e *Dal_Expecter) RawCursor(query any, params ...any) *Dal_RawCursor_Call {
	return &Dal_RawCursor_Call{Call: _e.mock.On("RawCursor",
		append([]any{query}, params...)...)}
}

func (_c *Dal_RawCursor_Call) Run(run func(query string, params ...interface{})) *Dal_RawCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_RawCursor_Call) Return(rows *sql.Rows, error errors.Error) *Dal_RawCursor_Call {
	_c.Call.Return(rows, error)
	return _c
}

func (_c *Dal_RawCursor_Call) RunAndReturn(run func(query string, params ...interface{}) (*sql.Rows, errors.Error)) *Dal_RawCursor_Call {
	_c.Call.Return(run)
	return _c
}

// RenameColumn provides a mock function for the type Dal
func (_mock *Dal) RenameColumn(table string, oldColumnName string, newColumnName string) errors.Error {
	ret := _mock.Called(table, oldColumnName, newColumnName)

	if len(ret) == 0 {
		panic("no return value specified for RenameColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) errors.Error); ok {
		r0 = returnFunc(table, oldColumnName, newColumnName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_RenameColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameColumn'
type Dal_RenameColumn_Call struct {
	*mock.Call
}

// RenameColumn is a helper method to define mock.On call
//   - table string
//   - oldColumnName string
//   - newColumnName string
func (_e *Dal_Expecter) RenameColumn(table any, oldColumnName any, newColumnName any) *Dal_RenameColumn_Call {
	return &Dal_RenameColumn_Call{Call: _e.mock.On("RenameColumn", table, oldColumnName, newColumnName)}
}

func (_c *Dal_RenameColumn_Call) Run(run func(table string, oldColumnName string, newColumnName string)) *Dal_RenameColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Dal_RenameColumn_Call) Return(error errors.Error) *Dal_RenameColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_RenameColumn_Call) RunAndReturn(run func(table string, oldColumnName string, newColumnName string) errors.Error) *Dal_RenameColumn_Call {
	_c.Call.Return(run)
	return _c
}

// RenameTable provides a mock function for the type Dal
func (_mock *Dal) RenameTable(oldName string, newName string) errors.Error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameTable")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string) errors.Error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_RenameTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameTable'
type Dal_RenameTable_Call struct {
	*mock.Call
}

// RenameTable is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *Dal_Expecter) RenameTable(oldName any, newName any) *Dal_RenameTable_Call {
	return &Dal_RenameTable_Call{Call: _e.mock.On("RenameTable", oldName, newName)}
}

func (_c *Dal_RenameTable_Call) Run(run func(oldName string, newName string)) *Dal_RenameTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dal_RenameTable_Call) Return(error errors.Error) *Dal_RenameTable_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_RenameTable_Call) RunAndReturn(run func(oldName string, newName string) errors.Error) *Dal_RenameTable_Call {
	_c.Call.Return(run)
	return _c
}

// Session provides a mock function for the type Dal
func (_mock *Dal) Session(config dal.SessionConfig) dal.Dal {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 dal.Dal
	if returnFunc, ok := ret.Get(0).(func(dal.SessionConfig) dal.Dal); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Dal)
		}
	}
	return r0
}

// Dal_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type Dal_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
//   - config dal.SessionConfig
func (_e *Dal_Expecter) Session(config any) *Dal_Session_Call {
	return &Dal_Session_Call{Call: _e.mock.On("Session", config)}
}

func (_c *Dal_Session_Call) Run(run func(config dal.SessionConfig)) *Dal_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.SessionConfig
		if args[0] != nil {
			arg0 = args[0].(dal.SessionConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dal_Session_Call) Return(dal1 dal.Dal) *Dal_Session_Call {
	_c.Call.Return(dal1)
	return _c
}

func (_c *Dal_Session_Call) RunAndReturn(run func(config dal.SessionConfig) dal.Dal) *Dal_Session_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Dal
func (_mock *Dal) Update(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Dal_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) Update(entity any, clauses ...any) *Dal_Update_Call {
	return &Dal_Update_Call{Call: _e.mock.On("Update",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_Update_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_Update_Call) Return(error errors.Error) *Dal_Update_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_Update_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllColumn provides a mock function for the type Dal
func (_mock *Dal) UpdateAllColumn(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_UpdateAllColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllColumn'
type Dal_UpdateAllColumn_Call struct {
	*mock.Call
}

// UpdateAllColumn is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) UpdateAllColumn(entity any, clauses ...any) *Dal_UpdateAllColumn_Call {
	return &Dal_UpdateAllColumn_Call{Call: _e.mock.On("UpdateAllColumn",
		append([]any{entity}, clauses...)...)}
}

func (_c *Dal_UpdateAllColumn_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Dal_UpdateAllColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Dal_UpdateAllColumn_Call) Return(error errors.Error) *Dal_UpdateAllColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_UpdateAllColumn_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Dal_UpdateAllColumn_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateColumn provides a mock function for the type Dal
func (_mock *Dal) UpdateColumn(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entityOrTable, columnName, value, clauses)
	} else {
		tmpRet = _mock.Called(entityOrTable, columnName, value)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entityOrTable, columnName, value, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_UpdateColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateColumn'
type Dal_UpdateColumn_Call struct {
	*mock.Call
}

// UpdateColumn is a helper method to define mock.On call
//   - entityOrTable interface{}
//   - columnName string
//   - value interface{}
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) UpdateColumn(entityOrTable any, columnName any, value any, clauses ...any) *Dal_UpdateColumn_Call {
	return &Dal_UpdateColumn_Call{Call: _e.mock.On("UpdateColumn",
		append([]any{entityOrTable, columnName, value}, clauses...)...)}
}

func (_c *Dal_UpdateColumn_Call) Run(run func(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause)) *Dal_UpdateColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 3 {
			variadicArgs = args[3].([]dal.Clause)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Dal_UpdateColumn_Call) Return(error errors.Error) *Dal_UpdateColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_UpdateColumn_Call) RunAndReturn(run func(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause) errors.Error) *Dal_UpdateColumn_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateColumns provides a mock function for the type Dal
func (_mock *Dal) UpdateColumns(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entityOrTable, set, clauses)
	} else {
		tmpRet = _mock.Called(entityOrTable, set)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumns")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, []dal.DalSet, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entityOrTable, set, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Dal_UpdateColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateColumns'
type Dal_UpdateColumns_Call struct {
	*mock.Call
}

// UpdateColumns is a helper method to define mock.On call
//   - entityOrTable interface{}
//   - set []dal.DalSet
//   - clauses ...dal.Clause
func (_e *Dal_Expecter) UpdateColumns(entityOrTable any, set any, clauses ...any) *Dal_UpdateColumns_Call {
	return &Dal_UpdateColumns_Call{Call: _e.mock.On("UpdateColumns",
		append([]any{entityOrTable, set}, clauses...)...)}
}

func (_c *Dal_UpdateColumns_Call) Run(run func(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause)) *Dal_UpdateColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.DalSet
		if args[1] != nil {
			arg1 = args[1].([]dal.DalSet)
		}
		var arg2 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 2 {
			variadicArgs = args[2].([]dal.Clause)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Dal_UpdateColumns_Call) Return(error errors.Error) *Dal_UpdateColumns_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Dal_UpdateColumns_Call) RunAndReturn(run func(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause) errors.Error) *Dal_UpdateColumns_Call {
	_c.Call.Return(run)
	return _c
}
