// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql"
	"reflect"

	"github.com/apache/devlake/core/dal"
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewTransaction creates a new instance of Transaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transaction {
	mock := &Transaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

type Transaction_Expecter struct {
	mock *mock.Mock
}

func (_m *Transaction) EXPECT() *Transaction_Expecter {
	return &Transaction_Expecter{mock: &_m.Mock}
}

// AddColumn provides a mock function for the type Transaction
func (_mock *Transaction) AddColumn(table string, columnName string, columnType dal.ColumnType) errors.Error {
	ret := _mock.Called(table, columnName, columnType)

	if len(ret) == 0 {
		panic("no return value specified for AddColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, dal.ColumnType) errors.Error); ok {
		r0 = returnFunc(table, columnName, columnType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_AddColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddColumn'
type Transaction_AddColumn_Call struct {
	*mock.Call
}

// AddColumn is a helper method to define mock.On call
//   - table string
//   - columnName string
//   - columnType dal.ColumnType
func (_e *Transaction_Expecter) AddColumn(table any, columnName any, columnType any) *Transaction_AddColumn_Call {
	return &Transaction_AddColumn_Call{Call: _e.mock.On("AddColumn", table, columnName, columnType)}
}

func (_c *Transaction_AddColumn_Call) Run(run func(table string, columnName string, columnType dal.ColumnType)) *Transaction_AddColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dal.ColumnType
		if args[2] != nil {
			arg2 = args[2].(dal.ColumnType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Transaction_AddColumn_Call) Return(error errors.Error) *Transaction_AddColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_AddColumn_Call) RunAndReturn(run func(table string, columnName string, columnType dal.ColumnType) errors.Error) *Transaction_AddColumn_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type Transaction
func (_mock *Transaction) All(dst interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(dst, clauses)
	} else {
		tmpRet = _mock.Called(dst)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(dst, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type Transaction_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - dst interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) All(dst any, clauses ...any) *Transaction_All_Call {
	return &Transaction_All_Call{Call: _e.mock.On("All",
		append([]any{dst}, clauses...)...)}
}

func (_c *Transaction_All_Call) Run(run func(dst interface{}, clauses ...dal.Clause)) *Transaction_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_All_Call) Return(error errors.Error) *Transaction_All_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_All_Call) RunAndReturn(run func(dst interface{}, clauses ...dal.Clause) errors.Error) *Transaction_All_Call {
	_c.Call.Return(run)
	return _c
}

// AllTables provides a mock function for the type Transaction
func (_mock *Transaction) AllTables() ([]string, errors.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllTables")
	}

	var r0 []string
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func() ([]string, errors.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() errors.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Transaction_AllTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllTables'
type Transaction_AllTables_Call struct {
	*mock.Call
}

// AllTables is a helper method to define mock.On call
func (_e *Transaction_Expecter) AllTables() *Transaction_AllTables_Call {
	return &Transaction_AllTables_Call{Call: _e.mock.On("AllTables")}
}

func (_c *Transaction_AllTables_Call) Run(run func()) *Transaction_AllTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_AllTables_Call) Return(strings []string, error errors.Error) *Transaction_AllTables_Call {
	_c.Call.Return(strings, error)
	return _c
}

func (_c *Transaction_AllTables_Call) RunAndReturn(run func() ([]string, errors.Error)) *Transaction_AllTables_Call {
	_c.Call.Return(run)
	return _c
}

// AutoMigrate provides a mock function for the type Transaction
func (_mock *Transaction) AutoMigrate(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AutoMigrate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_AutoMigrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoMigrate'
type Transaction_AutoMigrate_Call struct {
	*mock.Call
}

// AutoMigrate is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) AutoMigrate(entity any, clauses ...any) *Transaction_AutoMigrate_Call {
	return &Transaction_AutoMigrate_Call{Call: _e.mock.On("AutoMigrate",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_AutoMigrate_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_AutoMigrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_AutoMigrate_Call) Return(error errors.Error) *Transaction_AutoMigrate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_AutoMigrate_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_AutoMigrate_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type Transaction
func (_mock *Transaction) Begin() dal.Transaction {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 dal.Transaction
	if returnFunc, ok := ret.Get(0).(func() dal.Transaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Transaction)
		}
	}
	return r0
}

// Transaction_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type Transaction_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *Transaction_Expecter) Begin() *Transaction_Begin_Call {
	return &Transaction_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *Transaction_Begin_Call) Run(run func()) *Transaction_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_Begin_Call) Return(transaction dal.Transaction) *Transaction_Begin_Call {
	_c.Call.Return(transaction)
	return _c
}

func (_c *Transaction_Begin_Call) RunAndReturn(run func() dal.Transaction) *Transaction_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type Transaction
func (_mock *Transaction) Commit() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type Transaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *Transaction_Expecter) Commit() *Transaction_Commit_Call {
	return &Transaction_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *Transaction_Commit_Call) Run(run func()) *Transaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_Commit_Call) Return(error errors.Error) *Transaction_Commit_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Commit_Call) RunAndReturn(run func() errors.Error) *Transaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type Transaction
func (_mock *Transaction) Count(clauses ...dal.Clause) (int64, errors.Error) {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(clauses)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) (int64, errors.Error)); ok {
		return returnFunc(clauses...)
	}
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) int64); ok {
		r0 = returnFunc(clauses...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(...dal.Clause) errors.Error); ok {
		r1 = returnFunc(clauses...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Transaction_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Transaction_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Count(clauses ...any) *Transaction_Count_Call {
	return &Transaction_Count_Call{Call: _e.mock.On("Count",
		append([]any{}, clauses...)...)}
}

func (_c *Transaction_Count_Call) Run(run func(clauses ...dal.Clause)) *Transaction_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 0 {
			variadicArgs = args[0].([]dal.Clause)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Transaction_Count_Call) Return(n int64, error errors.Error) *Transaction_Count_Call {
	_c.Call.Return(n, error)
	return _c
}

func (_c *Transaction_Count_Call) RunAndReturn(run func(clauses ...dal.Clause) (int64, errors.Error)) *Transaction_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Transaction
func (_mock *Transaction) Create(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Transaction_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Create(entity any, clauses ...any) *Transaction_Create_Call {
	return &Transaction_Create_Call{Call: _e.mock.On("Create",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_Create_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_Create_Call) Return(error errors.Error) *Transaction_Create_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Create_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIfNotExist provides a mock function for the type Transaction
func (_mock *Transaction) CreateIfNotExist(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateIfNotExist")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_CreateIfNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIfNotExist'
type Transaction_CreateIfNotExist_Call struct {
	*mock.Call
}

// CreateIfNotExist is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) CreateIfNotExist(entity any, clauses ...any) *Transaction_CreateIfNotExist_Call {
	return &Transaction_CreateIfNotExist_Call{Call: _e.mock.On("CreateIfNotExist",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_CreateIfNotExist_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_CreateIfNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_CreateIfNotExist_Call) Return(error errors.Error) *Transaction_CreateIfNotExist_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_CreateIfNotExist_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_CreateIfNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdate provides a mock function for the type Transaction
func (_mock *Transaction) CreateOrUpdate(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type Transaction_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) CreateOrUpdate(entity any, clauses ...any) *Transaction_CreateOrUpdate_Call {
	return &Transaction_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_CreateOrUpdate_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_CreateOrUpdate_Call) Return(error errors.Error) *Transaction_CreateOrUpdate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_CreateOrUpdate_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithMap provides a mock function for the type Transaction
func (_mock *Transaction) CreateWithMap(entity interface{}, record map[string]interface{}) errors.Error {
	ret := _mock.Called(entity, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithMap")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, map[string]interface{}) errors.Error); ok {
		r0 = returnFunc(entity, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_CreateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithMap'
type Transaction_CreateWithMap_Call struct {
	*mock.Call
}

// CreateWithMap is a helper method to define mock.On call
//   - entity interface{}
//   - record map[string]interface{}
func (_e *Transaction_Expecter) CreateWithMap(entity any, record any) *Transaction_CreateWithMap_Call {
	return &Transaction_CreateWithMap_Call{Call: _e.mock.On("CreateWithMap", entity, record)}
}

func (_c *Transaction_CreateWithMap_Call) Run(run func(entity interface{}, record map[string]interface{})) *Transaction_CreateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transaction_CreateWithMap_Call) Return(error errors.Error) *Transaction_CreateWithMap_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_CreateWithMap_Call) RunAndReturn(run func(entity interface{}, record map[string]interface{}) errors.Error) *Transaction_CreateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// Cursor provides a mock function for the type Transaction
func (_mock *Transaction) Cursor(clauses ...dal.Clause) (dal.Rows, errors.Error) {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(clauses)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Cursor")
	}

	var r0 dal.Rows
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) (dal.Rows, errors.Error)); ok {
		return returnFunc(clauses...)
	}
	if returnFunc, ok := ret.Get(0).(func(...dal.Clause) dal.Rows); ok {
		r0 = returnFunc(clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...dal.Clause) errors.Error); ok {
		r1 = returnFunc(clauses...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Transaction_Cursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cursor'
type Transaction_Cursor_Call struct {
	*mock.Call
}

// Cursor is a helper method to define mock.On call
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Cursor(clauses ...any) *Transaction_Cursor_Call {
	return &Transaction_Cursor_Call{Call: _e.mock.On("Cursor",
		append([]any{}, clauses...)...)}
}

func (_c *Transaction_Cursor_Call) Run(run func(clauses ...dal.Clause)) *Transaction_Cursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 0 {
			variadicArgs = args[0].([]dal.Clause)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Transaction_Cursor_Call) Return(rows dal.Rows, error errors.Error) *Transaction_Cursor_Call {
	_c.Call.Return(rows, error)
	return _c
}

func (_c *Transaction_Cursor_Call) RunAndReturn(run func(clauses ...dal.Clause) (dal.Rows, errors.Error)) *Transaction_Cursor_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Transaction
func (_mock *Transaction) Delete(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Transaction_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Delete(entity any, clauses ...any) *Transaction_Delete_Call {
	return &Transaction_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_Delete_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_Delete_Call) Return(error errors.Error) *Transaction_Delete_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Delete_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Dialect provides a mock function for the type Transaction
func (_mock *Transaction) Dialect() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dialect")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Transaction_Dialect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dialect'
type Transaction_Dialect_Call struct {
	*mock.Call
}

// Dialect is a helper method to define mock.On call
func (_e *Transaction_Expecter) Dialect() *Transaction_Dialect_Call {
	return &Transaction_Dialect_Call{Call: _e.mock.On("Dialect")}
}

func (_c *Transaction_Dialect_Call) Run(run func()) *Transaction_Dialect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_Dialect_Call) Return(s string) *Transaction_Dialect_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Transaction_Dialect_Call) RunAndReturn(run func() string) *Transaction_Dialect_Call {
	_c.Call.Return(run)
	return _c
}

// DropColumns provides a mock function for the type Transaction
func (_mock *Transaction) DropColumns(table string, columnName ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(columnName) > 0 {
		tmpRet = _mock.Called(table, columnName)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropColumns")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, columnName...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_DropColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropColumns'
type Transaction_DropColumns_Call struct {
	*mock.Call
}

// DropColumns is a helper method to define mock.On call
//   - table string
//   - columnName ...string
func (_e *Transaction_Expecter) DropColumns(table any, columnName ...any) *Transaction_DropColumns_Call {
	return &Transaction_DropColumns_Call{Call: _e.mock.On("DropColumns",
		append([]any{table}, columnName...)...)}
}

func (_c *Transaction_DropColumns_Call) Run(run func(table string, columnName ...string)) *Transaction_DropColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_DropColumns_Call) Return(error errors.Error) *Transaction_DropColumns_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_DropColumns_Call) RunAndReturn(run func(table string, columnName ...string) errors.Error) *Transaction_DropColumns_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndex provides a mock function for the type Transaction
func (_mock *Transaction) DropIndex(table string, columnNames ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(columnNames) > 0 {
		tmpRet = _mock.Called(table, columnNames)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropIndex")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, columnNames...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_DropIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndex'
type Transaction_DropIndex_Call struct {
	*mock.Call
}

// DropIndex is a helper method to define mock.On call
//   - table string
//   - columnNames ...string
func (_e *Transaction_Expecter) DropIndex(table any, columnNames ...any) *Transaction_DropIndex_Call {
	return &Transaction_DropIndex_Call{Call: _e.mock.On("DropIndex",
		append([]any{table}, columnNames...)...)}
}

func (_c *Transaction_DropIndex_Call) Run(run func(table string, columnNames ...string)) *Transaction_DropIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_DropIndex_Call) Return(error errors.Error) *Transaction_DropIndex_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_DropIndex_Call) RunAndReturn(run func(table string, columnNames ...string) errors.Error) *Transaction_DropIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DropIndexes provides a mock function for the type Transaction
func (_mock *Transaction) DropIndexes(table string, indexes ...string) errors.Error {
	var tmpRet mock.Arguments
	if len(indexes) > 0 {
		tmpRet = _mock.Called(table, indexes)
	} else {
		tmpRet = _mock.Called(table)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropIndexes")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) errors.Error); ok {
		r0 = returnFunc(table, indexes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_DropIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropIndexes'
type Transaction_DropIndexes_Call struct {
	*mock.Call
}

// DropIndexes is a helper method to define mock.On call
//   - table string
//   - indexes ...string
func (_e *Transaction_Expecter) DropIndexes(table any, indexes ...any) *Transaction_DropIndexes_Call {
	return &Transaction_DropIndexes_Call{Call: _e.mock.On("DropIndexes",
		append([]any{table}, indexes...)...)}
}

func (_c *Transaction_DropIndexes_Call) Run(run func(table string, indexes ...string)) *Transaction_DropIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_DropIndexes_Call) Return(error errors.Error) *Transaction_DropIndexes_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_DropIndexes_Call) RunAndReturn(run func(table string, indexes ...string) errors.Error) *Transaction_DropIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// DropTables provides a mock function for the type Transaction
func (_mock *Transaction) DropTables(dst ...interface{}) errors.Error {
	var tmpRet mock.Arguments
	if len(dst) > 0 {
		tmpRet = _mock.Called(dst)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DropTables")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(...interface{}) errors.Error); ok {
		r0 = returnFunc(dst...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_DropTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropTables'
type Transaction_DropTables_Call struct {
	*mock.Call
}

// DropTables is a helper method to define mock.On call
//   - dst ...interface{}
func (_e *Transaction_Expecter) DropTables(dst ...any) *Transaction_DropTables_Call {
	return &Transaction_DropTables_Call{Call: _e.mock.On("DropTables",
		append([]any{}, dst...)...)}
}

func (_c *Transaction_DropTables_Call) Run(run func(dst ...interface{})) *Transaction_DropTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []interface{}
		var variadicArgs []interface{}
		if len(args) > 0 {
			variadicArgs = args[0].([]interface{})
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Transaction_DropTables_Call) Return(error errors.Error) *Transaction_DropTables_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_DropTables_Call) RunAndReturn(run func(dst ...interface{}) errors.Error) *Transaction_DropTables_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type Transaction
func (_mock *Transaction) Exec(query string, params ...interface{}) errors.Error {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(query, params)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) errors.Error); ok {
		r0 = returnFunc(query, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Transaction_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - params ...interface{}
func (_e *Transaction_Expecter) Exec(query any, params ...any) *Transaction_Exec_Call {
	return &Transaction_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{query}, params...)...)}
}

func (_c *Transaction_Exec_Call) Run(run func(query string, params ...interface{})) *Transaction_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_Exec_Call) Return(error errors.Error) *Transaction_Exec_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Exec_Call) RunAndReturn(run func(query string, params ...interface{}) errors.Error) *Transaction_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type Transaction
func (_mock *Transaction) Fetch(cursor dal.Rows, dst interface{}) errors.Error {
	ret := _mock.Called(cursor, dst)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(dal.Rows, interface{}) errors.Error); ok {
		r0 = returnFunc(cursor, dst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Transaction_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - cursor dal.Rows
//   - dst interface{}
func (_e *Transaction_Expecter) Fetch(cursor any, dst any) *Transaction_Fetch_Call {
	return &Transaction_Fetch_Call{Call: _e.mock.On("Fetch", cursor, dst)}
}

func (_c *Transaction_Fetch_Call) Run(run func(cursor dal.Rows, dst interface{})) *Transaction_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.Rows
		if args[0] != nil {
			arg0 = args[0].(dal.Rows)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transaction_Fetch_Call) Return(error errors.Error) *Transaction_Fetch_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Fetch_Call) RunAndReturn(run func(cursor dal.Rows, dst interface{}) errors.Error) *Transaction_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// First provides a mock function for the type Transaction
func (_mock *Transaction) First(dst interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(dst, clauses)
	} else {
		tmpRet = _mock.Called(dst)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(dst, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_First_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'First'
type Transaction_First_Call struct {
	*mock.Call
}

// First is a helper method to define mock.On call
//   - dst interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) First(dst any, clauses ...any) *Transaction_First_Call {
	return &Transaction_First_Call{Call: _e.mock.On("First",
		append([]any{dst}, clauses...)...)}
}

func (_c *Transaction_First_Call) Run(run func(dst interface{}, clauses ...dal.Clause)) *Transaction_First_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_First_Call) Return(error errors.Error) *Transaction_First_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_First_Call) RunAndReturn(run func(dst interface{}, clauses ...dal.Clause) errors.Error) *Transaction_First_Call {
	_c.Call.Return(run)
	return _c
}

// GetColumns provides a mock function for the type Transaction
func (_mock *Transaction) GetColumns(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error) {
	ret := _mock.Called(dst, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetColumns")
	}

	var r0 []dal.ColumnMeta
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error)); ok {
		return returnFunc(dst, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) []dal.ColumnMeta); ok {
		r0 = returnFunc(dst, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dal.ColumnMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dal.Tabler, func(columnMeta dal.ColumnMeta) bool) errors.Error); ok {
		r1 = returnFunc(dst, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Transaction_GetColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColumns'
type Transaction_GetColumns_Call struct {
	*mock.Call
}

// GetColumns is a helper method to define mock.On call
//   - dst dal.Tabler
//   - filter func(columnMeta dal.ColumnMeta) bool
func (_e *Transaction_Expecter) GetColumns(dst any, filter any) *Transaction_GetColumns_Call {
	return &Transaction_GetColumns_Call{Call: _e.mock.On("GetColumns", dst, filter)}
}

func (_c *Transaction_GetColumns_Call) Run(run func(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool)) *Transaction_GetColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.Tabler
		if args[0] != nil {
			arg0 = args[0].(dal.Tabler)
		}
		var arg1 func(columnMeta dal.ColumnMeta) bool
		if args[1] != nil {
			arg1 = args[1].(func(columnMeta dal.ColumnMeta) bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transaction_GetColumns_Call) Return(cms []dal.ColumnMeta, err errors.Error) *Transaction_GetColumns_Call {
	_c.Call.Return(cms, err)
	return _c
}

func (_c *Transaction_GetColumns_Call) RunAndReturn(run func(dst dal.Tabler, filter func(columnMeta dal.ColumnMeta) bool) ([]dal.ColumnMeta, errors.Error)) *Transaction_GetColumns_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrimaryKeyFields provides a mock function for the type Transaction
func (_mock *Transaction) GetPrimaryKeyFields(t reflect.Type) []reflect.StructField {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimaryKeyFields")
	}

	var r0 []reflect.StructField
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []reflect.StructField); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reflect.StructField)
		}
	}
	return r0
}

// Transaction_GetPrimaryKeyFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrimaryKeyFields'
type Transaction_GetPrimaryKeyFields_Call struct {
	*mock.Call
}

// GetPrimaryKeyFields is a helper method to define mock.On call
//   - t reflect.Type
func (_e *Transaction_Expecter) GetPrimaryKeyFields(t any) *Transaction_GetPrimaryKeyFields_Call {
	return &Transaction_GetPrimaryKeyFields_Call{Call: _e.mock.On("GetPrimaryKeyFields", t)}
}

func (_c *Transaction_GetPrimaryKeyFields_Call) Run(run func(t reflect.Type)) *Transaction_GetPrimaryKeyFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_GetPrimaryKeyFields_Call) Return(structFields []reflect.StructField) *Transaction_GetPrimaryKeyFields_Call {
	_c.Call.Return(structFields)
	return _c
}

func (_c *Transaction_GetPrimaryKeyFields_Call) RunAndReturn(run func(t reflect.Type) []reflect.StructField) *Transaction_GetPrimaryKeyFields_Call {
	_c.Call.Return(run)
	return _c
}

// HasColumn provides a mock function for the type Transaction
func (_mock *Transaction) HasColumn(table interface{}, columnName string) bool {
	ret := _mock.Called(table, columnName)

	if len(ret) == 0 {
		panic("no return value specified for HasColumn")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(interface{}, string) bool); ok {
		r0 = returnFunc(table, columnName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Transaction_HasColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasColumn'
type Transaction_HasColumn_Call struct {
	*mock.Call
}

// HasColumn is a helper method to define mock.On call
//   - table interface{}
//   - columnName string
func (_e *Transaction_Expecter) HasColumn(table any, columnName any) *Transaction_HasColumn_Call {
	return &Transaction_HasColumn_Call{Call: _e.mock.On("HasColumn", table, columnName)}
}

func (_c *Transaction_HasColumn_Call) Run(run func(table interface{}, columnName string)) *Transaction_HasColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transaction_HasColumn_Call) Return(b bool) *Transaction_HasColumn_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Transaction_HasColumn_Call) RunAndReturn(run func(table interface{}, columnName string) bool) *Transaction_HasColumn_Call {
	_c.Call.Return(run)
	return _c
}

// HasTable provides a mock function for the type Transaction
func (_mock *Transaction) HasTable(table interface{}) bool {
	ret := _mock.Called(table)

	if len(ret) == 0 {
		panic("no return value specified for HasTable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = returnFunc(table)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Transaction_HasTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasTable'
type Transaction_HasTable_Call struct {
	*mock.Call
}

// HasTable is a helper method to define mock.On call
//   - table interface{}
func (_e *Transaction_Expecter) HasTable(table any) *Transaction_HasTable_Call {
	return &Transaction_HasTable_Call{Call: _e.mock.On("HasTable", table)}
}

func (_c *Transaction_HasTable_Call) Run(run func(table interface{})) *Transaction_HasTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_HasTable_Call) Return(b bool) *Transaction_HasTable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Transaction_HasTable_Call) RunAndReturn(run func(table interface{}) bool) *Transaction_HasTable_Call {
	_c.Call.Return(run)
	return _c
}

// IsDuplicationError provides a mock function for the type Transaction
func (_mock *Transaction) IsDuplicationError(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicationError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Transaction_IsDuplicationError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicationError'
type Transaction_IsDuplicationError_Call struct {
	*mock.Call
}

// IsDuplicationError is a helper method to define mock.On call
//   - err error
func (_e *Transaction_Expecter) IsDuplicationError(err any) *Transaction_IsDuplicationError_Call {
	return &Transaction_IsDuplicationError_Call{Call: _e.mock.On("IsDuplicationError", err)}
}

func (_c *Transaction_IsDuplicationError_Call) Run(run func(err error)) *Transaction_IsDuplicationError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_IsDuplicationError_Call) Return(b bool) *Transaction_IsDuplicationError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Transaction_IsDuplicationError_Call) RunAndReturn(run func(err error) bool) *Transaction_IsDuplicationError_Call {
	_c.Call.Return(run)
	return _c
}

// IsErrorNotFound provides a mock function for the type Transaction
func (_mock *Transaction) IsErrorNotFound(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsErrorNotFound")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Transaction_IsErrorNotFound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsErrorNotFound'
type Transaction_IsErrorNotFound_Call struct {
	*mock.Call
}

// IsErrorNotFound is a helper method to define mock.On call
//   - err error
func (_e *Transaction_Expecter) IsErrorNotFound(err any) *Transaction_IsErrorNotFound_Call {
	return &Transaction_IsErrorNotFound_Call{Call: _e.mock.On("IsErrorNotFound", err)}
}

func (_c *Transaction_IsErrorNotFound_Call) Run(run func(err error)) *Transaction_IsErrorNotFound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_IsErrorNotFound_Call) Return(b bool) *Transaction_IsErrorNotFound_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Transaction_IsErrorNotFound_Call) RunAndReturn(run func(err error) bool) *Transaction_IsErrorNotFound_Call {
	_c.Call.Return(run)
	return _c
}

// LockTables provides a mock function for the type Transaction
func (_mock *Transaction) LockTables(lockTables dal.LockTables) errors.Error {
	ret := _mock.Called(lockTables)

	if len(ret) == 0 {
		panic("no return value specified for LockTables")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(dal.LockTables) errors.Error); ok {
		r0 = returnFunc(lockTables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_LockTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockTables'
type Transaction_LockTables_Call struct {
	*mock.Call
}

// LockTables is a helper method to define mock.On call
//   - lockTables dal.LockTables
func (_e *Transaction_Expecter) LockTables(lockTables any) *Transaction_LockTables_Call {
	return &Transaction_LockTables_Call{Call: _e.mock.On("LockTables", lockTables)}
}

func (_c *Transaction_LockTables_Call) Run(run func(lockTables dal.LockTables)) *Transaction_LockTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.LockTables
		if args[0] != nil {
			arg0 = args[0].(dal.LockTables)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_LockTables_Call) Return(error errors.Error) *Transaction_LockTables_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_LockTables_Call) RunAndReturn(run func(lockTables dal.LockTables) errors.Error) *Transaction_LockTables_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyColumnType provides a mock function for the type Transaction
func (_mock *Transaction) ModifyColumnType(table string, columnName string, columnType string) errors.Error {
	ret := _mock.Called(table, columnName, columnType)

	if len(ret) == 0 {
		panic("no return value specified for ModifyColumnType")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) errors.Error); ok {
		r0 = returnFunc(table, columnName, columnType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_ModifyColumnType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyColumnType'
type Transaction_ModifyColumnType_Call struct {
	*mock.Call
}

// ModifyColumnType is a helper method to define mock.On call
//   - table string
//   - columnName string
//   - columnType string
func (_e *Transaction_Expecter) ModifyColumnType(table any, columnName any, columnType any) *Transaction_ModifyColumnType_Call {
	return &Transaction_ModifyColumnType_Call{Call: _e.mock.On("ModifyColumnType", table, columnName, columnType)}
}

func (_c *Transaction_ModifyColumnType_Call) Run(run func(table string, columnName string, columnType string)) *Transaction_ModifyColumnType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Transaction_ModifyColumnType_Call) Return(error errors.Error) *Transaction_ModifyColumnType_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_ModifyColumnType_Call) RunAndReturn(run func(table string, columnName string, columnType string) errors.Error) *Transaction_ModifyColumnType_Call {
	_c.Call.Return(run)
	return _c
}

// Pluck provides a mock function for the type Transaction
func (_mock *Transaction) Pluck(column string, dest interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(column, dest, clauses)
	} else {
		tmpRet = _mock.Called(column, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Pluck")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(column, dest, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Pluck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pluck'
type Transaction_Pluck_Call struct {
	*mock.Call
}

// Pluck is a helper method to define mock.On call
//   - column string
//   - dest interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Pluck(column any, dest any, clauses ...any) *Transaction_Pluck_Call {
	return &Transaction_Pluck_Call{Call: _e.mock.On("Pluck",
		append([]any{column, dest}, clauses...)...)}
}

func (_c *Transaction_Pluck_Call) Run(run func(column string, dest interface{}, clauses ...dal.Clause)) *Transaction_Pluck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 2 {
			variadicArgs = args[2].([]dal.Clause)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Transaction_Pluck_Call) Return(error errors.Error) *Transaction_Pluck_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Pluck_Call) RunAndReturn(run func(column string, dest interface{}, clauses ...dal.Clause) errors.Error) *Transaction_Pluck_Call {
	_c.Call.Return(run)
	return _c
}

// RawCursor provides a mock function for the type Transaction
func (_mock *Transaction) RawCursor(query string, params ...interface{}) (*sql.Rows, errors.Error) {
	var tmpRet mock.Arguments
	if len(params) > 0 {
		tmpRet = _mock.Called(query, params)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RawCursor")
	}

	var r0 *sql.Rows
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, errors.Error)); ok {
		return returnFunc(query, params...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = returnFunc(query, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...interface{}) errors.Error); ok {
		r1 = returnFunc(query, params...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Transaction_RawCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawCursor'
type Transaction_RawCursor_Call struct {
	*mock.Call
}

// RawCursor is a helper method to define mock.On call
//   - query string
//   - params ...interface{}
func (_e *Transaction_Expecter) RawCursor(query any, params ...any) *Transaction_RawCursor_Call {
	return &Transaction_RawCursor_Call{Call: _e.mock.On("RawCursor",
		append([]any{query}, params...)...)}
}

func (_c *Transaction_RawCursor_Call) Run(run func(query string, params ...interface{})) *Transaction_RawCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_RawCursor_Call) Return(rows *sql.Rows, error errors.Error) *Transaction_RawCursor_Call {
	_c.Call.Return(rows, error)
	return _c
}

func (_c *Transaction_RawCursor_Call) RunAndReturn(run func(query string, params ...interface{}) (*sql.Rows, errors.Error)) *Transaction_RawCursor_Call {
	_c.Call.Return(run)
	return _c
}

// RenameColumn provides a mock function for the type Transaction
func (_mock *Transaction) RenameColumn(table string, oldColumnName string, newColumnName string) errors.Error {
	ret := _mock.Called(table, oldColumnName, newColumnName)

	if len(ret) == 0 {
		panic("no return value specified for RenameColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) errors.Error); ok {
		r0 = returnFunc(table, oldColumnName, newColumnName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_RenameColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameColumn'
type Transaction_RenameColumn_Call struct {
	*mock.Call
}

// RenameColumn is a helper method to define mock.On call
//   - table string
//   - oldColumnName string
//   - newColumnName string
func (_e *Transaction_Expecter) RenameColumn(table any, oldColumnName any, newColumnName any) *Transaction_RenameColumn_Call {
	return &Transaction_RenameColumn_Call{Call: _e.mock.On("RenameColumn", table, oldColumnName, newColumnName)}
}

func (_c *Transaction_RenameColumn_Call) Run(run func(table string, oldColumnName string, newColumnName string)) *Transaction_RenameColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Transaction_RenameColumn_Call) Return(error errors.Error) *Transaction_RenameColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_RenameColumn_Call) RunAndReturn(run func(table string, oldColumnName string, newColumnName string) errors.Error) *Transaction_RenameColumn_Call {
	_c.Call.Return(run)
	return _c
}

// RenameTable provides a mock function for the type Transaction
func (_mock *Transaction) RenameTable(oldName string, newName string) errors.Error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for RenameTable")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, string) errors.Error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_RenameTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameTable'
type Transaction_RenameTable_Call struct {
	*mock.Call
}

// RenameTable is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *Transaction_Expecter) RenameTable(oldName any, newName any) *Transaction_RenameTable_Call {
	return &Transaction_RenameTable_Call{Call: _e.mock.On("RenameTable", oldName, newName)}
}

func (_c *Transaction_RenameTable_Call) Run(run func(oldName string, newName string)) *Transaction_RenameTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transaction_RenameTable_Call) Return(error errors.Error) *Transaction_RenameTable_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_RenameTable_Call) RunAndReturn(run func(oldName string, newName string) errors.Error) *Transaction_RenameTable_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type Transaction
func (_mock *Transaction) Rollback() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type Transaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *Transaction_Expecter) Rollback() *Transaction_Rollback_Call {
	return &Transaction_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *Transaction_Rollback_Call) Run(run func()) *Transaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_Rollback_Call) Return(error errors.Error) *Transaction_Rollback_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Rollback_Call) RunAndReturn(run func() errors.Error) *Transaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Session provides a mock function for the type Transaction
func (_mock *Transaction) Session(config dal.SessionConfig) dal.Dal {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 dal.Dal
	if returnFunc, ok := ret.Get(0).(func(dal.SessionConfig) dal.Dal); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Dal)
		}
	}
	return r0
}

// Transaction_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type Transaction_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
//   - config dal.SessionConfig
func (_e *Transaction_Expecter) Session(config any) *Transaction_Session_Call {
	return &Transaction_Session_Call{Call: _e.mock.On("Session", config)}
}

func (_c *Transaction_Session_Call) Run(run func(config dal.SessionConfig)) *Transaction_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dal.SessionConfig
		if args[0] != nil {
			arg0 = args[0].(dal.SessionConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Transaction_Session_Call) Return(dal1 dal.Dal) *Transaction_Session_Call {
	_c.Call.Return(dal1)
	return _c
}

func (_c *Transaction_Session_Call) RunAndReturn(run func(config dal.SessionConfig) dal.Dal) *Transaction_Session_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockTables provides a mock function for the type Transaction
func (_mock *Transaction) UnlockTables() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnlockTables")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_UnlockTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockTables'
type Transaction_UnlockTables_Call struct {
	*mock.Call
}

// UnlockTables is a helper method to define mock.On call
func (_e *Transaction_Expecter) UnlockTables() *Transaction_UnlockTables_Call {
	return &Transaction_UnlockTables_Call{Call: _e.mock.On("UnlockTables")}
}

func (_c *Transaction_UnlockTables_Call) Run(run func()) *Transaction_UnlockTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transaction_UnlockTables_Call) Return(error errors.Error) *Transaction_UnlockTables_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_UnlockTables_Call) RunAndReturn(run func() errors.Error) *Transaction_UnlockTables_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Transaction
func (_mock *Transaction) Update(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Transaction_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) Update(entity any, clauses ...any) *Transaction_Update_Call {
	return &Transaction_Update_Call{Call: _e.mock.On("Update",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_Update_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_Update_Call) Return(error errors.Error) *Transaction_Update_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_Update_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllColumn provides a mock function for the type Transaction
func (_mock *Transaction) UpdateAllColumn(entity interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entity, clauses)
	} else {
		tmpRet = _mock.Called(entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entity, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_UpdateAllColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllColumn'
type Transaction_UpdateAllColumn_Call struct {
	*mock.Call
}

// UpdateAllColumn is a helper method to define mock.On call
//   - entity interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) UpdateAllColumn(entity any, clauses ...any) *Transaction_UpdateAllColumn_Call {
	return &Transaction_UpdateAllColumn_Call{Call: _e.mock.On("UpdateAllColumn",
		append([]any{entity}, clauses...)...)}
}

func (_c *Transaction_UpdateAllColumn_Call) Run(run func(entity interface{}, clauses ...dal.Clause)) *Transaction_UpdateAllColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 1 {
			variadicArgs = args[1].([]dal.Clause)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Transaction_UpdateAllColumn_Call) Return(error errors.Error) *Transaction_UpdateAllColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_UpdateAllColumn_Call) RunAndReturn(run func(entity interface{}, clauses ...dal.Clause) errors.Error) *Transaction_UpdateAllColumn_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateColumn provides a mock function for the type Transaction
func (_mock *Transaction) UpdateColumn(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entityOrTable, columnName, value, clauses)
	} else {
		tmpRet = _mock.Called(entityOrTable, columnName, value)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumn")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, interface{}, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entityOrTable, columnName, value, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_UpdateColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateColumn'
type Transaction_UpdateColumn_Call struct {
	*mock.Call
}

// UpdateColumn is a helper method to define mock.On call
//   - entityOrTable interface{}
//   - columnName string
//   - value interface{}
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) UpdateColumn(entityOrTable any, columnName any, value any, clauses ...any) *Transaction_UpdateColumn_Call {
	return &Transaction_UpdateColumn_Call{Call: _e.mock.On("UpdateColumn",
		append([]any{entityOrTable, columnName, value}, clauses...)...)}
}

func (_c *Transaction_UpdateColumn_Call) Run(run func(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause)) *Transaction_UpdateColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 3 {
			variadicArgs = args[3].([]dal.Clause)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Transaction_UpdateColumn_Call) Return(error errors.Error) *Transaction_UpdateColumn_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_UpdateColumn_Call) RunAndReturn(run func(entityOrTable interface{}, columnName string, value interface{}, clauses ...dal.Clause) errors.Error) *Transaction_UpdateColumn_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateColumns provides a mock function for the type Transaction
func (_mock *Transaction) UpdateColumns(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause) errors.Error {
	var tmpRet mock.Arguments
	if len(clauses) > 0 {
		tmpRet = _mock.Called(entityOrTable, set, clauses)
	} else {
		tmpRet = _mock.Called(entityOrTable, set)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumns")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, []dal.DalSet, ...dal.Clause) errors.Error); ok {
		r0 = returnFunc(entityOrTable, set, clauses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Transaction_UpdateColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateColumns'
type Transaction_UpdateColumns_Call struct {
	*mock.Call
}

// UpdateColumns is a helper method to define mock.On call
//   - entityOrTable interface{}
//   - set []dal.DalSet
//   - clauses ...dal.Clause
func (_e *Transaction_Expecter) UpdateColumns(entityOrTable any, set any, clauses ...any) *Transaction_UpdateColumns_Call {
	return &Transaction_UpdateColumns_Call{Call: _e.mock.On("UpdateColumns",
		append([]any{entityOrTable, set}, clauses...)...)}
}

func (_c *Transaction_UpdateColumns_Call) Run(run func(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause)) *Transaction_UpdateColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 []dal.DalSet
		if args[1] != nil {
			arg1 = args[1].([]dal.DalSet)
		}
		var arg2 []dal.Clause
		var variadicArgs []dal.Clause
		if len(args) > 2 {
			variadicArgs = args[2].([]dal.Clause)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Transaction_UpdateColumns_Call) Return(error errors.Error) *Transaction_UpdateColumns_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Transaction_UpdateColumns_Call) RunAndReturn(run func(entityOrTable interface{}, set []dal.DalSet, clauses ...dal.Clause) errors.Error) *Transaction_UpdateColumns_Call {
	_c.Call.Return(run)
	return _c
}
