// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewConfigReader creates a new instance of ConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigReader {
	mock := &ConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigReader is an autogenerated mock type for the ConfigReader type
type ConfigReader struct {
	mock.Mock
}

type ConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigReader) EXPECT() *ConfigReader_Expecter {
	return &ConfigReader_Expecter{mock: &_m.Mock}
}

// AllSettings provides a mock function for the type ConfigReader
func (_mock *ConfigReader) AllSettings() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllSettings")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// ConfigReader_AllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllSettings'
type ConfigReader_AllSettings_Call struct {
	*mock.Call
}

// AllSettings is a helper method to define mock.On call
func (_e *ConfigReader_Expecter) AllSettings() *ConfigReader_AllSettings_Call {
	return &ConfigReader_AllSettings_Call{Call: _e.mock.On("AllSettings")}
}

func (_c *ConfigReader_AllSettings_Call) Run(run func()) *ConfigReader_AllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigReader_AllSettings_Call) Return(stringToIfaceVal map[string]interface{}) *ConfigReader_AllSettings_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *ConfigReader_AllSettings_Call) RunAndReturn(run func() map[string]interface{}) *ConfigReader_AllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ConfigReader
func (_mock *ConfigReader) Get(key string) interface{} {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// ConfigReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ConfigReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) Get(key any) *ConfigReader_Get_Call {
	return &ConfigReader_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *ConfigReader_Get_Call) Run(run func(key string)) *ConfigReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_Get_Call) Return(ifaceVal interface{}) *ConfigReader_Get_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *ConfigReader_Get_Call) RunAndReturn(run func(key string) interface{}) *ConfigReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBool provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetBool(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetBool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConfigReader_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type ConfigReader_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - name string
func (_e *ConfigReader_Expecter) GetBool(name any) *ConfigReader_GetBool_Call {
	return &ConfigReader_GetBool_Call{Call: _e.mock.On("GetBool", name)}
}

func (_c *ConfigReader_GetBool_Call) Run(run func(name string)) *ConfigReader_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetBool_Call) Return(b bool) *ConfigReader_GetBool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConfigReader_GetBool_Call) RunAndReturn(run func(name string) bool) *ConfigReader_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuration provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetDuration(key string) time.Duration {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// ConfigReader_GetDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuration'
type ConfigReader_GetDuration_Call struct {
	*mock.Call
}

// GetDuration is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetDuration(key any) *ConfigReader_GetDuration_Call {
	return &ConfigReader_GetDuration_Call{Call: _e.mock.On("GetDuration", key)}
}

func (_c *ConfigReader_GetDuration_Call) Run(run func(key string)) *ConfigReader_GetDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetDuration_Call) Return(duration time.Duration) *ConfigReader_GetDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *ConfigReader_GetDuration_Call) RunAndReturn(run func(key string) time.Duration) *ConfigReader_GetDuration_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloat64 provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetFloat64(key string) float64 {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat64")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// ConfigReader_GetFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat64'
type ConfigReader_GetFloat64_Call struct {
	*mock.Call
}

// GetFloat64 is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetFloat64(key any) *ConfigReader_GetFloat64_Call {
	return &ConfigReader_GetFloat64_Call{Call: _e.mock.On("GetFloat64", key)}
}

func (_c *ConfigReader_GetFloat64_Call) Run(run func(key string)) *ConfigReader_GetFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetFloat64_Call) Return(f float64) *ConfigReader_GetFloat64_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *ConfigReader_GetFloat64_Call) RunAndReturn(run func(key string) float64) *ConfigReader_GetFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetInt(key string) int {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// ConfigReader_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type ConfigReader_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetInt(key any) *ConfigReader_GetInt_Call {
	return &ConfigReader_GetInt_Call{Call: _e.mock.On("GetInt", key)}
}

func (_c *ConfigReader_GetInt_Call) Run(run func(key string)) *ConfigReader_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetInt_Call) Return(n int) *ConfigReader_GetInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *ConfigReader_GetInt_Call) RunAndReturn(run func(key string) int) *ConfigReader_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt64 provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetInt64(key string) int64 {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetInt64")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// ConfigReader_GetInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt64'
type ConfigReader_GetInt64_Call struct {
	*mock.Call
}

// GetInt64 is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetInt64(key any) *ConfigReader_GetInt64_Call {
	return &ConfigReader_GetInt64_Call{Call: _e.mock.On("GetInt64", key)}
}

func (_c *ConfigReader_GetInt64_Call) Run(run func(key string)) *ConfigReader_GetInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetInt64_Call) Return(n int64) *ConfigReader_GetInt64_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *ConfigReader_GetInt64_Call) RunAndReturn(run func(key string) int64) *ConfigReader_GetInt64_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntSlice provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetIntSlice(key string) []int {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetIntSlice")
	}

	var r0 []int
	if returnFunc, ok := ret.Get(0).(func(string) []int); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	return r0
}

// ConfigReader_GetIntSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntSlice'
type ConfigReader_GetIntSlice_Call struct {
	*mock.Call
}

// GetIntSlice is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetIntSlice(key any) *ConfigReader_GetIntSlice_Call {
	return &ConfigReader_GetIntSlice_Call{Call: _e.mock.On("GetIntSlice", key)}
}

func (_c *ConfigReader_GetIntSlice_Call) Run(run func(key string)) *ConfigReader_GetIntSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetIntSlice_Call) Return(ints []int) *ConfigReader_GetIntSlice_Call {
	_c.Call.Return(ints)
	return _c
}

func (_c *ConfigReader_GetIntSlice_Call) RunAndReturn(run func(key string) []int) *ConfigReader_GetIntSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetString(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigReader_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type ConfigReader_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetString(key any) *ConfigReader_GetString_Call {
	return &ConfigReader_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *ConfigReader_GetString_Call) Run(run func(key string)) *ConfigReader_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetString_Call) Return(s string) *ConfigReader_GetString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigReader_GetString_Call) RunAndReturn(run func(key string) string) *ConfigReader_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMap provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetStringMap(key string) map[string]interface{} {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMap")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// ConfigReader_GetStringMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMap'
type ConfigReader_GetStringMap_Call struct {
	*mock.Call
}

// GetStringMap is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetStringMap(key any) *ConfigReader_GetStringMap_Call {
	return &ConfigReader_GetStringMap_Call{Call: _e.mock.On("GetStringMap", key)}
}

func (_c *ConfigReader_GetStringMap_Call) Run(run func(key string)) *ConfigReader_GetStringMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetStringMap_Call) Return(stringToIfaceVal map[string]interface{}) *ConfigReader_GetStringMap_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *ConfigReader_GetStringMap_Call) RunAndReturn(run func(key string) map[string]interface{}) *ConfigReader_GetStringMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringMapString provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetStringMapString(key string) map[string]string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringMapString")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// ConfigReader_GetStringMapString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringMapString'
type ConfigReader_GetStringMapString_Call struct {
	*mock.Call
}

// GetStringMapString is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetStringMapString(key any) *ConfigReader_GetStringMapString_Call {
	return &ConfigReader_GetStringMapString_Call{Call: _e.mock.On("GetStringMapString", key)}
}

func (_c *ConfigReader_GetStringMapString_Call) Run(run func(key string)) *ConfigReader_GetStringMapString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetStringMapString_Call) Return(stringToString map[string]string) *ConfigReader_GetStringMapString_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *ConfigReader_GetStringMapString_Call) RunAndReturn(run func(key string) map[string]string) *ConfigReader_GetStringMapString_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringSlice provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetStringSlice(key string) []string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStringSlice")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// ConfigReader_GetStringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringSlice'
type ConfigReader_GetStringSlice_Call struct {
	*mock.Call
}

// GetStringSlice is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetStringSlice(key any) *ConfigReader_GetStringSlice_Call {
	return &ConfigReader_GetStringSlice_Call{Call: _e.mock.On("GetStringSlice", key)}
}

func (_c *ConfigReader_GetStringSlice_Call) Run(run func(key string)) *ConfigReader_GetStringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetStringSlice_Call) Return(strings []string) *ConfigReader_GetStringSlice_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *ConfigReader_GetStringSlice_Call) RunAndReturn(run func(key string) []string) *ConfigReader_GetStringSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetTime provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetTime(key string) time.Time {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// ConfigReader_GetTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTime'
type ConfigReader_GetTime_Call struct {
	*mock.Call
}

// GetTime is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetTime(key any) *ConfigReader_GetTime_Call {
	return &ConfigReader_GetTime_Call{Call: _e.mock.On("GetTime", key)}
}

func (_c *ConfigReader_GetTime_Call) Run(run func(key string)) *ConfigReader_GetTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetTime_Call) Return(time1 time.Time) *ConfigReader_GetTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *ConfigReader_GetTime_Call) RunAndReturn(run func(key string) time.Time) *ConfigReader_GetTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetUint(key string) uint {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func(string) uint); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// ConfigReader_GetUint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint'
type ConfigReader_GetUint_Call struct {
	*mock.Call
}

// GetUint is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetUint(key any) *ConfigReader_GetUint_Call {
	return &ConfigReader_GetUint_Call{Call: _e.mock.On("GetUint", key)}
}

func (_c *ConfigReader_GetUint_Call) Run(run func(key string)) *ConfigReader_GetUint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetUint_Call) Return(v uint) *ConfigReader_GetUint_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ConfigReader_GetUint_Call) RunAndReturn(run func(key string) uint) *ConfigReader_GetUint_Call {
	_c.Call.Return(run)
	return _c
}

// GetUint64 provides a mock function for the type ConfigReader
func (_mock *ConfigReader) GetUint64(key string) uint64 {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUint64")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// ConfigReader_GetUint64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUint64'
type ConfigReader_GetUint64_Call struct {
	*mock.Call
}

// GetUint64 is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) GetUint64(key any) *ConfigReader_GetUint64_Call {
	return &ConfigReader_GetUint64_Call{Call: _e.mock.On("GetUint64", key)}
}

func (_c *ConfigReader_GetUint64_Call) Run(run func(key string)) *ConfigReader_GetUint64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_GetUint64_Call) Return(v uint64) *ConfigReader_GetUint64_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ConfigReader_GetUint64_Call) RunAndReturn(run func(key string) uint64) *ConfigReader_GetUint64_Call {
	_c.Call.Return(run)
	return _c
}

// IsSet provides a mock function for the type ConfigReader
func (_mock *ConfigReader) IsSet(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for IsSet")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConfigReader_IsSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSet'
type ConfigReader_IsSet_Call struct {
	*mock.Call
}

// IsSet is a helper method to define mock.On call
//   - key string
func (_e *ConfigReader_Expecter) IsSet(key any) *ConfigReader_IsSet_Call {
	return &ConfigReader_IsSet_Call{Call: _e.mock.On("IsSet", key)}
}

func (_c *ConfigReader_IsSet_Call) Run(run func(key string)) *ConfigReader_IsSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigReader_IsSet_Call) Return(b bool) *ConfigReader_IsSet_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConfigReader_IsSet_Call) RunAndReturn(run func(key string) bool) *ConfigReader_IsSet_Call {
	_c.Call.Return(run)
	return _c
}
