// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/log"
	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type Logger
func (_mock *Logger) Debug(format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(format, a)
	} else {
		_mock.Called(format)
	}

	return
}

// Logger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type Logger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Debug(format any, a ...any) *Logger_Debug_Call {
	return &Logger_Debug_Call{Call: _e.mock.On("Debug",
		append([]any{format}, a...)...)}
}

func (_c *Logger_Debug_Call) Run(run func(format string, a ...interface{})) *Logger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Debug_Call) Return() *Logger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Debug_Call) RunAndReturn(run func(format string, a ...interface{})) *Logger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type Logger
func (_mock *Logger) Error(err error, format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(err, format, a)
	} else {
		_mock.Called(err, format)
	}

	return
}

// Logger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Logger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Error(err any, format any, a ...any) *Logger_Error_Call {
	return &Logger_Error_Call{Call: _e.mock.On("Error",
		append([]any{err, format}, a...)...)}
}

func (_c *Logger_Error_Call) Run(run func(err error, format string, a ...interface{})) *Logger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_Error_Call) Return() *Logger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Error_Call) RunAndReturn(run func(err error, format string, a ...interface{})) *Logger_Error_Call {
	_c.Run(run)
	return _c
}

// GetConfig provides a mock function for the type Logger
func (_mock *Logger) GetConfig() *log.LoggerConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *log.LoggerConfig
	if returnFunc, ok := ret.Get(0).(func() *log.LoggerConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log.LoggerConfig)
		}
	}
	return r0
}

// Logger_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type Logger_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *Logger_Expecter) GetConfig() *Logger_GetConfig_Call {
	return &Logger_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *Logger_GetConfig_Call) Run(run func()) *Logger_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Logger_GetConfig_Call) Return(loggerConfig *log.LoggerConfig) *Logger_GetConfig_Call {
	_c.Call.Return(loggerConfig)
	return _c
}

func (_c *Logger_GetConfig_Call) RunAndReturn(run func() *log.LoggerConfig) *Logger_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type Logger
func (_mock *Logger) Info(format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(format, a)
	} else {
		_mock.Called(format)
	}

	return
}

// Logger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Logger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Info(format any, a ...any) *Logger_Info_Call {
	return &Logger_Info_Call{Call: _e.mock.On("Info",
		append([]any{format}, a...)...)}
}

func (_c *Logger_Info_Call) Run(run func(format string, a ...interface{})) *Logger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Info_Call) Return() *Logger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Info_Call) RunAndReturn(run func(format string, a ...interface{})) *Logger_Info_Call {
	_c.Run(run)
	return _c
}

// IsLevelEnabled provides a mock function for the type Logger
func (_mock *Logger) IsLevelEnabled(level log.LogLevel) bool {
	ret := _mock.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for IsLevelEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(log.LogLevel) bool); ok {
		r0 = returnFunc(level)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Logger_IsLevelEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLevelEnabled'
type Logger_IsLevelEnabled_Call struct {
	*mock.Call
}

// IsLevelEnabled is a helper method to define mock.On call
//   - level log.LogLevel
func (_e *Logger_Expecter) IsLevelEnabled(level any) *Logger_IsLevelEnabled_Call {
	return &Logger_IsLevelEnabled_Call{Call: _e.mock.On("IsLevelEnabled", level)}
}

func (_c *Logger_IsLevelEnabled_Call) Run(run func(level log.LogLevel)) *Logger_IsLevelEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.LogLevel
		if args[0] != nil {
			arg0 = args[0].(log.LogLevel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_IsLevelEnabled_Call) Return(b bool) *Logger_IsLevelEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Logger_IsLevelEnabled_Call) RunAndReturn(run func(level log.LogLevel) bool) *Logger_IsLevelEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function for the type Logger
func (_mock *Logger) Log(level log.LogLevel, format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(level, format, a)
	} else {
		_mock.Called(level, format)
	}

	return
}

// Logger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type Logger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - level log.LogLevel
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Log(level any, format any, a ...any) *Logger_Log_Call {
	return &Logger_Log_Call{Call: _e.mock.On("Log",
		append([]any{level, format}, a...)...)}
}

func (_c *Logger_Log_Call) Run(run func(level log.LogLevel, format string, a ...interface{})) *Logger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.LogLevel
		if args[0] != nil {
			arg0 = args[0].(log.LogLevel)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_Log_Call) Return() *Logger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Log_Call) RunAndReturn(run func(level log.LogLevel, format string, a ...interface{})) *Logger_Log_Call {
	_c.Run(run)
	return _c
}

// Nested provides a mock function for the type Logger
func (_mock *Logger) Nested(name string) log.Logger {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Nested")
	}

	var r0 log.Logger
	if returnFunc, ok := ret.Get(0).(func(string) log.Logger); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}
	return r0
}

// Logger_Nested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nested'
type Logger_Nested_Call struct {
	*mock.Call
}

// Nested is a helper method to define mock.On call
//   - name string
func (_e *Logger_Expecter) Nested(name any) *Logger_Nested_Call {
	return &Logger_Nested_Call{Call: _e.mock.On("Nested", name)}
}

func (_c *Logger_Nested_Call) Run(run func(name string)) *Logger_Nested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_Nested_Call) Return(logger log.Logger) *Logger_Nested_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *Logger_Nested_Call) RunAndReturn(run func(name string) log.Logger) *Logger_Nested_Call {
	_c.Call.Return(run)
	return _c
}

// Printf provides a mock function for the type Logger
func (_mock *Logger) Printf(format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(format, a)
	} else {
		_mock.Called(format)
	}

	return
}

// Logger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type Logger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Printf(format any, a ...any) *Logger_Printf_Call {
	return &Logger_Printf_Call{Call: _e.mock.On("Printf",
		append([]any{format}, a...)...)}
}

func (_c *Logger_Printf_Call) Run(run func(format string, a ...interface{})) *Logger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Printf_Call) Return() *Logger_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Printf_Call) RunAndReturn(run func(format string, a ...interface{})) *Logger_Printf_Call {
	_c.Run(run)
	return _c
}

// SetStream provides a mock function for the type Logger
func (_mock *Logger) SetStream(config *log.LoggerStreamConfig) {
	_mock.Called(config)
	return
}

// Logger_SetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStream'
type Logger_SetStream_Call struct {
	*mock.Call
}

// SetStream is a helper method to define mock.On call
//   - config *log.LoggerStreamConfig
func (_e *Logger_Expecter) SetStream(config any) *Logger_SetStream_Call {
	return &Logger_SetStream_Call{Call: _e.mock.On("SetStream", config)}
}

func (_c *Logger_SetStream_Call) Run(run func(config *log.LoggerStreamConfig)) *Logger_SetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *log.LoggerStreamConfig
		if args[0] != nil {
			arg0 = args[0].(*log.LoggerStreamConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_SetStream_Call) Return() *Logger_SetStream_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_SetStream_Call) RunAndReturn(run func(config *log.LoggerStreamConfig)) *Logger_SetStream_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type Logger
func (_mock *Logger) Warn(err error, format string, a ...interface{}) {
	if len(a) > 0 {
		_mock.Called(err, format, a)
	} else {
		_mock.Called(err, format)
	}

	return
}

// Logger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type Logger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - err error
//   - format string
//   - a ...interface{}
func (_e *Logger_Expecter) Warn(err any, format any, a ...any) *Logger_Warn_Call {
	return &Logger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{err, format}, a...)...)}
}

func (_c *Logger_Warn_Call) Run(run func(err error, format string, a ...interface{})) *Logger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_Warn_Call) Return() *Logger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Warn_Call) RunAndReturn(run func(err error, format string, a ...interface{})) *Logger_Warn_Call {
	_c.Run(run)
	return _c
}
