// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
)

// newMysqlMigratorInternals creates a new instance of mysqlMigratorInternals. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMysqlMigratorInternals(t interface {
	mock.TestingT
	Cleanup(func())
}) *mysqlMigratorInternals {
	mock := &mysqlMigratorInternals{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mysqlMigratorInternals is an autogenerated mock type for the mysqlMigratorInternals type
type mysqlMigratorInternals struct {
	mock.Mock
}

type mysqlMigratorInternals_Expecter struct {
	mock *mock.Mock
}

func (_m *mysqlMigratorInternals) EXPECT() *mysqlMigratorInternals_Expecter {
	return &mysqlMigratorInternals_Expecter{mock: &_m.Mock}
}

// CurrentTable provides a mock function for the type mysqlMigratorInternals
func (_mock *mysqlMigratorInternals) CurrentTable(stmt *gorm.Statement) interface{} {
	ret := _mock.Called(stmt)

	if len(ret) == 0 {
		panic("no return value specified for CurrentTable")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(*gorm.Statement) interface{}); ok {
		r0 = returnFunc(stmt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// mysqlMigratorInternals_CurrentTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentTable'
type mysqlMigratorInternals_CurrentTable_Call struct {
	*mock.Call
}

// CurrentTable is a helper method to define mock.On call
//   - stmt *gorm.Statement
func (_e *mysqlMigratorInternals_Expecter) CurrentTable(stmt any) *mysqlMigratorInternals_CurrentTable_Call {
	return &mysqlMigratorInternals_CurrentTable_Call{Call: _e.mock.On("CurrentTable", stmt)}
}

func (_c *mysqlMigratorInternals_CurrentTable_Call) Run(run func(stmt *gorm.Statement)) *mysqlMigratorInternals_CurrentTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.Statement
		if args[0] != nil {
			arg0 = args[0].(*gorm.Statement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mysqlMigratorInternals_CurrentTable_Call) Return(ifaceVal interface{}) *mysqlMigratorInternals_CurrentTable_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *mysqlMigratorInternals_CurrentTable_Call) RunAndReturn(run func(stmt *gorm.Statement) interface{}) *mysqlMigratorInternals_CurrentTable_Call {
	_c.Call.Return(run)
	return _c
}

// FullDataTypeOf provides a mock function for the type mysqlMigratorInternals
func (_mock *mysqlMigratorInternals) FullDataTypeOf(field *schema.Field) clause.Expr {
	ret := _mock.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for FullDataTypeOf")
	}

	var r0 clause.Expr
	if returnFunc, ok := ret.Get(0).(func(*schema.Field) clause.Expr); ok {
		r0 = returnFunc(field)
	} else {
		r0 = ret.Get(0).(clause.Expr)
	}
	return r0
}

// mysqlMigratorInternals_FullDataTypeOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullDataTypeOf'
type mysqlMigratorInternals_FullDataTypeOf_Call struct {
	*mock.Call
}

// FullDataTypeOf is a helper method to define mock.On call
//   - field *schema.Field
func (_e *mysqlMigratorInternals_Expecter) FullDataTypeOf(field any) *mysqlMigratorInternals_FullDataTypeOf_Call {
	return &mysqlMigratorInternals_FullDataTypeOf_Call{Call: _e.mock.On("FullDataTypeOf", field)}
}

func (_c *mysqlMigratorInternals_FullDataTypeOf_Call) Run(run func(field *schema.Field)) *mysqlMigratorInternals_FullDataTypeOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *schema.Field
		if args[0] != nil {
			arg0 = args[0].(*schema.Field)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mysqlMigratorInternals_FullDataTypeOf_Call) Return(expr clause.Expr) *mysqlMigratorInternals_FullDataTypeOf_Call {
	_c.Call.Return(expr)
	return _c
}

func (_c *mysqlMigratorInternals_FullDataTypeOf_Call) RunAndReturn(run func(field *schema.Field) clause.Expr) *mysqlMigratorInternals_FullDataTypeOf_Call {
	_c.Call.Return(run)
	return _c
}

// RunWithValue provides a mock function for the type mysqlMigratorInternals
func (_mock *mysqlMigratorInternals) RunWithValue(value interface{}, fc func(*gorm.Statement) error) error {
	ret := _mock.Called(value, fc)

	if len(ret) == 0 {
		panic("no return value specified for RunWithValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, func(*gorm.Statement) error) error); ok {
		r0 = returnFunc(value, fc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mysqlMigratorInternals_RunWithValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWithValue'
type mysqlMigratorInternals_RunWithValue_Call struct {
	*mock.Call
}

// RunWithValue is a helper method to define mock.On call
//   - value interface{}
//   - fc func(*gorm.Statement) error
func (_e *mysqlMigratorInternals_Expecter) RunWithValue(value any, fc any) *mysqlMigratorInternals_RunWithValue_Call {
	return &mysqlMigratorInternals_RunWithValue_Call{Call: _e.mock.On("RunWithValue", value, fc)}
}

func (_c *mysqlMigratorInternals_RunWithValue_Call) Run(run func(value interface{}, fc func(*gorm.Statement) error)) *mysqlMigratorInternals_RunWithValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 func(*gorm.Statement) error
		if args[1] != nil {
			arg1 = args[1].(func(*gorm.Statement) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mysqlMigratorInternals_RunWithValue_Call) Return(err error) *mysqlMigratorInternals_RunWithValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mysqlMigratorInternals_RunWithValue_Call) RunAndReturn(run func(value interface{}, fc func(*gorm.Statement) error) error) *mysqlMigratorInternals_RunWithValue_Call {
	_c.Call.Return(run)
	return _c
}
