// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/dal"
	mock "github.com/stretchr/testify/mock"
)

// NewCustomMerge creates a new instance of CustomMerge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomMerge[M dal.Tabler](t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomMerge[M] {
	mock := &CustomMerge[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomMerge is an autogenerated mock type for the CustomMerge type
type CustomMerge[M dal.Tabler] struct {
	mock.Mock
}

type CustomMerge_Expecter[M dal.Tabler] struct {
	mock *mock.Mock
}

func (_m *CustomMerge[M]) EXPECT() *CustomMerge_Expecter[M] {
	return &CustomMerge_Expecter[M]{mock: &_m.Mock}
}

// MergeFromRequest provides a mock function for the type CustomMerge
func (_mock *CustomMerge[M]) MergeFromRequest(target *M, body map[string]interface{}) error {
	ret := _mock.Called(target, body)

	if len(ret) == 0 {
		panic("no return value specified for MergeFromRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*M, map[string]interface{}) error); ok {
		r0 = returnFunc(target, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomMerge_MergeFromRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeFromRequest'
type CustomMerge_MergeFromRequest_Call[M dal.Tabler] struct {
	*mock.Call
}

// MergeFromRequest is a helper method to define mock.On call
//   - target *M
//   - body map[string]interface{}
func (_e *CustomMerge_Expecter[M]) MergeFromRequest(target any, body any) *CustomMerge_MergeFromRequest_Call[M] {
	return &CustomMerge_MergeFromRequest_Call[M]{Call: _e.mock.On("MergeFromRequest", target, body)}
}

func (_c *CustomMerge_MergeFromRequest_Call[M]) Run(run func(target *M, body map[string]interface{})) *CustomMerge_MergeFromRequest_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *M
		if args[0] != nil {
			arg0 = args[0].(*M)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomMerge_MergeFromRequest_Call[M]) Return(err error) *CustomMerge_MergeFromRequest_Call[M] {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomMerge_MergeFromRequest_Call[M]) RunAndReturn(run func(target *M, body map[string]interface{}) error) *CustomMerge_MergeFromRequest_Call[M] {
	_c.Call.Return(run)
	return _c
}
