// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewIterator creates a new instance of Iterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Iterator {
	mock := &Iterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Iterator is an autogenerated mock type for the Iterator type
type Iterator struct {
	mock.Mock
}

type Iterator_Expecter struct {
	mock *mock.Mock
}

func (_m *Iterator) EXPECT() *Iterator_Expecter {
	return &Iterator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Iterator
func (_mock *Iterator) Close() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Iterator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Iterator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Iterator_Expecter) Close() *Iterator_Close_Call {
	return &Iterator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Iterator_Close_Call) Run(run func()) *Iterator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_Close_Call) Return(error errors.Error) *Iterator_Close_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Iterator_Close_Call) RunAndReturn(run func() errors.Error) *Iterator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type Iterator
func (_mock *Iterator) Fetch() (interface{}, errors.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 interface{}
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func() (interface{}, errors.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func() errors.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// Iterator_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Iterator_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
func (_e *Iterator_Expecter) Fetch() *Iterator_Fetch_Call {
	return &Iterator_Fetch_Call{Call: _e.mock.On("Fetch")}
}

func (_c *Iterator_Fetch_Call) Run(run func()) *Iterator_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_Fetch_Call) Return(ifaceVal interface{}, error errors.Error) *Iterator_Fetch_Call {
	_c.Call.Return(ifaceVal, error)
	return _c
}

func (_c *Iterator_Fetch_Call) RunAndReturn(run func() (interface{}, errors.Error)) *Iterator_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// HasNext provides a mock function for the type Iterator
func (_mock *Iterator) HasNext() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Iterator_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type Iterator_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *Iterator_Expecter) HasNext() *Iterator_HasNext_Call {
	return &Iterator_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *Iterator_HasNext_Call) Run(run func()) *Iterator_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Iterator_HasNext_Call) Return(b bool) *Iterator_HasNext_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Iterator_HasNext_Call) RunAndReturn(run func() bool) *Iterator_HasNext_Call {
	_c.Call.Return(run)
	return _c
}
