// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewQueueNode creates a new instance of QueueNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueNode {
	mock := &QueueNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueueNode is an autogenerated mock type for the QueueNode type
type QueueNode struct {
	mock.Mock
}

type QueueNode_Expecter struct {
	mock *mock.Mock
}

func (_m *QueueNode) EXPECT() *QueueNode_Expecter {
	return &QueueNode_Expecter{mock: &_m.Mock}
}

// Data provides a mock function for the type QueueNode
func (_mock *QueueNode) Data() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// QueueNode_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type QueueNode_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *QueueNode_Expecter) Data() *QueueNode_Data_Call {
	return &QueueNode_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *QueueNode_Data_Call) Run(run func()) *QueueNode_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueNode_Data_Call) Return(ifaceVal interface{}) *QueueNode_Data_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *QueueNode_Data_Call) RunAndReturn(run func() interface{}) *QueueNode_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type QueueNode
func (_mock *QueueNode) Next() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// QueueNode_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type QueueNode_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *QueueNode_Expecter) Next() *QueueNode_Next_Call {
	return &QueueNode_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *QueueNode_Next_Call) Run(run func()) *QueueNode_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueNode_Next_Call) Return(ifaceVal interface{}) *QueueNode_Next_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *QueueNode_Next_Call) RunAndReturn(run func() interface{}) *QueueNode_Next_Call {
	_c.Call.Return(run)
	return _c
}

// SetNext provides a mock function for the type QueueNode
func (_mock *QueueNode) SetNext(next interface{}) {
	_mock.Called(next)
	return
}

// QueueNode_SetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNext'
type QueueNode_SetNext_Call struct {
	*mock.Call
}

// SetNext is a helper method to define mock.On call
//   - next interface{}
func (_e *QueueNode_Expecter) SetNext(next any) *QueueNode_SetNext_Call {
	return &QueueNode_SetNext_Call{Call: _e.mock.On("SetNext", next)}
}

func (_c *QueueNode_SetNext_Call) Run(run func(next interface{})) *QueueNode_SetNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueueNode_SetNext_Call) Return() *QueueNode_SetNext_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueueNode_SetNext_Call) RunAndReturn(run func(next interface{})) *QueueNode_SetNext_Call {
	_c.Run(run)
	return _c
}
