// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"
	"net/url"
	"time"

	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewRateLimitedApiClient creates a new instance of RateLimitedApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitedApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitedApiClient {
	mock := &RateLimitedApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RateLimitedApiClient is an autogenerated mock type for the RateLimitedApiClient type
type RateLimitedApiClient struct {
	mock.Mock
}

type RateLimitedApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RateLimitedApiClient) EXPECT() *RateLimitedApiClient_Expecter {
	return &RateLimitedApiClient_Expecter{mock: &_m.Mock}
}

// DoGetAsync provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) DoGetAsync(path string, query url.Values, header http.Header, handler plugin.ApiAsyncCallback) {
	_mock.Called(path, query, header, handler)
	return
}

// RateLimitedApiClient_DoGetAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoGetAsync'
type RateLimitedApiClient_DoGetAsync_Call struct {
	*mock.Call
}

// DoGetAsync is a helper method to define mock.On call
//   - path string
//   - query url.Values
//   - header http.Header
//   - handler plugin.ApiAsyncCallback
func (_e *RateLimitedApiClient_Expecter) DoGetAsync(path any, query any, header any, handler any) *RateLimitedApiClient_DoGetAsync_Call {
	return &RateLimitedApiClient_DoGetAsync_Call{Call: _e.mock.On("DoGetAsync", path, query, header, handler)}
}

func (_c *RateLimitedApiClient_DoGetAsync_Call) Run(run func(path string, query url.Values, header http.Header, handler plugin.ApiAsyncCallback)) *RateLimitedApiClient_DoGetAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		var arg2 http.Header
		if args[2] != nil {
			arg2 = args[2].(http.Header)
		}
		var arg3 plugin.ApiAsyncCallback
		if args[3] != nil {
			arg3 = args[3].(plugin.ApiAsyncCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RateLimitedApiClient_DoGetAsync_Call) Return() *RateLimitedApiClient_DoGetAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_DoGetAsync_Call) RunAndReturn(run func(path string, query url.Values, header http.Header, handler plugin.ApiAsyncCallback)) *RateLimitedApiClient_DoGetAsync_Call {
	_c.Run(run)
	return _c
}

// DoPostAsync provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) DoPostAsync(path string, query url.Values, body interface{}, header http.Header, handler plugin.ApiAsyncCallback) {
	_mock.Called(path, query, body, header, handler)
	return
}

// RateLimitedApiClient_DoPostAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoPostAsync'
type RateLimitedApiClient_DoPostAsync_Call struct {
	*mock.Call
}

// DoPostAsync is a helper method to define mock.On call
//   - path string
//   - query url.Values
//   - body interface{}
//   - header http.Header
//   - handler plugin.ApiAsyncCallback
func (_e *RateLimitedApiClient_Expecter) DoPostAsync(path any, query any, body any, header any, handler any) *RateLimitedApiClient_DoPostAsync_Call {
	return &RateLimitedApiClient_DoPostAsync_Call{Call: _e.mock.On("DoPostAsync", path, query, body, header, handler)}
}

func (_c *RateLimitedApiClient_DoPostAsync_Call) Run(run func(path string, query url.Values, body interface{}, header http.Header, handler plugin.ApiAsyncCallback)) *RateLimitedApiClient_DoPostAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 http.Header
		if args[3] != nil {
			arg3 = args[3].(http.Header)
		}
		var arg4 plugin.ApiAsyncCallback
		if args[4] != nil {
			arg4 = args[4].(plugin.ApiAsyncCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RateLimitedApiClient_DoPostAsync_Call) Return() *RateLimitedApiClient_DoPostAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_DoPostAsync_Call) RunAndReturn(run func(path string, query url.Values, body interface{}, header http.Header, handler plugin.ApiAsyncCallback)) *RateLimitedApiClient_DoPostAsync_Call {
	_c.Run(run)
	return _c
}

// GetAfterFunction provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) GetAfterFunction() plugin.ApiClientAfterResponse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAfterFunction")
	}

	var r0 plugin.ApiClientAfterResponse
	if returnFunc, ok := ret.Get(0).(func() plugin.ApiClientAfterResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ApiClientAfterResponse)
		}
	}
	return r0
}

// RateLimitedApiClient_GetAfterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAfterFunction'
type RateLimitedApiClient_GetAfterFunction_Call struct {
	*mock.Call
}

// GetAfterFunction is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) GetAfterFunction() *RateLimitedApiClient_GetAfterFunction_Call {
	return &RateLimitedApiClient_GetAfterFunction_Call{Call: _e.mock.On("GetAfterFunction")}
}

func (_c *RateLimitedApiClient_GetAfterFunction_Call) Run(run func()) *RateLimitedApiClient_GetAfterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_GetAfterFunction_Call) Return(apiClientAfterResponse plugin.ApiClientAfterResponse) *RateLimitedApiClient_GetAfterFunction_Call {
	_c.Call.Return(apiClientAfterResponse)
	return _c
}

func (_c *RateLimitedApiClient_GetAfterFunction_Call) RunAndReturn(run func() plugin.ApiClientAfterResponse) *RateLimitedApiClient_GetAfterFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetNumOfWorkers provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) GetNumOfWorkers() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNumOfWorkers")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// RateLimitedApiClient_GetNumOfWorkers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNumOfWorkers'
type RateLimitedApiClient_GetNumOfWorkers_Call struct {
	*mock.Call
}

// GetNumOfWorkers is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) GetNumOfWorkers() *RateLimitedApiClient_GetNumOfWorkers_Call {
	return &RateLimitedApiClient_GetNumOfWorkers_Call{Call: _e.mock.On("GetNumOfWorkers")}
}

func (_c *RateLimitedApiClient_GetNumOfWorkers_Call) Run(run func()) *RateLimitedApiClient_GetNumOfWorkers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_GetNumOfWorkers_Call) Return(n int) *RateLimitedApiClient_GetNumOfWorkers_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *RateLimitedApiClient_GetNumOfWorkers_Call) RunAndReturn(run func() int) *RateLimitedApiClient_GetNumOfWorkers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTickInterval provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) GetTickInterval() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTickInterval")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// RateLimitedApiClient_GetTickInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTickInterval'
type RateLimitedApiClient_GetTickInterval_Call struct {
	*mock.Call
}

// GetTickInterval is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) GetTickInterval() *RateLimitedApiClient_GetTickInterval_Call {
	return &RateLimitedApiClient_GetTickInterval_Call{Call: _e.mock.On("GetTickInterval")}
}

func (_c *RateLimitedApiClient_GetTickInterval_Call) Run(run func()) *RateLimitedApiClient_GetTickInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_GetTickInterval_Call) Return(duration time.Duration) *RateLimitedApiClient_GetTickInterval_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *RateLimitedApiClient_GetTickInterval_Call) RunAndReturn(run func() time.Duration) *RateLimitedApiClient_GetTickInterval_Call {
	_c.Call.Return(run)
	return _c
}

// HasError provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) HasError() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RateLimitedApiClient_HasError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasError'
type RateLimitedApiClient_HasError_Call struct {
	*mock.Call
}

// HasError is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) HasError() *RateLimitedApiClient_HasError_Call {
	return &RateLimitedApiClient_HasError_Call{Call: _e.mock.On("HasError")}
}

func (_c *RateLimitedApiClient_HasError_Call) Run(run func()) *RateLimitedApiClient_HasError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_HasError_Call) Return(b bool) *RateLimitedApiClient_HasError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RateLimitedApiClient_HasError_Call) RunAndReturn(run func() bool) *RateLimitedApiClient_HasError_Call {
	_c.Call.Return(run)
	return _c
}

// NextTick provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) NextTick(task func() errors.Error) {
	_mock.Called(task)
	return
}

// RateLimitedApiClient_NextTick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextTick'
type RateLimitedApiClient_NextTick_Call struct {
	*mock.Call
}

// NextTick is a helper method to define mock.On call
//   - task func() errors.Error
func (_e *RateLimitedApiClient_Expecter) NextTick(task any) *RateLimitedApiClient_NextTick_Call {
	return &RateLimitedApiClient_NextTick_Call{Call: _e.mock.On("NextTick", task)}
}

func (_c *RateLimitedApiClient_NextTick_Call) Run(run func(task func() errors.Error)) *RateLimitedApiClient_NextTick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() errors.Error
		if args[0] != nil {
			arg0 = args[0].(func() errors.Error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RateLimitedApiClient_NextTick_Call) Return() *RateLimitedApiClient_NextTick_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_NextTick_Call) RunAndReturn(run func(task func() errors.Error)) *RateLimitedApiClient_NextTick_Call {
	_c.Run(run)
	return _c
}

// Release provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) Release() {
	_mock.Called()
	return
}

// RateLimitedApiClient_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type RateLimitedApiClient_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) Release() *RateLimitedApiClient_Release_Call {
	return &RateLimitedApiClient_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *RateLimitedApiClient_Release_Call) Run(run func()) *RateLimitedApiClient_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_Release_Call) Return() *RateLimitedApiClient_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_Release_Call) RunAndReturn(run func()) *RateLimitedApiClient_Release_Call {
	_c.Run(run)
	return _c
}

// Reset provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) Reset(d time.Duration) {
	_mock.Called(d)
	return
}

// RateLimitedApiClient_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type RateLimitedApiClient_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - d time.Duration
func (_e *RateLimitedApiClient_Expecter) Reset(d any) *RateLimitedApiClient_Reset_Call {
	return &RateLimitedApiClient_Reset_Call{Call: _e.mock.On("Reset", d)}
}

func (_c *RateLimitedApiClient_Reset_Call) Run(run func(d time.Duration)) *RateLimitedApiClient_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RateLimitedApiClient_Reset_Call) Return() *RateLimitedApiClient_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_Reset_Call) RunAndReturn(run func(d time.Duration)) *RateLimitedApiClient_Reset_Call {
	_c.Run(run)
	return _c
}

// SetAfterFunction provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) SetAfterFunction(callback plugin.ApiClientAfterResponse) {
	_mock.Called(callback)
	return
}

// RateLimitedApiClient_SetAfterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAfterFunction'
type RateLimitedApiClient_SetAfterFunction_Call struct {
	*mock.Call
}

// SetAfterFunction is a helper method to define mock.On call
//   - callback plugin.ApiClientAfterResponse
func (_e *RateLimitedApiClient_Expecter) SetAfterFunction(callback any) *RateLimitedApiClient_SetAfterFunction_Call {
	return &RateLimitedApiClient_SetAfterFunction_Call{Call: _e.mock.On("SetAfterFunction", callback)}
}

func (_c *RateLimitedApiClient_SetAfterFunction_Call) Run(run func(callback plugin.ApiClientAfterResponse)) *RateLimitedApiClient_SetAfterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.ApiClientAfterResponse
		if args[0] != nil {
			arg0 = args[0].(plugin.ApiClientAfterResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RateLimitedApiClient_SetAfterFunction_Call) Return() *RateLimitedApiClient_SetAfterFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *RateLimitedApiClient_SetAfterFunction_Call) RunAndReturn(run func(callback plugin.ApiClientAfterResponse)) *RateLimitedApiClient_SetAfterFunction_Call {
	_c.Run(run)
	return _c
}

// WaitAsync provides a mock function for the type RateLimitedApiClient
func (_mock *RateLimitedApiClient) WaitAsync() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitAsync")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// RateLimitedApiClient_WaitAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitAsync'
type RateLimitedApiClient_WaitAsync_Call struct {
	*mock.Call
}

// WaitAsync is a helper method to define mock.On call
func (_e *RateLimitedApiClient_Expecter) WaitAsync() *RateLimitedApiClient_WaitAsync_Call {
	return &RateLimitedApiClient_WaitAsync_Call{Call: _e.mock.On("WaitAsync")}
}

func (_c *RateLimitedApiClient_WaitAsync_Call) Run(run func()) *RateLimitedApiClient_WaitAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateLimitedApiClient_WaitAsync_Call) Return(error errors.Error) *RateLimitedApiClient_WaitAsync_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *RateLimitedApiClient_WaitAsync_Call) RunAndReturn(run func() errors.Error) *RateLimitedApiClient_WaitAsync_Call {
	_c.Call.Return(run)
	return _c
}
