// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewScopeDatabaseHelper creates a new instance of ScopeDatabaseHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopeDatabaseHelper[Conn any, Scope plugin.ToolLayerScope, Tr any](t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopeDatabaseHelper[Conn, Scope, Tr] {
	mock := &ScopeDatabaseHelper[Conn, Scope, Tr]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopeDatabaseHelper is an autogenerated mock type for the ScopeDatabaseHelper type
type ScopeDatabaseHelper[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	mock.Mock
}

type ScopeDatabaseHelper_Expecter[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	mock *mock.Mock
}

func (_m *ScopeDatabaseHelper[Conn, Scope, Tr]) EXPECT() *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]{mock: &_m.Mock}
}

// DeleteScope provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) DeleteScope(scope *Scope) errors.Error {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScope")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(*Scope) errors.Error); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ScopeDatabaseHelper_DeleteScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteScope'
type ScopeDatabaseHelper_DeleteScope_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// DeleteScope is a helper method to define mock.On call
//   - scope *Scope
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) DeleteScope(scope any) *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr]{Call: _e.mock.On("DeleteScope", scope)}
}

func (_c *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr]) Run(run func(scope *Scope)) *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Scope
		if args[0] != nil {
			arg0 = args[0].(*Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr]) Return(error errors.Error) *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(error)
	return _c
}

func (_c *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr]) RunAndReturn(run func(scope *Scope) errors.Error) *ScopeDatabaseHelper_DeleteScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// GetScope provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) GetScope(connectionId uint64, scopeId string) (*Scope, errors.Error) {
	ret := _mock.Called(connectionId, scopeId)

	if len(ret) == 0 {
		panic("no return value specified for GetScope")
	}

	var r0 *Scope
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) (*Scope, errors.Error)); ok {
		return returnFunc(connectionId, scopeId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *Scope); ok {
		r0 = returnFunc(connectionId, scopeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Scope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string) errors.Error); ok {
		r1 = returnFunc(connectionId, scopeId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// ScopeDatabaseHelper_GetScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScope'
type ScopeDatabaseHelper_GetScope_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// GetScope is a helper method to define mock.On call
//   - connectionId uint64
//   - scopeId string
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) GetScope(connectionId any, scopeId any) *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr]{Call: _e.mock.On("GetScope", connectionId, scopeId)}
}

func (_c *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr]) Run(run func(connectionId uint64, scopeId string)) *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr]) Return(v *Scope, error errors.Error) *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(v, error)
	return _c
}

func (_c *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr]) RunAndReturn(run func(connectionId uint64, scopeId string) (*Scope, errors.Error)) *ScopeDatabaseHelper_GetScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// GetScopeAndConfig provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) GetScopeAndConfig(connectionId uint64, scopeId string) (*Scope, *Tr, errors.Error) {
	ret := _mock.Called(connectionId, scopeId)

	if len(ret) == 0 {
		panic("no return value specified for GetScopeAndConfig")
	}

	var r0 *Scope
	var r1 *Tr
	var r2 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) (*Scope, *Tr, errors.Error)); ok {
		return returnFunc(connectionId, scopeId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *Scope); ok {
		r0 = returnFunc(connectionId, scopeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Scope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string) *Tr); ok {
		r1 = returnFunc(connectionId, scopeId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*Tr)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, string) errors.Error); ok {
		r2 = returnFunc(connectionId, scopeId)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(errors.Error)
		}
	}
	return r0, r1, r2
}

// ScopeDatabaseHelper_GetScopeAndConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScopeAndConfig'
type ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// GetScopeAndConfig is a helper method to define mock.On call
//   - connectionId uint64
//   - scopeId string
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) GetScopeAndConfig(connectionId any, scopeId any) *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr]{Call: _e.mock.On("GetScopeAndConfig", connectionId, scopeId)}
}

func (_c *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr]) Run(run func(connectionId uint64, scopeId string)) *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr]) Return(v *Scope, v1 *Tr, error errors.Error) *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr] {
	_c.Call.Return(v, v1, error)
	return _c
}

func (_c *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr]) RunAndReturn(run func(connectionId uint64, scopeId string) (*Scope, *Tr, errors.Error)) *ScopeDatabaseHelper_GetScopeAndConfig_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// GetScopeConfig provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) GetScopeConfig(ruleId uint64) (*Tr, errors.Error) {
	ret := _mock.Called(ruleId)

	if len(ret) == 0 {
		panic("no return value specified for GetScopeConfig")
	}

	var r0 *Tr
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*Tr, errors.Error)); ok {
		return returnFunc(ruleId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *Tr); ok {
		r0 = returnFunc(ruleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Tr)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) errors.Error); ok {
		r1 = returnFunc(ruleId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// ScopeDatabaseHelper_GetScopeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScopeConfig'
type ScopeDatabaseHelper_GetScopeConfig_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// GetScopeConfig is a helper method to define mock.On call
//   - ruleId uint64
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) GetScopeConfig(ruleId any) *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr]{Call: _e.mock.On("GetScopeConfig", ruleId)}
}

func (_c *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr]) Run(run func(ruleId uint64)) *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr]) Return(v *Tr, error errors.Error) *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr] {
	_c.Call.Return(v, error)
	return _c
}

func (_c *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr]) RunAndReturn(run func(ruleId uint64) (*Tr, errors.Error)) *ScopeDatabaseHelper_GetScopeConfig_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// ListScopeConfigs provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) ListScopeConfigs(ruleIds []uint64) ([]*Tr, errors.Error) {
	ret := _mock.Called(ruleIds)

	if len(ret) == 0 {
		panic("no return value specified for ListScopeConfigs")
	}

	var r0 []*Tr
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func([]uint64) ([]*Tr, errors.Error)); ok {
		return returnFunc(ruleIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) []*Tr); ok {
		r0 = returnFunc(ruleIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Tr)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) errors.Error); ok {
		r1 = returnFunc(ruleIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// ScopeDatabaseHelper_ListScopeConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScopeConfigs'
type ScopeDatabaseHelper_ListScopeConfigs_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// ListScopeConfigs is a helper method to define mock.On call
//   - ruleIds []uint64
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) ListScopeConfigs(ruleIds any) *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr]{Call: _e.mock.On("ListScopeConfigs", ruleIds)}
}

func (_c *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr]) Run(run func(ruleIds []uint64)) *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr]) Return(vs []*Tr, error errors.Error) *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr] {
	_c.Call.Return(vs, error)
	return _c
}

func (_c *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr]) RunAndReturn(run func(ruleIds []uint64) ([]*Tr, errors.Error)) *ScopeDatabaseHelper_ListScopeConfigs_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// ListScopes provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) ListScopes(input *plugin.ApiResourceInput, connectionId uint64) ([]*Scope, int64, errors.Error) {
	ret := _mock.Called(input, connectionId)

	if len(ret) == 0 {
		panic("no return value specified for ListScopes")
	}

	var r0 []*Scope
	var r1 int64
	var r2 errors.Error
	if returnFunc, ok := ret.Get(0).(func(*plugin.ApiResourceInput, uint64) ([]*Scope, int64, errors.Error)); ok {
		return returnFunc(input, connectionId)
	}
	if returnFunc, ok := ret.Get(0).(func(*plugin.ApiResourceInput, uint64) []*Scope); ok {
		r0 = returnFunc(input, connectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Scope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*plugin.ApiResourceInput, uint64) int64); ok {
		r1 = returnFunc(input, connectionId)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(*plugin.ApiResourceInput, uint64) errors.Error); ok {
		r2 = returnFunc(input, connectionId)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(errors.Error)
		}
	}
	return r0, r1, r2
}

// ScopeDatabaseHelper_ListScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScopes'
type ScopeDatabaseHelper_ListScopes_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// ListScopes is a helper method to define mock.On call
//   - input *plugin.ApiResourceInput
//   - connectionId uint64
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) ListScopes(input any, connectionId any) *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr]{Call: _e.mock.On("ListScopes", input, connectionId)}
}

func (_c *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr]) Run(run func(input *plugin.ApiResourceInput, connectionId uint64)) *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *plugin.ApiResourceInput
		if args[0] != nil {
			arg0 = args[0].(*plugin.ApiResourceInput)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr]) Return(vs []*Scope, n int64, error errors.Error) *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr] {
	_c.Call.Return(vs, n, error)
	return _c
}

func (_c *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr]) RunAndReturn(run func(input *plugin.ApiResourceInput, connectionId uint64) ([]*Scope, int64, errors.Error)) *ScopeDatabaseHelper_ListScopes_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// SaveScope provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) SaveScope(scopes []*Scope) errors.Error {
	ret := _mock.Called(scopes)

	if len(ret) == 0 {
		panic("no return value specified for SaveScope")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func([]*Scope) errors.Error); ok {
		r0 = returnFunc(scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ScopeDatabaseHelper_SaveScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveScope'
type ScopeDatabaseHelper_SaveScope_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// SaveScope is a helper method to define mock.On call
//   - scopes []*Scope
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) SaveScope(scopes any) *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr]{Call: _e.mock.On("SaveScope", scopes)}
}

func (_c *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr]) Run(run func(scopes []*Scope)) *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*Scope
		if args[0] != nil {
			arg0 = args[0].([]*Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr]) Return(error errors.Error) *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(error)
	return _c
}

func (_c *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr]) RunAndReturn(run func(scopes []*Scope) errors.Error) *ScopeDatabaseHelper_SaveScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// UpdateScope provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) UpdateScope(scope *Scope) errors.Error {
	ret := _mock.Called(scope)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScope")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(*Scope) errors.Error); ok {
		r0 = returnFunc(scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ScopeDatabaseHelper_UpdateScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScope'
type ScopeDatabaseHelper_UpdateScope_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// UpdateScope is a helper method to define mock.On call
//   - scope *Scope
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) UpdateScope(scope any) *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr]{Call: _e.mock.On("UpdateScope", scope)}
}

func (_c *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr]) Run(run func(scope *Scope)) *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Scope
		if args[0] != nil {
			arg0 = args[0].(*Scope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr]) Return(error errors.Error) *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(error)
	return _c
}

func (_c *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr]) RunAndReturn(run func(scope *Scope) errors.Error) *ScopeDatabaseHelper_UpdateScope_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}

// VerifyConnection provides a mock function for the type ScopeDatabaseHelper
func (_mock *ScopeDatabaseHelper[Conn, Scope, Tr]) VerifyConnection(connectionId uint64) errors.Error {
	ret := _mock.Called(connectionId)

	if len(ret) == 0 {
		panic("no return value specified for VerifyConnection")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64) errors.Error); ok {
		r0 = returnFunc(connectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ScopeDatabaseHelper_VerifyConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyConnection'
type ScopeDatabaseHelper_VerifyConnection_Call[Conn any, Scope plugin.ToolLayerScope, Tr any] struct {
	*mock.Call
}

// VerifyConnection is a helper method to define mock.On call
//   - connectionId uint64
func (_e *ScopeDatabaseHelper_Expecter[Conn, Scope, Tr]) VerifyConnection(connectionId any) *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr] {
	return &ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr]{Call: _e.mock.On("VerifyConnection", connectionId)}
}

func (_c *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr]) Run(run func(connectionId uint64)) *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr]) Return(error errors.Error) *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr] {
	_c.Call.Return(error)
	return _c
}

func (_c *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr]) RunAndReturn(run func(connectionId uint64) errors.Error) *ScopeDatabaseHelper_VerifyConnection_Call[Conn, Scope, Tr] {
	_c.Call.Return(run)
	return _c
}
