// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewCustomValidator creates a new instance of CustomValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomValidator {
	mock := &CustomValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomValidator is an autogenerated mock type for the CustomValidator type
type CustomValidator struct {
	mock.Mock
}

type CustomValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomValidator) EXPECT() *CustomValidator_Expecter {
	return &CustomValidator_Expecter{mock: &_m.Mock}
}

// CustomValidate provides a mock function for the type CustomValidator
func (_mock *CustomValidator) CustomValidate(entity interface{}, validate *validator.Validate) errors.Error {
	ret := _mock.Called(entity, validate)

	if len(ret) == 0 {
		panic("no return value specified for CustomValidate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *validator.Validate) errors.Error); ok {
		r0 = returnFunc(entity, validate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// CustomValidator_CustomValidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomValidate'
type CustomValidator_CustomValidate_Call struct {
	*mock.Call
}

// CustomValidate is a helper method to define mock.On call
//   - entity interface{}
//   - validate *validator.Validate
func (_e *CustomValidator_Expecter) CustomValidate(entity any, validate any) *CustomValidator_CustomValidate_Call {
	return &CustomValidator_CustomValidate_Call{Call: _e.mock.On("CustomValidate", entity, validate)}
}

func (_c *CustomValidator_CustomValidate_Call) Run(run func(entity interface{}, validate *validator.Validate)) *CustomValidator_CustomValidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *validator.Validate
		if args[1] != nil {
			arg1 = args[1].(*validator.Validate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomValidator_CustomValidate_Call) Return(error errors.Error) *CustomValidator_CustomValidate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *CustomValidator_CustomValidate_Call) RunAndReturn(run func(entity interface{}, validate *validator.Validate) errors.Error) *CustomValidator_CustomValidate_Call {
	_c.Call.Return(run)
	return _c
}
