// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewComplexValidate creates a new instance of ComplexValidate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComplexValidate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComplexValidate {
	mock := &ComplexValidate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ComplexValidate is an autogenerated mock type for the ComplexValidate type
type ComplexValidate struct {
	mock.Mock
}

type ComplexValidate_Expecter struct {
	mock *mock.Mock
}

func (_m *ComplexValidate) EXPECT() *ComplexValidate_Expecter {
	return &ComplexValidate_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ComplexValidate
func (_mock *ComplexValidate) Validate() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ComplexValidate_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ComplexValidate_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *ComplexValidate_Expecter) Validate() *ComplexValidate_Validate_Call {
	return &ComplexValidate_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *ComplexValidate_Validate_Call) Run(run func()) *ComplexValidate_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ComplexValidate_Validate_Call) Return(error errors.Error) *ComplexValidate_Validate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *ComplexValidate_Validate_Call) RunAndReturn(run func() errors.Error) *ComplexValidate_Validate_Call {
	_c.Call.Return(run)
	return _c
}
