// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewDynamicTabler creates a new instance of DynamicTabler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamicTabler(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamicTabler {
	mock := &DynamicTabler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DynamicTabler is an autogenerated mock type for the DynamicTabler type
type DynamicTabler struct {
	mock.Mock
}

type DynamicTabler_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamicTabler) EXPECT() *DynamicTabler_Expecter {
	return &DynamicTabler_Expecter{mock: &_m.Mock}
}

// From provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) From(src any) errors.Error {
	ret := _mock.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for From")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(any) errors.Error); ok {
		r0 = returnFunc(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// DynamicTabler_From_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'From'
type DynamicTabler_From_Call struct {
	*mock.Call
}

// From is a helper method to define mock.On call
//   - src any
func (_e *DynamicTabler_Expecter) From(src any) *DynamicTabler_From_Call {
	return &DynamicTabler_From_Call{Call: _e.mock.On("From", src)}
}

func (_c *DynamicTabler_From_Call) Run(run func(src any)) *DynamicTabler_From_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DynamicTabler_From_Call) Return(error errors.Error) *DynamicTabler_From_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *DynamicTabler_From_Call) RunAndReturn(run func(src any) errors.Error) *DynamicTabler_From_Call {
	_c.Call.Return(run)
	return _c
}

// MarshalJSON provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) MarshalJSON() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalJSON")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamicTabler_MarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalJSON'
type DynamicTabler_MarshalJSON_Call struct {
	*mock.Call
}

// MarshalJSON is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) MarshalJSON() *DynamicTabler_MarshalJSON_Call {
	return &DynamicTabler_MarshalJSON_Call{Call: _e.mock.On("MarshalJSON")}
}

func (_c *DynamicTabler_MarshalJSON_Call) Run(run func()) *DynamicTabler_MarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_MarshalJSON_Call) Return(bytes []byte, err error) *DynamicTabler_MarshalJSON_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *DynamicTabler_MarshalJSON_Call) RunAndReturn(run func() ([]byte, error)) *DynamicTabler_MarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) New() models.DynamicTabler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 models.DynamicTabler
	if returnFunc, ok := ret.Get(0).(func() models.DynamicTabler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.DynamicTabler)
		}
	}
	return r0
}

// DynamicTabler_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type DynamicTabler_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) New() *DynamicTabler_New_Call {
	return &DynamicTabler_New_Call{Call: _e.mock.On("New")}
}

func (_c *DynamicTabler_New_Call) Run(run func()) *DynamicTabler_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_New_Call) Return(dynamicTabler models.DynamicTabler) *DynamicTabler_New_Call {
	_c.Call.Return(dynamicTabler)
	return _c
}

func (_c *DynamicTabler_New_Call) RunAndReturn(run func() models.DynamicTabler) *DynamicTabler_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewSlice provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) NewSlice() models.DynamicTabler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewSlice")
	}

	var r0 models.DynamicTabler
	if returnFunc, ok := ret.Get(0).(func() models.DynamicTabler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.DynamicTabler)
		}
	}
	return r0
}

// DynamicTabler_NewSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSlice'
type DynamicTabler_NewSlice_Call struct {
	*mock.Call
}

// NewSlice is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) NewSlice() *DynamicTabler_NewSlice_Call {
	return &DynamicTabler_NewSlice_Call{Call: _e.mock.On("NewSlice")}
}

func (_c *DynamicTabler_NewSlice_Call) Run(run func()) *DynamicTabler_NewSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_NewSlice_Call) Return(dynamicTabler models.DynamicTabler) *DynamicTabler_NewSlice_Call {
	_c.Call.Return(dynamicTabler)
	return _c
}

func (_c *DynamicTabler_NewSlice_Call) RunAndReturn(run func() models.DynamicTabler) *DynamicTabler_NewSlice_Call {
	_c.Call.Return(run)
	return _c
}

// NewValue provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) NewValue() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewValue")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// DynamicTabler_NewValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewValue'
type DynamicTabler_NewValue_Call struct {
	*mock.Call
}

// NewValue is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) NewValue() *DynamicTabler_NewValue_Call {
	return &DynamicTabler_NewValue_Call{Call: _e.mock.On("NewValue")}
}

func (_c *DynamicTabler_NewValue_Call) Run(run func()) *DynamicTabler_NewValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_NewValue_Call) Return(anyMoqParam any) *DynamicTabler_NewValue_Call {
	_c.Call.Return(anyMoqParam)
	return _c
}

func (_c *DynamicTabler_NewValue_Call) RunAndReturn(run func() any) *DynamicTabler_NewValue_Call {
	_c.Call.Return(run)
	return _c
}

// TableName provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// DynamicTabler_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type DynamicTabler_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) TableName() *DynamicTabler_TableName_Call {
	return &DynamicTabler_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *DynamicTabler_TableName_Call) Run(run func()) *DynamicTabler_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_TableName_Call) Return(s string) *DynamicTabler_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *DynamicTabler_TableName_Call) RunAndReturn(run func() string) *DynamicTabler_TableName_Call {
	_c.Call.Return(run)
	return _c
}

// To provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) To(target any) errors.Error {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for To")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(any) errors.Error); ok {
		r0 = returnFunc(target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// DynamicTabler_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type DynamicTabler_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
//   - target any
func (_e *DynamicTabler_Expecter) To(target any) *DynamicTabler_To_Call {
	return &DynamicTabler_To_Call{Call: _e.mock.On("To", target)}
}

func (_c *DynamicTabler_To_Call) Run(run func(target any)) *DynamicTabler_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DynamicTabler_To_Call) Return(error errors.Error) *DynamicTabler_To_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *DynamicTabler_To_Call) RunAndReturn(run func(target any) errors.Error) *DynamicTabler_To_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalJSON provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) UnmarshalJSON(bytes []byte) error {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DynamicTabler_UnmarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalJSON'
type DynamicTabler_UnmarshalJSON_Call struct {
	*mock.Call
}

// UnmarshalJSON is a helper method to define mock.On call
//   - bytes []byte
func (_e *DynamicTabler_Expecter) UnmarshalJSON(bytes any) *DynamicTabler_UnmarshalJSON_Call {
	return &DynamicTabler_UnmarshalJSON_Call{Call: _e.mock.On("UnmarshalJSON", bytes)}
}

func (_c *DynamicTabler_UnmarshalJSON_Call) Run(run func(bytes []byte)) *DynamicTabler_UnmarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DynamicTabler_UnmarshalJSON_Call) Return(err error) *DynamicTabler_UnmarshalJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DynamicTabler_UnmarshalJSON_Call) RunAndReturn(run func(bytes []byte) error) *DynamicTabler_UnmarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) Unwrap() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// DynamicTabler_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type DynamicTabler_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) Unwrap() *DynamicTabler_Unwrap_Call {
	return &DynamicTabler_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *DynamicTabler_Unwrap_Call) Run(run func()) *DynamicTabler_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_Unwrap_Call) Return(anyMoqParam any) *DynamicTabler_Unwrap_Call {
	_c.Call.Return(anyMoqParam)
	return _c
}

func (_c *DynamicTabler_Unwrap_Call) RunAndReturn(run func() any) *DynamicTabler_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// UnwrapPtr provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) UnwrapPtr() *any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnwrapPtr")
	}

	var r0 *any
	if returnFunc, ok := ret.Get(0).(func() *any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*any)
		}
	}
	return r0
}

// DynamicTabler_UnwrapPtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnwrapPtr'
type DynamicTabler_UnwrapPtr_Call struct {
	*mock.Call
}

// UnwrapPtr is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) UnwrapPtr() *DynamicTabler_UnwrapPtr_Call {
	return &DynamicTabler_UnwrapPtr_Call{Call: _e.mock.On("UnwrapPtr")}
}

func (_c *DynamicTabler_UnwrapPtr_Call) Run(run func()) *DynamicTabler_UnwrapPtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_UnwrapPtr_Call) Return(anyMoqParam *any) *DynamicTabler_UnwrapPtr_Call {
	_c.Call.Return(anyMoqParam)
	return _c
}

func (_c *DynamicTabler_UnwrapPtr_Call) RunAndReturn(run func() *any) *DynamicTabler_UnwrapPtr_Call {
	_c.Call.Return(run)
	return _c
}

// UnwrapSlice provides a mock function for the type DynamicTabler
func (_mock *DynamicTabler) UnwrapSlice() []any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnwrapSlice")
	}

	var r0 []any
	if returnFunc, ok := ret.Get(0).(func() []any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	return r0
}

// DynamicTabler_UnwrapSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnwrapSlice'
type DynamicTabler_UnwrapSlice_Call struct {
	*mock.Call
}

// UnwrapSlice is a helper method to define mock.On call
func (_e *DynamicTabler_Expecter) UnwrapSlice() *DynamicTabler_UnwrapSlice_Call {
	return &DynamicTabler_UnwrapSlice_Call{Call: _e.mock.On("UnwrapSlice")}
}

func (_c *DynamicTabler_UnwrapSlice_Call) Run(run func()) *DynamicTabler_UnwrapSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DynamicTabler_UnwrapSlice_Call) Return(anyMoqParams []any) *DynamicTabler_UnwrapSlice_Call {
	_c.Call.Return(anyMoqParams)
	return _c
}

func (_c *DynamicTabler_UnwrapSlice_Call) RunAndReturn(run func() []any) *DynamicTabler_UnwrapSlice_Call {
	_c.Call.Return(run)
	return _c
}
