// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/models/common"
	mock "github.com/stretchr/testify/mock"
)

// NewGetRawDataOrigin creates a new instance of GetRawDataOrigin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetRawDataOrigin(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetRawDataOrigin {
	mock := &GetRawDataOrigin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetRawDataOrigin is an autogenerated mock type for the GetRawDataOrigin type
type GetRawDataOrigin struct {
	mock.Mock
}

type GetRawDataOrigin_Expecter struct {
	mock *mock.Mock
}

func (_m *GetRawDataOrigin) EXPECT() *GetRawDataOrigin_Expecter {
	return &GetRawDataOrigin_Expecter{mock: &_m.Mock}
}

// GetRawDataOrigin provides a mock function for the type GetRawDataOrigin
func (_mock *GetRawDataOrigin) GetRawDataOrigin() *common.RawDataOrigin {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRawDataOrigin")
	}

	var r0 *common.RawDataOrigin
	if returnFunc, ok := ret.Get(0).(func() *common.RawDataOrigin); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.RawDataOrigin)
		}
	}
	return r0
}

// GetRawDataOrigin_GetRawDataOrigin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawDataOrigin'
type GetRawDataOrigin_GetRawDataOrigin_Call struct {
	*mock.Call
}

// GetRawDataOrigin is a helper method to define mock.On call
func (_e *GetRawDataOrigin_Expecter) GetRawDataOrigin() *GetRawDataOrigin_GetRawDataOrigin_Call {
	return &GetRawDataOrigin_GetRawDataOrigin_Call{Call: _e.mock.On("GetRawDataOrigin")}
}

func (_c *GetRawDataOrigin_GetRawDataOrigin_Call) Run(run func()) *GetRawDataOrigin_GetRawDataOrigin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GetRawDataOrigin_GetRawDataOrigin_Call) Return(rawDataOrigin *common.RawDataOrigin) *GetRawDataOrigin_GetRawDataOrigin_Call {
	_c.Call.Return(rawDataOrigin)
	return _c
}

func (_c *GetRawDataOrigin_GetRawDataOrigin_Call) RunAndReturn(run func() *common.RawDataOrigin) *GetRawDataOrigin_GetRawDataOrigin_Call {
	_c.Call.Return(run)
	return _c
}
