// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/dal"
	mock "github.com/stretchr/testify/mock"
)

// NewScopeConfigOperator creates a new instance of ScopeConfigOperator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopeConfigOperator[T dal.Tabler](t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopeConfigOperator[T] {
	mock := &ScopeConfigOperator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopeConfigOperator is an autogenerated mock type for the ScopeConfigOperator type
type ScopeConfigOperator[T dal.Tabler] struct {
	mock.Mock
}

type ScopeConfigOperator_Expecter[T dal.Tabler] struct {
	mock *mock.Mock
}

func (_m *ScopeConfigOperator[T]) EXPECT() *ScopeConfigOperator_Expecter[T] {
	return &ScopeConfigOperator_Expecter[T]{mock: &_m.Mock}
}

// SetConnectionId provides a mock function for the type ScopeConfigOperator
func (_mock *ScopeConfigOperator[T]) SetConnectionId(t *T, connectionId uint64) {
	_mock.Called(t, connectionId)
	return
}

// ScopeConfigOperator_SetConnectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnectionId'
type ScopeConfigOperator_SetConnectionId_Call[T dal.Tabler] struct {
	*mock.Call
}

// SetConnectionId is a helper method to define mock.On call
//   - t *T
//   - connectionId uint64
func (_e *ScopeConfigOperator_Expecter[T]) SetConnectionId(t any, connectionId any) *ScopeConfigOperator_SetConnectionId_Call[T] {
	return &ScopeConfigOperator_SetConnectionId_Call[T]{Call: _e.mock.On("SetConnectionId", t, connectionId)}
}

func (_c *ScopeConfigOperator_SetConnectionId_Call[T]) Run(run func(t *T, connectionId uint64)) *ScopeConfigOperator_SetConnectionId_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *T
		if args[0] != nil {
			arg0 = args[0].(*T)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopeConfigOperator_SetConnectionId_Call[T]) Return() *ScopeConfigOperator_SetConnectionId_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *ScopeConfigOperator_SetConnectionId_Call[T]) RunAndReturn(run func(t *T, connectionId uint64)) *ScopeConfigOperator_SetConnectionId_Call[T] {
	_c.Run(run)
	return _c
}
