// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewApiAuthenticator creates a new instance of ApiAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiAuthenticator {
	mock := &ApiAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApiAuthenticator is an autogenerated mock type for the ApiAuthenticator type
type ApiAuthenticator struct {
	mock.Mock
}

type ApiAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiAuthenticator) EXPECT() *ApiAuthenticator_Expecter {
	return &ApiAuthenticator_Expecter{mock: &_m.Mock}
}

// SetupAuthentication provides a mock function for the type ApiAuthenticator
func (_mock *ApiAuthenticator) SetupAuthentication(request *http.Request) errors.Error {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for SetupAuthentication")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) errors.Error); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ApiAuthenticator_SetupAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupAuthentication'
type ApiAuthenticator_SetupAuthentication_Call struct {
	*mock.Call
}

// SetupAuthentication is a helper method to define mock.On call
//   - request *http.Request
func (_e *ApiAuthenticator_Expecter) SetupAuthentication(request any) *ApiAuthenticator_SetupAuthentication_Call {
	return &ApiAuthenticator_SetupAuthentication_Call{Call: _e.mock.On("SetupAuthentication", request)}
}

func (_c *ApiAuthenticator_SetupAuthentication_Call) Run(run func(request *http.Request)) *ApiAuthenticator_SetupAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApiAuthenticator_SetupAuthentication_Call) Return(error errors.Error) *ApiAuthenticator_SetupAuthentication_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *ApiAuthenticator_SetupAuthentication_Call) RunAndReturn(run func(request *http.Request) errors.Error) *ApiAuthenticator_SetupAuthentication_Call {
	_c.Call.Return(run)
	return _c
}
