// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewApiConnection creates a new instance of ApiConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiConnection {
	mock := &ApiConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApiConnection is an autogenerated mock type for the ApiConnection type
type ApiConnection struct {
	mock.Mock
}

type ApiConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiConnection) EXPECT() *ApiConnection_Expecter {
	return &ApiConnection_Expecter{mock: &_m.Mock}
}

// GetEndpoint provides a mock function for the type ApiConnection
func (_mock *ApiConnection) GetEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ApiConnection_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type ApiConnection_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
func (_e *ApiConnection_Expecter) GetEndpoint() *ApiConnection_GetEndpoint_Call {
	return &ApiConnection_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint")}
}

func (_c *ApiConnection_GetEndpoint_Call) Run(run func()) *ApiConnection_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiConnection_GetEndpoint_Call) Return(s string) *ApiConnection_GetEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ApiConnection_GetEndpoint_Call) RunAndReturn(run func() string) *ApiConnection_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetProxy provides a mock function for the type ApiConnection
func (_mock *ApiConnection) GetProxy() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProxy")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ApiConnection_GetProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProxy'
type ApiConnection_GetProxy_Call struct {
	*mock.Call
}

// GetProxy is a helper method to define mock.On call
func (_e *ApiConnection_Expecter) GetProxy() *ApiConnection_GetProxy_Call {
	return &ApiConnection_GetProxy_Call{Call: _e.mock.On("GetProxy")}
}

func (_c *ApiConnection_GetProxy_Call) Run(run func()) *ApiConnection_GetProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiConnection_GetProxy_Call) Return(s string) *ApiConnection_GetProxy_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ApiConnection_GetProxy_Call) RunAndReturn(run func() string) *ApiConnection_GetProxy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimitPerHour provides a mock function for the type ApiConnection
func (_mock *ApiConnection) GetRateLimitPerHour() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimitPerHour")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// ApiConnection_GetRateLimitPerHour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimitPerHour'
type ApiConnection_GetRateLimitPerHour_Call struct {
	*mock.Call
}

// GetRateLimitPerHour is a helper method to define mock.On call
func (_e *ApiConnection_Expecter) GetRateLimitPerHour() *ApiConnection_GetRateLimitPerHour_Call {
	return &ApiConnection_GetRateLimitPerHour_Call{Call: _e.mock.On("GetRateLimitPerHour")}
}

func (_c *ApiConnection_GetRateLimitPerHour_Call) Run(run func()) *ApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiConnection_GetRateLimitPerHour_Call) Return(n int) *ApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *ApiConnection_GetRateLimitPerHour_Call) RunAndReturn(run func() int) *ApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(run)
	return _c
}
