// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"
	"net/url"

	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewApiClient creates a new instance of ApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiClient {
	mock := &ApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApiClient is an autogenerated mock type for the ApiClient type
type ApiClient struct {
	mock.Mock
}

type ApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiClient) EXPECT() *ApiClient_Expecter {
	return &ApiClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type ApiClient
func (_mock *ApiClient) Get(path string, query url.Values, headers http.Header) (*http.Response, errors.Error) {
	ret := _mock.Called(path, query, headers)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, url.Values, http.Header) (*http.Response, errors.Error)); ok {
		return returnFunc(path, query, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(string, url.Values, http.Header) *http.Response); ok {
		r0 = returnFunc(path, query, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, url.Values, http.Header) errors.Error); ok {
		r1 = returnFunc(path, query, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// ApiClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ApiClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
//   - query url.Values
//   - headers http.Header
func (_e *ApiClient_Expecter) Get(path any, query any, headers any) *ApiClient_Get_Call {
	return &ApiClient_Get_Call{Call: _e.mock.On("Get", path, query, headers)}
}

func (_c *ApiClient_Get_Call) Run(run func(path string, query url.Values, headers http.Header)) *ApiClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		var arg2 http.Header
		if args[2] != nil {
			arg2 = args[2].(http.Header)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApiClient_Get_Call) Return(response *http.Response, error errors.Error) *ApiClient_Get_Call {
	_c.Call.Return(response, error)
	return _c
}

func (_c *ApiClient_Get_Call) RunAndReturn(run func(path string, query url.Values, headers http.Header) (*http.Response, errors.Error)) *ApiClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAfterFunction provides a mock function for the type ApiClient
func (_mock *ApiClient) GetAfterFunction() plugin.ApiClientAfterResponse {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAfterFunction")
	}

	var r0 plugin.ApiClientAfterResponse
	if returnFunc, ok := ret.Get(0).(func() plugin.ApiClientAfterResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ApiClientAfterResponse)
		}
	}
	return r0
}

// ApiClient_GetAfterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAfterFunction'
type ApiClient_GetAfterFunction_Call struct {
	*mock.Call
}

// GetAfterFunction is a helper method to define mock.On call
func (_e *ApiClient_Expecter) GetAfterFunction() *ApiClient_GetAfterFunction_Call {
	return &ApiClient_GetAfterFunction_Call{Call: _e.mock.On("GetAfterFunction")}
}

func (_c *ApiClient_GetAfterFunction_Call) Run(run func()) *ApiClient_GetAfterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiClient_GetAfterFunction_Call) Return(apiClientAfterResponse plugin.ApiClientAfterResponse) *ApiClient_GetAfterFunction_Call {
	_c.Call.Return(apiClientAfterResponse)
	return _c
}

func (_c *ApiClient_GetAfterFunction_Call) RunAndReturn(run func() plugin.ApiClientAfterResponse) *ApiClient_GetAfterFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetBeforeFunction provides a mock function for the type ApiClient
func (_mock *ApiClient) GetBeforeFunction() plugin.ApiClientBeforeRequest {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBeforeFunction")
	}

	var r0 plugin.ApiClientBeforeRequest
	if returnFunc, ok := ret.Get(0).(func() plugin.ApiClientBeforeRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ApiClientBeforeRequest)
		}
	}
	return r0
}

// ApiClient_GetBeforeFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBeforeFunction'
type ApiClient_GetBeforeFunction_Call struct {
	*mock.Call
}

// GetBeforeFunction is a helper method to define mock.On call
func (_e *ApiClient_Expecter) GetBeforeFunction() *ApiClient_GetBeforeFunction_Call {
	return &ApiClient_GetBeforeFunction_Call{Call: _e.mock.On("GetBeforeFunction")}
}

func (_c *ApiClient_GetBeforeFunction_Call) Run(run func()) *ApiClient_GetBeforeFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiClient_GetBeforeFunction_Call) Return(apiClientBeforeRequest plugin.ApiClientBeforeRequest) *ApiClient_GetBeforeFunction_Call {
	_c.Call.Return(apiClientBeforeRequest)
	return _c
}

func (_c *ApiClient_GetBeforeFunction_Call) RunAndReturn(run func() plugin.ApiClientBeforeRequest) *ApiClient_GetBeforeFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type ApiClient
func (_mock *ApiClient) GetData(name string) interface{} {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// ApiClient_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type ApiClient_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
//   - name string
func (_e *ApiClient_Expecter) GetData(name any) *ApiClient_GetData_Call {
	return &ApiClient_GetData_Call{Call: _e.mock.On("GetData", name)}
}

func (_c *ApiClient_GetData_Call) Run(run func(name string)) *ApiClient_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApiClient_GetData_Call) Return(ifaceVal interface{}) *ApiClient_GetData_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *ApiClient_GetData_Call) RunAndReturn(run func(name string) interface{}) *ApiClient_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type ApiClient
func (_mock *ApiClient) Post(path string, query url.Values, body interface{}, headers http.Header) (*http.Response, errors.Error) {
	ret := _mock.Called(path, query, body, headers)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *http.Response
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, url.Values, interface{}, http.Header) (*http.Response, errors.Error)); ok {
		return returnFunc(path, query, body, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(string, url.Values, interface{}, http.Header) *http.Response); ok {
		r0 = returnFunc(path, query, body, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, url.Values, interface{}, http.Header) errors.Error); ok {
		r1 = returnFunc(path, query, body, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// ApiClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type ApiClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - path string
//   - query url.Values
//   - body interface{}
//   - headers http.Header
func (_e *ApiClient_Expecter) Post(path any, query any, body any, headers any) *ApiClient_Post_Call {
	return &ApiClient_Post_Call{Call: _e.mock.On("Post", path, query, body, headers)}
}

func (_c *ApiClient_Post_Call) Run(run func(path string, query url.Values, body interface{}, headers http.Header)) *ApiClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 http.Header
		if args[3] != nil {
			arg3 = args[3].(http.Header)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ApiClient_Post_Call) Return(response *http.Response, error errors.Error) *ApiClient_Post_Call {
	_c.Call.Return(response, error)
	return _c
}

func (_c *ApiClient_Post_Call) RunAndReturn(run func(path string, query url.Values, body interface{}, headers http.Header) (*http.Response, errors.Error)) *ApiClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// SetAfterFunction provides a mock function for the type ApiClient
func (_mock *ApiClient) SetAfterFunction(callback plugin.ApiClientAfterResponse) {
	_mock.Called(callback)
	return
}

// ApiClient_SetAfterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAfterFunction'
type ApiClient_SetAfterFunction_Call struct {
	*mock.Call
}

// SetAfterFunction is a helper method to define mock.On call
//   - callback plugin.ApiClientAfterResponse
func (_e *ApiClient_Expecter) SetAfterFunction(callback any) *ApiClient_SetAfterFunction_Call {
	return &ApiClient_SetAfterFunction_Call{Call: _e.mock.On("SetAfterFunction", callback)}
}

func (_c *ApiClient_SetAfterFunction_Call) Run(run func(callback plugin.ApiClientAfterResponse)) *ApiClient_SetAfterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.ApiClientAfterResponse
		if args[0] != nil {
			arg0 = args[0].(plugin.ApiClientAfterResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApiClient_SetAfterFunction_Call) Return() *ApiClient_SetAfterFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApiClient_SetAfterFunction_Call) RunAndReturn(run func(callback plugin.ApiClientAfterResponse)) *ApiClient_SetAfterFunction_Call {
	_c.Run(run)
	return _c
}

// SetBeforeFunction provides a mock function for the type ApiClient
func (_mock *ApiClient) SetBeforeFunction(callback plugin.ApiClientBeforeRequest) {
	_mock.Called(callback)
	return
}

// ApiClient_SetBeforeFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBeforeFunction'
type ApiClient_SetBeforeFunction_Call struct {
	*mock.Call
}

// SetBeforeFunction is a helper method to define mock.On call
//   - callback plugin.ApiClientBeforeRequest
func (_e *ApiClient_Expecter) SetBeforeFunction(callback any) *ApiClient_SetBeforeFunction_Call {
	return &ApiClient_SetBeforeFunction_Call{Call: _e.mock.On("SetBeforeFunction", callback)}
}

func (_c *ApiClient_SetBeforeFunction_Call) Run(run func(callback plugin.ApiClientBeforeRequest)) *ApiClient_SetBeforeFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.ApiClientBeforeRequest
		if args[0] != nil {
			arg0 = args[0].(plugin.ApiClientBeforeRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApiClient_SetBeforeFunction_Call) Return() *ApiClient_SetBeforeFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApiClient_SetBeforeFunction_Call) RunAndReturn(run func(callback plugin.ApiClientBeforeRequest)) *ApiClient_SetBeforeFunction_Call {
	_c.Run(run)
	return _c
}

// SetData provides a mock function for the type ApiClient
func (_mock *ApiClient) SetData(name string, data interface{}) {
	_mock.Called(name, data)
	return
}

// ApiClient_SetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetData'
type ApiClient_SetData_Call struct {
	*mock.Call
}

// SetData is a helper method to define mock.On call
//   - name string
//   - data interface{}
func (_e *ApiClient_Expecter) SetData(name any, data any) *ApiClient_SetData_Call {
	return &ApiClient_SetData_Call{Call: _e.mock.On("SetData", name, data)}
}

func (_c *ApiClient_SetData_Call) Run(run func(name string, data interface{})) *ApiClient_SetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApiClient_SetData_Call) Return() *ApiClient_SetData_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApiClient_SetData_Call) RunAndReturn(run func(name string, data interface{})) *ApiClient_SetData_Call {
	_c.Run(run)
	return _c
}

// SetHeaders provides a mock function for the type ApiClient
func (_mock *ApiClient) SetHeaders(headers map[string]string) {
	_mock.Called(headers)
	return
}

// ApiClient_SetHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaders'
type ApiClient_SetHeaders_Call struct {
	*mock.Call
}

// SetHeaders is a helper method to define mock.On call
//   - headers map[string]string
func (_e *ApiClient_Expecter) SetHeaders(headers any) *ApiClient_SetHeaders_Call {
	return &ApiClient_SetHeaders_Call{Call: _e.mock.On("SetHeaders", headers)}
}

func (_c *ApiClient_SetHeaders_Call) Run(run func(headers map[string]string)) *ApiClient_SetHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApiClient_SetHeaders_Call) Return() *ApiClient_SetHeaders_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApiClient_SetHeaders_Call) RunAndReturn(run func(headers map[string]string)) *ApiClient_SetHeaders_Call {
	_c.Run(run)
	return _c
}
