// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewApiGroup creates a new instance of ApiGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiGroup {
	mock := &ApiGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApiGroup is an autogenerated mock type for the ApiGroup type
type ApiGroup struct {
	mock.Mock
}

type ApiGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *ApiGroup) EXPECT() *ApiGroup_Expecter {
	return &ApiGroup_Expecter{mock: &_m.Mock}
}

// GroupId provides a mock function for the type ApiGroup
func (_mock *ApiGroup) GroupId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ApiGroup_GroupId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupId'
type ApiGroup_GroupId_Call struct {
	*mock.Call
}

// GroupId is a helper method to define mock.On call
func (_e *ApiGroup_Expecter) GroupId() *ApiGroup_GroupId_Call {
	return &ApiGroup_GroupId_Call{Call: _e.mock.On("GroupId")}
}

func (_c *ApiGroup_GroupId_Call) Run(run func()) *ApiGroup_GroupId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiGroup_GroupId_Call) Return(s string) *ApiGroup_GroupId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ApiGroup_GroupId_Call) RunAndReturn(run func() string) *ApiGroup_GroupId_Call {
	_c.Call.Return(run)
	return _c
}

// GroupName provides a mock function for the type ApiGroup
func (_mock *ApiGroup) GroupName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ApiGroup_GroupName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupName'
type ApiGroup_GroupName_Call struct {
	*mock.Call
}

// GroupName is a helper method to define mock.On call
func (_e *ApiGroup_Expecter) GroupName() *ApiGroup_GroupName_Call {
	return &ApiGroup_GroupName_Call{Call: _e.mock.On("GroupName")}
}

func (_c *ApiGroup_GroupName_Call) Run(run func()) *ApiGroup_GroupName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ApiGroup_GroupName_Call) Return(s string) *ApiGroup_GroupName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ApiGroup_GroupName_Call) RunAndReturn(run func() string) *ApiGroup_GroupName_Call {
	_c.Call.Return(run)
	return _c
}
