// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewBasicAuthenticator creates a new instance of BasicAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBasicAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *BasicAuthenticator {
	mock := &BasicAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BasicAuthenticator is an autogenerated mock type for the BasicAuthenticator type
type BasicAuthenticator struct {
	mock.Mock
}

type BasicAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *BasicAuthenticator) EXPECT() *BasicAuthenticator_Expecter {
	return &BasicAuthenticator_Expecter{mock: &_m.Mock}
}

// GetBasicAuthenticator provides a mock function for the type BasicAuthenticator
func (_mock *BasicAuthenticator) GetBasicAuthenticator() plugin.ApiAuthenticator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBasicAuthenticator")
	}

	var r0 plugin.ApiAuthenticator
	if returnFunc, ok := ret.Get(0).(func() plugin.ApiAuthenticator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ApiAuthenticator)
		}
	}
	return r0
}

// BasicAuthenticator_GetBasicAuthenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBasicAuthenticator'
type BasicAuthenticator_GetBasicAuthenticator_Call struct {
	*mock.Call
}

// GetBasicAuthenticator is a helper method to define mock.On call
func (_e *BasicAuthenticator_Expecter) GetBasicAuthenticator() *BasicAuthenticator_GetBasicAuthenticator_Call {
	return &BasicAuthenticator_GetBasicAuthenticator_Call{Call: _e.mock.On("GetBasicAuthenticator")}
}

func (_c *BasicAuthenticator_GetBasicAuthenticator_Call) Run(run func()) *BasicAuthenticator_GetBasicAuthenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BasicAuthenticator_GetBasicAuthenticator_Call) Return(apiAuthenticator plugin.ApiAuthenticator) *BasicAuthenticator_GetBasicAuthenticator_Call {
	_c.Call.Return(apiAuthenticator)
	return _c
}

func (_c *BasicAuthenticator_GetBasicAuthenticator_Call) RunAndReturn(run func() plugin.ApiAuthenticator) *BasicAuthenticator_GetBasicAuthenticator_Call {
	_c.Call.Return(run)
	return _c
}
