// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCacheableConnection creates a new instance of CacheableConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheableConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheableConnection {
	mock := &CacheableConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheableConnection is an autogenerated mock type for the CacheableConnection type
type CacheableConnection struct {
	mock.Mock
}

type CacheableConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheableConnection) EXPECT() *CacheableConnection_Expecter {
	return &CacheableConnection_Expecter{mock: &_m.Mock}
}

// GetEndpoint provides a mock function for the type CacheableConnection
func (_mock *CacheableConnection) GetEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CacheableConnection_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type CacheableConnection_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
func (_e *CacheableConnection_Expecter) GetEndpoint() *CacheableConnection_GetEndpoint_Call {
	return &CacheableConnection_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint")}
}

func (_c *CacheableConnection_GetEndpoint_Call) Run(run func()) *CacheableConnection_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheableConnection_GetEndpoint_Call) Return(s string) *CacheableConnection_GetEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CacheableConnection_GetEndpoint_Call) RunAndReturn(run func() string) *CacheableConnection_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetHash provides a mock function for the type CacheableConnection
func (_mock *CacheableConnection) GetHash() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHash")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CacheableConnection_GetHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHash'
type CacheableConnection_GetHash_Call struct {
	*mock.Call
}

// GetHash is a helper method to define mock.On call
func (_e *CacheableConnection_Expecter) GetHash() *CacheableConnection_GetHash_Call {
	return &CacheableConnection_GetHash_Call{Call: _e.mock.On("GetHash")}
}

func (_c *CacheableConnection_GetHash_Call) Run(run func()) *CacheableConnection_GetHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheableConnection_GetHash_Call) Return(s string) *CacheableConnection_GetHash_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CacheableConnection_GetHash_Call) RunAndReturn(run func() string) *CacheableConnection_GetHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetProxy provides a mock function for the type CacheableConnection
func (_mock *CacheableConnection) GetProxy() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProxy")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CacheableConnection_GetProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProxy'
type CacheableConnection_GetProxy_Call struct {
	*mock.Call
}

// GetProxy is a helper method to define mock.On call
func (_e *CacheableConnection_Expecter) GetProxy() *CacheableConnection_GetProxy_Call {
	return &CacheableConnection_GetProxy_Call{Call: _e.mock.On("GetProxy")}
}

func (_c *CacheableConnection_GetProxy_Call) Run(run func()) *CacheableConnection_GetProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheableConnection_GetProxy_Call) Return(s string) *CacheableConnection_GetProxy_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CacheableConnection_GetProxy_Call) RunAndReturn(run func() string) *CacheableConnection_GetProxy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimitPerHour provides a mock function for the type CacheableConnection
func (_mock *CacheableConnection) GetRateLimitPerHour() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimitPerHour")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// CacheableConnection_GetRateLimitPerHour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimitPerHour'
type CacheableConnection_GetRateLimitPerHour_Call struct {
	*mock.Call
}

// GetRateLimitPerHour is a helper method to define mock.On call
func (_e *CacheableConnection_Expecter) GetRateLimitPerHour() *CacheableConnection_GetRateLimitPerHour_Call {
	return &CacheableConnection_GetRateLimitPerHour_Call{Call: _e.mock.On("GetRateLimitPerHour")}
}

func (_c *CacheableConnection_GetRateLimitPerHour_Call) Run(run func()) *CacheableConnection_GetRateLimitPerHour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheableConnection_GetRateLimitPerHour_Call) Return(n int) *CacheableConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *CacheableConnection_GetRateLimitPerHour_Call) RunAndReturn(run func() int) *CacheableConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(run)
	return _c
}
