// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"encoding/json"

	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCompositeMetricPluginBlueprintV200 creates a new instance of CompositeMetricPluginBlueprintV200. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompositeMetricPluginBlueprintV200(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompositeMetricPluginBlueprintV200 {
	mock := &CompositeMetricPluginBlueprintV200{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompositeMetricPluginBlueprintV200 is an autogenerated mock type for the CompositeMetricPluginBlueprintV200 type
type CompositeMetricPluginBlueprintV200 struct {
	mock.Mock
}

type CompositeMetricPluginBlueprintV200_Expecter struct {
	mock *mock.Mock
}

func (_m *CompositeMetricPluginBlueprintV200) EXPECT() *CompositeMetricPluginBlueprintV200_Expecter {
	return &CompositeMetricPluginBlueprintV200_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type CompositeMetricPluginBlueprintV200
func (_mock *CompositeMetricPluginBlueprintV200) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeMetricPluginBlueprintV200_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type CompositeMetricPluginBlueprintV200_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *CompositeMetricPluginBlueprintV200_Expecter) Description() *CompositeMetricPluginBlueprintV200_Description_Call {
	return &CompositeMetricPluginBlueprintV200_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *CompositeMetricPluginBlueprintV200_Description_Call) Run(run func()) *CompositeMetricPluginBlueprintV200_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_Description_Call) Return(s string) *CompositeMetricPluginBlueprintV200_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_Description_Call) RunAndReturn(run func() string) *CompositeMetricPluginBlueprintV200_Description_Call {
	_c.Call.Return(run)
	return _c
}

// MakeMetricPluginPipelinePlanV200 provides a mock function for the type CompositeMetricPluginBlueprintV200
func (_mock *CompositeMetricPluginBlueprintV200) MakeMetricPluginPipelinePlanV200(projectName string, options json.RawMessage) (models.PipelinePlan, errors.Error) {
	ret := _mock.Called(projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for MakeMetricPluginPipelinePlanV200")
	}

	var r0 models.PipelinePlan
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) (models.PipelinePlan, errors.Error)); ok {
		return returnFunc(projectName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) models.PipelinePlan); ok {
		r0 = returnFunc(projectName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PipelinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage) errors.Error); ok {
		r1 = returnFunc(projectName, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeMetricPluginPipelinePlanV200'
type CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call struct {
	*mock.Call
}

// MakeMetricPluginPipelinePlanV200 is a helper method to define mock.On call
//   - projectName string
//   - options json.RawMessage
func (_e *CompositeMetricPluginBlueprintV200_Expecter) MakeMetricPluginPipelinePlanV200(projectName any, options any) *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	return &CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call{Call: _e.mock.On("MakeMetricPluginPipelinePlanV200", projectName, options)}
}

func (_c *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) Run(run func(projectName string, options json.RawMessage)) *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) Return(pipelinePlan models.PipelinePlan, error errors.Error) *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Return(pipelinePlan, error)
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) RunAndReturn(run func(projectName string, options json.RawMessage) (models.PipelinePlan, errors.Error)) *CompositeMetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type CompositeMetricPluginBlueprintV200
func (_mock *CompositeMetricPluginBlueprintV200) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeMetricPluginBlueprintV200_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type CompositeMetricPluginBlueprintV200_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *CompositeMetricPluginBlueprintV200_Expecter) Name() *CompositeMetricPluginBlueprintV200_Name_Call {
	return &CompositeMetricPluginBlueprintV200_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *CompositeMetricPluginBlueprintV200_Name_Call) Run(run func()) *CompositeMetricPluginBlueprintV200_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_Name_Call) Return(s string) *CompositeMetricPluginBlueprintV200_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_Name_Call) RunAndReturn(run func() string) *CompositeMetricPluginBlueprintV200_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RootPkgPath provides a mock function for the type CompositeMetricPluginBlueprintV200
func (_mock *CompositeMetricPluginBlueprintV200) RootPkgPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootPkgPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeMetricPluginBlueprintV200_RootPkgPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootPkgPath'
type CompositeMetricPluginBlueprintV200_RootPkgPath_Call struct {
	*mock.Call
}

// RootPkgPath is a helper method to define mock.On call
func (_e *CompositeMetricPluginBlueprintV200_Expecter) RootPkgPath() *CompositeMetricPluginBlueprintV200_RootPkgPath_Call {
	return &CompositeMetricPluginBlueprintV200_RootPkgPath_Call{Call: _e.mock.On("RootPkgPath")}
}

func (_c *CompositeMetricPluginBlueprintV200_RootPkgPath_Call) Run(run func()) *CompositeMetricPluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_RootPkgPath_Call) Return(s string) *CompositeMetricPluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeMetricPluginBlueprintV200_RootPkgPath_Call) RunAndReturn(run func() string) *CompositeMetricPluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Return(run)
	return _c
}
