// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewCompositeProjectMapper creates a new instance of CompositeProjectMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompositeProjectMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompositeProjectMapper {
	mock := &CompositeProjectMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompositeProjectMapper is an autogenerated mock type for the CompositeProjectMapper type
type CompositeProjectMapper struct {
	mock.Mock
}

type CompositeProjectMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *CompositeProjectMapper) EXPECT() *CompositeProjectMapper_Expecter {
	return &CompositeProjectMapper_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type CompositeProjectMapper
func (_mock *CompositeProjectMapper) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeProjectMapper_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type CompositeProjectMapper_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *CompositeProjectMapper_Expecter) Description() *CompositeProjectMapper_Description_Call {
	return &CompositeProjectMapper_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *CompositeProjectMapper_Description_Call) Run(run func()) *CompositeProjectMapper_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeProjectMapper_Description_Call) Return(s string) *CompositeProjectMapper_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeProjectMapper_Description_Call) RunAndReturn(run func() string) *CompositeProjectMapper_Description_Call {
	_c.Call.Return(run)
	return _c
}

// MapProject provides a mock function for the type CompositeProjectMapper
func (_mock *CompositeProjectMapper) MapProject(projectName string, scopes []plugin.Scope) (models.PipelinePlan, errors.Error) {
	ret := _mock.Called(projectName, scopes)

	if len(ret) == 0 {
		panic("no return value specified for MapProject")
	}

	var r0 models.PipelinePlan
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, []plugin.Scope) (models.PipelinePlan, errors.Error)); ok {
		return returnFunc(projectName, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []plugin.Scope) models.PipelinePlan); ok {
		r0 = returnFunc(projectName, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PipelinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []plugin.Scope) errors.Error); ok {
		r1 = returnFunc(projectName, scopes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// CompositeProjectMapper_MapProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapProject'
type CompositeProjectMapper_MapProject_Call struct {
	*mock.Call
}

// MapProject is a helper method to define mock.On call
//   - projectName string
//   - scopes []plugin.Scope
func (_e *CompositeProjectMapper_Expecter) MapProject(projectName any, scopes any) *CompositeProjectMapper_MapProject_Call {
	return &CompositeProjectMapper_MapProject_Call{Call: _e.mock.On("MapProject", projectName, scopes)}
}

func (_c *CompositeProjectMapper_MapProject_Call) Run(run func(projectName string, scopes []plugin.Scope)) *CompositeProjectMapper_MapProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []plugin.Scope
		if args[1] != nil {
			arg1 = args[1].([]plugin.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompositeProjectMapper_MapProject_Call) Return(pipelinePlan models.PipelinePlan, error errors.Error) *CompositeProjectMapper_MapProject_Call {
	_c.Call.Return(pipelinePlan, error)
	return _c
}

func (_c *CompositeProjectMapper_MapProject_Call) RunAndReturn(run func(projectName string, scopes []plugin.Scope) (models.PipelinePlan, errors.Error)) *CompositeProjectMapper_MapProject_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type CompositeProjectMapper
func (_mock *CompositeProjectMapper) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeProjectMapper_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type CompositeProjectMapper_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *CompositeProjectMapper_Expecter) Name() *CompositeProjectMapper_Name_Call {
	return &CompositeProjectMapper_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *CompositeProjectMapper_Name_Call) Run(run func()) *CompositeProjectMapper_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeProjectMapper_Name_Call) Return(s string) *CompositeProjectMapper_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeProjectMapper_Name_Call) RunAndReturn(run func() string) *CompositeProjectMapper_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RootPkgPath provides a mock function for the type CompositeProjectMapper
func (_mock *CompositeProjectMapper) RootPkgPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootPkgPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeProjectMapper_RootPkgPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootPkgPath'
type CompositeProjectMapper_RootPkgPath_Call struct {
	*mock.Call
}

// RootPkgPath is a helper method to define mock.On call
func (_e *CompositeProjectMapper_Expecter) RootPkgPath() *CompositeProjectMapper_RootPkgPath_Call {
	return &CompositeProjectMapper_RootPkgPath_Call{Call: _e.mock.On("RootPkgPath")}
}

func (_c *CompositeProjectMapper_RootPkgPath_Call) Run(run func()) *CompositeProjectMapper_RootPkgPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeProjectMapper_RootPkgPath_Call) Return(s string) *CompositeProjectMapper_RootPkgPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeProjectMapper_RootPkgPath_Call) RunAndReturn(run func() string) *CompositeProjectMapper_RootPkgPath_Call {
	_c.Call.Return(run)
	return _c
}
