// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewCompositeDataSourcePluginBlueprintV200 creates a new instance of CompositeDataSourcePluginBlueprintV200. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompositeDataSourcePluginBlueprintV200(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompositeDataSourcePluginBlueprintV200 {
	mock := &CompositeDataSourcePluginBlueprintV200{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompositeDataSourcePluginBlueprintV200 is an autogenerated mock type for the CompositeDataSourcePluginBlueprintV200 type
type CompositeDataSourcePluginBlueprintV200 struct {
	mock.Mock
}

type CompositeDataSourcePluginBlueprintV200_Expecter struct {
	mock *mock.Mock
}

func (_m *CompositeDataSourcePluginBlueprintV200) EXPECT() *CompositeDataSourcePluginBlueprintV200_Expecter {
	return &CompositeDataSourcePluginBlueprintV200_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type CompositeDataSourcePluginBlueprintV200
func (_mock *CompositeDataSourcePluginBlueprintV200) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeDataSourcePluginBlueprintV200_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type CompositeDataSourcePluginBlueprintV200_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *CompositeDataSourcePluginBlueprintV200_Expecter) Description() *CompositeDataSourcePluginBlueprintV200_Description_Call {
	return &CompositeDataSourcePluginBlueprintV200_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *CompositeDataSourcePluginBlueprintV200_Description_Call) Run(run func()) *CompositeDataSourcePluginBlueprintV200_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_Description_Call) Return(s string) *CompositeDataSourcePluginBlueprintV200_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_Description_Call) RunAndReturn(run func() string) *CompositeDataSourcePluginBlueprintV200_Description_Call {
	_c.Call.Return(run)
	return _c
}

// MakeDataSourcePipelinePlanV200 provides a mock function for the type CompositeDataSourcePluginBlueprintV200
func (_mock *CompositeDataSourcePluginBlueprintV200) MakeDataSourcePipelinePlanV200(connectionId uint64, scopes []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error) {
	ret := _mock.Called(connectionId, scopes)

	if len(ret) == 0 {
		panic("no return value specified for MakeDataSourcePipelinePlanV200")
	}

	var r0 models.PipelinePlan
	var r1 []plugin.Scope
	var r2 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64, []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error)); ok {
		return returnFunc(connectionId, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, []*models.BlueprintScope) models.PipelinePlan); ok {
		r0 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PipelinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, []*models.BlueprintScope) []plugin.Scope); ok {
		r1 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]plugin.Scope)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, []*models.BlueprintScope) errors.Error); ok {
		r2 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(errors.Error)
		}
	}
	return r0, r1, r2
}

// CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeDataSourcePipelinePlanV200'
type CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call struct {
	*mock.Call
}

// MakeDataSourcePipelinePlanV200 is a helper method to define mock.On call
//   - connectionId uint64
//   - scopes []*models.BlueprintScope
func (_e *CompositeDataSourcePluginBlueprintV200_Expecter) MakeDataSourcePipelinePlanV200(connectionId any, scopes any) *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	return &CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call{Call: _e.mock.On("MakeDataSourcePipelinePlanV200", connectionId, scopes)}
}

func (_c *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) Run(run func(connectionId uint64, scopes []*models.BlueprintScope)) *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 []*models.BlueprintScope
		if args[1] != nil {
			arg1 = args[1].([]*models.BlueprintScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) Return(pipelinePlan models.PipelinePlan, scopes1 []plugin.Scope, error errors.Error) *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Return(pipelinePlan, scopes1, error)
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) RunAndReturn(run func(connectionId uint64, scopes []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error)) *CompositeDataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type CompositeDataSourcePluginBlueprintV200
func (_mock *CompositeDataSourcePluginBlueprintV200) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeDataSourcePluginBlueprintV200_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type CompositeDataSourcePluginBlueprintV200_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *CompositeDataSourcePluginBlueprintV200_Expecter) Name() *CompositeDataSourcePluginBlueprintV200_Name_Call {
	return &CompositeDataSourcePluginBlueprintV200_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *CompositeDataSourcePluginBlueprintV200_Name_Call) Run(run func()) *CompositeDataSourcePluginBlueprintV200_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_Name_Call) Return(s string) *CompositeDataSourcePluginBlueprintV200_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_Name_Call) RunAndReturn(run func() string) *CompositeDataSourcePluginBlueprintV200_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RootPkgPath provides a mock function for the type CompositeDataSourcePluginBlueprintV200
func (_mock *CompositeDataSourcePluginBlueprintV200) RootPkgPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootPkgPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootPkgPath'
type CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call struct {
	*mock.Call
}

// RootPkgPath is a helper method to define mock.On call
func (_e *CompositeDataSourcePluginBlueprintV200_Expecter) RootPkgPath() *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call {
	return &CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call{Call: _e.mock.On("RootPkgPath")}
}

func (_c *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call) Run(run func()) *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call) Return(s string) *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call) RunAndReturn(run func() string) *CompositeDataSourcePluginBlueprintV200_RootPkgPath_Call {
	_c.Call.Return(run)
	return _c
}
