// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewConnectionValidator creates a new instance of ConnectionValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionValidator {
	mock := &ConnectionValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConnectionValidator is an autogenerated mock type for the ConnectionValidator type
type ConnectionValidator struct {
	mock.Mock
}

type ConnectionValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionValidator) EXPECT() *ConnectionValidator_Expecter {
	return &ConnectionValidator_Expecter{mock: &_m.Mock}
}

// ValidateConnection provides a mock function for the type ConnectionValidator
func (_mock *ConnectionValidator) ValidateConnection(connection interface{}, validator1 *validator.Validate) errors.Error {
	ret := _mock.Called(connection, validator1)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConnection")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *validator.Validate) errors.Error); ok {
		r0 = returnFunc(connection, validator1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// ConnectionValidator_ValidateConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConnection'
type ConnectionValidator_ValidateConnection_Call struct {
	*mock.Call
}

// ValidateConnection is a helper method to define mock.On call
//   - connection interface{}
//   - validator1 *validator.Validate
func (_e *ConnectionValidator_Expecter) ValidateConnection(connection any, validator1 any) *ConnectionValidator_ValidateConnection_Call {
	return &ConnectionValidator_ValidateConnection_Call{Call: _e.mock.On("ValidateConnection", connection, validator1)}
}

func (_c *ConnectionValidator_ValidateConnection_Call) Run(run func(connection interface{}, validator1 *validator.Validate)) *ConnectionValidator_ValidateConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *validator.Validate
		if args[1] != nil {
			arg1 = args[1].(*validator.Validate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionValidator_ValidateConnection_Call) Return(error errors.Error) *ConnectionValidator_ValidateConnection_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *ConnectionValidator_ValidateConnection_Call) RunAndReturn(run func(connection interface{}, validator1 *validator.Validate) errors.Error) *ConnectionValidator_ValidateConnection_Call {
	_c.Call.Return(run)
	return _c
}
