// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewDataSourcePluginBlueprintV200 creates a new instance of DataSourcePluginBlueprintV200. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataSourcePluginBlueprintV200(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataSourcePluginBlueprintV200 {
	mock := &DataSourcePluginBlueprintV200{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataSourcePluginBlueprintV200 is an autogenerated mock type for the DataSourcePluginBlueprintV200 type
type DataSourcePluginBlueprintV200 struct {
	mock.Mock
}

type DataSourcePluginBlueprintV200_Expecter struct {
	mock *mock.Mock
}

func (_m *DataSourcePluginBlueprintV200) EXPECT() *DataSourcePluginBlueprintV200_Expecter {
	return &DataSourcePluginBlueprintV200_Expecter{mock: &_m.Mock}
}

// MakeDataSourcePipelinePlanV200 provides a mock function for the type DataSourcePluginBlueprintV200
func (_mock *DataSourcePluginBlueprintV200) MakeDataSourcePipelinePlanV200(connectionId uint64, scopes []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error) {
	ret := _mock.Called(connectionId, scopes)

	if len(ret) == 0 {
		panic("no return value specified for MakeDataSourcePipelinePlanV200")
	}

	var r0 models.PipelinePlan
	var r1 []plugin.Scope
	var r2 errors.Error
	if returnFunc, ok := ret.Get(0).(func(uint64, []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error)); ok {
		return returnFunc(connectionId, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, []*models.BlueprintScope) models.PipelinePlan); ok {
		r0 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PipelinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, []*models.BlueprintScope) []plugin.Scope); ok {
		r1 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]plugin.Scope)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, []*models.BlueprintScope) errors.Error); ok {
		r2 = returnFunc(connectionId, scopes)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(errors.Error)
		}
	}
	return r0, r1, r2
}

// DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeDataSourcePipelinePlanV200'
type DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call struct {
	*mock.Call
}

// MakeDataSourcePipelinePlanV200 is a helper method to define mock.On call
//   - connectionId uint64
//   - scopes []*models.BlueprintScope
func (_e *DataSourcePluginBlueprintV200_Expecter) MakeDataSourcePipelinePlanV200(connectionId any, scopes any) *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	return &DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call{Call: _e.mock.On("MakeDataSourcePipelinePlanV200", connectionId, scopes)}
}

func (_c *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) Run(run func(connectionId uint64, scopes []*models.BlueprintScope)) *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 []*models.BlueprintScope
		if args[1] != nil {
			arg1 = args[1].([]*models.BlueprintScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) Return(pipelinePlan models.PipelinePlan, scopes1 []plugin.Scope, error errors.Error) *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Return(pipelinePlan, scopes1, error)
	return _c
}

func (_c *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call) RunAndReturn(run func(connectionId uint64, scopes []*models.BlueprintScope) (models.PipelinePlan, []plugin.Scope, errors.Error)) *DataSourcePluginBlueprintV200_MakeDataSourcePipelinePlanV200_Call {
	_c.Call.Return(run)
	return _c
}
