// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"encoding/json"

	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMetricPluginBlueprintV200 creates a new instance of MetricPluginBlueprintV200. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricPluginBlueprintV200(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricPluginBlueprintV200 {
	mock := &MetricPluginBlueprintV200{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetricPluginBlueprintV200 is an autogenerated mock type for the MetricPluginBlueprintV200 type
type MetricPluginBlueprintV200 struct {
	mock.Mock
}

type MetricPluginBlueprintV200_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricPluginBlueprintV200) EXPECT() *MetricPluginBlueprintV200_Expecter {
	return &MetricPluginBlueprintV200_Expecter{mock: &_m.Mock}
}

// MakeMetricPluginPipelinePlanV200 provides a mock function for the type MetricPluginBlueprintV200
func (_mock *MetricPluginBlueprintV200) MakeMetricPluginPipelinePlanV200(projectName string, options json.RawMessage) (models.PipelinePlan, errors.Error) {
	ret := _mock.Called(projectName, options)

	if len(ret) == 0 {
		panic("no return value specified for MakeMetricPluginPipelinePlanV200")
	}

	var r0 models.PipelinePlan
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) (models.PipelinePlan, errors.Error)); ok {
		return returnFunc(projectName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) models.PipelinePlan); ok {
		r0 = returnFunc(projectName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.PipelinePlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage) errors.Error); ok {
		r1 = returnFunc(projectName, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeMetricPluginPipelinePlanV200'
type MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call struct {
	*mock.Call
}

// MakeMetricPluginPipelinePlanV200 is a helper method to define mock.On call
//   - projectName string
//   - options json.RawMessage
func (_e *MetricPluginBlueprintV200_Expecter) MakeMetricPluginPipelinePlanV200(projectName any, options any) *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	return &MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call{Call: _e.mock.On("MakeMetricPluginPipelinePlanV200", projectName, options)}
}

func (_c *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) Run(run func(projectName string, options json.RawMessage)) *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) Return(pipelinePlan models.PipelinePlan, error errors.Error) *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Return(pipelinePlan, error)
	return _c
}

func (_c *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call) RunAndReturn(run func(projectName string, options json.RawMessage) (models.PipelinePlan, errors.Error)) *MetricPluginBlueprintV200_MakeMetricPluginPipelinePlanV200_Call {
	_c.Call.Return(run)
	return _c
}
