// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewMigrator creates a new instance of Migrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Migrator {
	mock := &Migrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Migrator is an autogenerated mock type for the Migrator type
type Migrator struct {
	mock.Mock
}

type Migrator_Expecter struct {
	mock *mock.Mock
}

func (_m *Migrator) EXPECT() *Migrator_Expecter {
	return &Migrator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type Migrator
func (_mock *Migrator) Execute() errors.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func() errors.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// Migrator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Migrator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *Migrator_Expecter) Execute() *Migrator_Execute_Call {
	return &Migrator_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *Migrator_Execute_Call) Run(run func()) *Migrator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Migrator_Execute_Call) Return(error errors.Error) *Migrator_Execute_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *Migrator_Execute_Call) RunAndReturn(run func() errors.Error) *Migrator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// HasPendingScripts provides a mock function for the type Migrator
func (_mock *Migrator) HasPendingScripts() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasPendingScripts")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Migrator_HasPendingScripts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPendingScripts'
type Migrator_HasPendingScripts_Call struct {
	*mock.Call
}

// HasPendingScripts is a helper method to define mock.On call
func (_e *Migrator_Expecter) HasPendingScripts() *Migrator_HasPendingScripts_Call {
	return &Migrator_HasPendingScripts_Call{Call: _e.mock.On("HasPendingScripts")}
}

func (_c *Migrator_HasPendingScripts_Call) Run(run func()) *Migrator_HasPendingScripts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Migrator_HasPendingScripts_Call) Return(b bool) *Migrator_HasPendingScripts_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Migrator_HasPendingScripts_Call) RunAndReturn(run func() bool) *Migrator_HasPendingScripts_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Migrator
func (_mock *Migrator) Register(scripts []plugin.MigrationScript, comment string) {
	_mock.Called(scripts, comment)
	return
}

// Migrator_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Migrator_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - scripts []plugin.MigrationScript
//   - comment string
func (_e *Migrator_Expecter) Register(scripts any, comment any) *Migrator_Register_Call {
	return &Migrator_Register_Call{Call: _e.mock.On("Register", scripts, comment)}
}

func (_c *Migrator_Register_Call) Run(run func(scripts []plugin.MigrationScript, comment string)) *Migrator_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []plugin.MigrationScript
		if args[0] != nil {
			arg0 = args[0].([]plugin.MigrationScript)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Migrator_Register_Call) Return() *Migrator_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Migrator_Register_Call) RunAndReturn(run func(scripts []plugin.MigrationScript, comment string)) *Migrator_Register_Call {
	_c.Run(run)
	return _c
}
