// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/context"
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewMigrationScript creates a new instance of MigrationScript. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMigrationScript(t interface {
	mock.TestingT
	Cleanup(func())
}) *MigrationScript {
	mock := &MigrationScript{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MigrationScript is an autogenerated mock type for the MigrationScript type
type MigrationScript struct {
	mock.Mock
}

type MigrationScript_Expecter struct {
	mock *mock.Mock
}

func (_m *MigrationScript) EXPECT() *MigrationScript_Expecter {
	return &MigrationScript_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MigrationScript
func (_mock *MigrationScript) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MigrationScript_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MigrationScript_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MigrationScript_Expecter) Name() *MigrationScript_Name_Call {
	return &MigrationScript_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MigrationScript_Name_Call) Run(run func()) *MigrationScript_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MigrationScript_Name_Call) Return(s string) *MigrationScript_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MigrationScript_Name_Call) RunAndReturn(run func() string) *MigrationScript_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MigrationScript
func (_mock *MigrationScript) Up(basicRes context.BasicRes) errors.Error {
	ret := _mock.Called(basicRes)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(context.BasicRes) errors.Error); ok {
		r0 = returnFunc(basicRes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// MigrationScript_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MigrationScript_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - basicRes context.BasicRes
func (_e *MigrationScript_Expecter) Up(basicRes any) *MigrationScript_Up_Call {
	return &MigrationScript_Up_Call{Call: _e.mock.On("Up", basicRes)}
}

func (_c *MigrationScript_Up_Call) Run(run func(basicRes context.BasicRes)) *MigrationScript_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.BasicRes
		if args[0] != nil {
			arg0 = args[0].(context.BasicRes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MigrationScript_Up_Call) Return(error errors.Error) *MigrationScript_Up_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MigrationScript_Up_Call) RunAndReturn(run func(basicRes context.BasicRes) errors.Error) *MigrationScript_Up_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MigrationScript
func (_mock *MigrationScript) Version() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// MigrationScript_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MigrationScript_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MigrationScript_Expecter) Version() *MigrationScript_Version_Call {
	return &MigrationScript_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MigrationScript_Version_Call) Run(run func()) *MigrationScript_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MigrationScript_Version_Call) Return(v uint64) *MigrationScript_Version_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MigrationScript_Version_Call) RunAndReturn(run func() uint64) *MigrationScript_Version_Call {
	_c.Call.Return(run)
	return _c
}
