// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMultiAuthenticator creates a new instance of MultiAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultiAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultiAuthenticator {
	mock := &MultiAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MultiAuthenticator is an autogenerated mock type for the MultiAuthenticator type
type MultiAuthenticator struct {
	mock.Mock
}

type MultiAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MultiAuthenticator) EXPECT() *MultiAuthenticator_Expecter {
	return &MultiAuthenticator_Expecter{mock: &_m.Mock}
}

// GetAuthMethod provides a mock function for the type MultiAuthenticator
func (_mock *MultiAuthenticator) GetAuthMethod() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthMethod")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MultiAuthenticator_GetAuthMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthMethod'
type MultiAuthenticator_GetAuthMethod_Call struct {
	*mock.Call
}

// GetAuthMethod is a helper method to define mock.On call
func (_e *MultiAuthenticator_Expecter) GetAuthMethod() *MultiAuthenticator_GetAuthMethod_Call {
	return &MultiAuthenticator_GetAuthMethod_Call{Call: _e.mock.On("GetAuthMethod")}
}

func (_c *MultiAuthenticator_GetAuthMethod_Call) Run(run func()) *MultiAuthenticator_GetAuthMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MultiAuthenticator_GetAuthMethod_Call) Return(s string) *MultiAuthenticator_GetAuthMethod_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MultiAuthenticator_GetAuthMethod_Call) RunAndReturn(run func() string) *MultiAuthenticator_GetAuthMethod_Call {
	_c.Call.Return(run)
	return _c
}
