// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPluginOpenApiSpec creates a new instance of PluginOpenApiSpec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginOpenApiSpec(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginOpenApiSpec {
	mock := &PluginOpenApiSpec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginOpenApiSpec is an autogenerated mock type for the PluginOpenApiSpec type
type PluginOpenApiSpec struct {
	mock.Mock
}

type PluginOpenApiSpec_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginOpenApiSpec) EXPECT() *PluginOpenApiSpec_Expecter {
	return &PluginOpenApiSpec_Expecter{mock: &_m.Mock}
}

// OpenApiSpec provides a mock function for the type PluginOpenApiSpec
func (_mock *PluginOpenApiSpec) OpenApiSpec() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenApiSpec")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PluginOpenApiSpec_OpenApiSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenApiSpec'
type PluginOpenApiSpec_OpenApiSpec_Call struct {
	*mock.Call
}

// OpenApiSpec is a helper method to define mock.On call
func (_e *PluginOpenApiSpec_Expecter) OpenApiSpec() *PluginOpenApiSpec_OpenApiSpec_Call {
	return &PluginOpenApiSpec_OpenApiSpec_Call{Call: _e.mock.On("OpenApiSpec")}
}

func (_c *PluginOpenApiSpec_OpenApiSpec_Call) Run(run func()) *PluginOpenApiSpec_OpenApiSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginOpenApiSpec_OpenApiSpec_Call) Return(s string) *PluginOpenApiSpec_OpenApiSpec_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PluginOpenApiSpec_OpenApiSpec_Call) RunAndReturn(run func() string) *PluginOpenApiSpec_OpenApiSpec_Call {
	_c.Call.Return(run)
	return _c
}
