// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/context"
	"github.com/apache/devlake/core/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginInit creates a new instance of PluginInit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginInit(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginInit {
	mock := &PluginInit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginInit is an autogenerated mock type for the PluginInit type
type PluginInit struct {
	mock.Mock
}

type PluginInit_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginInit) EXPECT() *PluginInit_Expecter {
	return &PluginInit_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type PluginInit
func (_mock *PluginInit) Init(basicRes context.BasicRes) errors.Error {
	ret := _mock.Called(basicRes)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(context.BasicRes) errors.Error); ok {
		r0 = returnFunc(basicRes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// PluginInit_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type PluginInit_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - basicRes context.BasicRes
func (_e *PluginInit_Expecter) Init(basicRes any) *PluginInit_Init_Call {
	return &PluginInit_Init_Call{Call: _e.mock.On("Init", basicRes)}
}

func (_c *PluginInit_Init_Call) Run(run func(basicRes context.BasicRes)) *PluginInit_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.BasicRes
		if args[0] != nil {
			arg0 = args[0].(context.BasicRes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PluginInit_Init_Call) Return(error errors.Error) *PluginInit_Init_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *PluginInit_Init_Call) RunAndReturn(run func(basicRes context.BasicRes) errors.Error) *PluginInit_Init_Call {
	_c.Call.Return(run)
	return _c
}
