// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginMigration creates a new instance of PluginMigration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginMigration(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginMigration {
	mock := &PluginMigration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginMigration is an autogenerated mock type for the PluginMigration type
type PluginMigration struct {
	mock.Mock
}

type PluginMigration_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginMigration) EXPECT() *PluginMigration_Expecter {
	return &PluginMigration_Expecter{mock: &_m.Mock}
}

// MigrationScripts provides a mock function for the type PluginMigration
func (_mock *PluginMigration) MigrationScripts() []plugin.MigrationScript {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationScripts")
	}

	var r0 []plugin.MigrationScript
	if returnFunc, ok := ret.Get(0).(func() []plugin.MigrationScript); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.MigrationScript)
		}
	}
	return r0
}

// PluginMigration_MigrationScripts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationScripts'
type PluginMigration_MigrationScripts_Call struct {
	*mock.Call
}

// MigrationScripts is a helper method to define mock.On call
func (_e *PluginMigration_Expecter) MigrationScripts() *PluginMigration_MigrationScripts_Call {
	return &PluginMigration_MigrationScripts_Call{Call: _e.mock.On("MigrationScripts")}
}

func (_c *PluginMigration_MigrationScripts_Call) Run(run func()) *PluginMigration_MigrationScripts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginMigration_MigrationScripts_Call) Return(migrationScripts []plugin.MigrationScript) *PluginMigration_MigrationScripts_Call {
	_c.Call.Return(migrationScripts)
	return _c
}

func (_c *PluginMigration_MigrationScripts_Call) RunAndReturn(run func() []plugin.MigrationScript) *PluginMigration_MigrationScripts_Call {
	_c.Call.Return(run)
	return _c
}
