// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginTask creates a new instance of PluginTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginTask {
	mock := &PluginTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginTask is an autogenerated mock type for the PluginTask type
type PluginTask struct {
	mock.Mock
}

type PluginTask_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginTask) EXPECT() *PluginTask_Expecter {
	return &PluginTask_Expecter{mock: &_m.Mock}
}

// PrepareTaskData provides a mock function for the type PluginTask
func (_mock *PluginTask) PrepareTaskData(taskCtx plugin.TaskContext, options map[string]interface{}) (interface{}, errors.Error) {
	ret := _mock.Called(taskCtx, options)

	if len(ret) == 0 {
		panic("no return value specified for PrepareTaskData")
	}

	var r0 interface{}
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(plugin.TaskContext, map[string]interface{}) (interface{}, errors.Error)); ok {
		return returnFunc(taskCtx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(plugin.TaskContext, map[string]interface{}) interface{}); ok {
		r0 = returnFunc(taskCtx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(plugin.TaskContext, map[string]interface{}) errors.Error); ok {
		r1 = returnFunc(taskCtx, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// PluginTask_PrepareTaskData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareTaskData'
type PluginTask_PrepareTaskData_Call struct {
	*mock.Call
}

// PrepareTaskData is a helper method to define mock.On call
//   - taskCtx plugin.TaskContext
//   - options map[string]interface{}
func (_e *PluginTask_Expecter) PrepareTaskData(taskCtx any, options any) *PluginTask_PrepareTaskData_Call {
	return &PluginTask_PrepareTaskData_Call{Call: _e.mock.On("PrepareTaskData", taskCtx, options)}
}

func (_c *PluginTask_PrepareTaskData_Call) Run(run func(taskCtx plugin.TaskContext, options map[string]interface{})) *PluginTask_PrepareTaskData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.TaskContext
		if args[0] != nil {
			arg0 = args[0].(plugin.TaskContext)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PluginTask_PrepareTaskData_Call) Return(ifaceVal interface{}, error errors.Error) *PluginTask_PrepareTaskData_Call {
	_c.Call.Return(ifaceVal, error)
	return _c
}

func (_c *PluginTask_PrepareTaskData_Call) RunAndReturn(run func(taskCtx plugin.TaskContext, options map[string]interface{}) (interface{}, errors.Error)) *PluginTask_PrepareTaskData_Call {
	_c.Call.Return(run)
	return _c
}

// SubTaskMetas provides a mock function for the type PluginTask
func (_mock *PluginTask) SubTaskMetas() []plugin.SubTaskMeta {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubTaskMetas")
	}

	var r0 []plugin.SubTaskMeta
	if returnFunc, ok := ret.Get(0).(func() []plugin.SubTaskMeta); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.SubTaskMeta)
		}
	}
	return r0
}

// PluginTask_SubTaskMetas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTaskMetas'
type PluginTask_SubTaskMetas_Call struct {
	*mock.Call
}

// SubTaskMetas is a helper method to define mock.On call
func (_e *PluginTask_Expecter) SubTaskMetas() *PluginTask_SubTaskMetas_Call {
	return &PluginTask_SubTaskMetas_Call{Call: _e.mock.On("SubTaskMetas")}
}

func (_c *PluginTask_SubTaskMetas_Call) Run(run func()) *PluginTask_SubTaskMetas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginTask_SubTaskMetas_Call) Return(subTaskMetas []plugin.SubTaskMeta) *PluginTask_SubTaskMetas_Call {
	_c.Call.Return(subTaskMetas)
	return _c
}

func (_c *PluginTask_SubTaskMetas_Call) RunAndReturn(run func() []plugin.SubTaskMeta) *PluginTask_SubTaskMetas_Call {
	_c.Call.Return(run)
	return _c
}
