// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPluginIcon creates a new instance of PluginIcon. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginIcon(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginIcon {
	mock := &PluginIcon{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginIcon is an autogenerated mock type for the PluginIcon type
type PluginIcon struct {
	mock.Mock
}

type PluginIcon_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginIcon) EXPECT() *PluginIcon_Expecter {
	return &PluginIcon_Expecter{mock: &_m.Mock}
}

// SvgIcon provides a mock function for the type PluginIcon
func (_mock *PluginIcon) SvgIcon() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SvgIcon")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PluginIcon_SvgIcon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SvgIcon'
type PluginIcon_SvgIcon_Call struct {
	*mock.Call
}

// SvgIcon is a helper method to define mock.On call
func (_e *PluginIcon_Expecter) SvgIcon() *PluginIcon_SvgIcon_Call {
	return &PluginIcon_SvgIcon_Call{Call: _e.mock.On("SvgIcon")}
}

func (_c *PluginIcon_SvgIcon_Call) Run(run func()) *PluginIcon_SvgIcon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginIcon_SvgIcon_Call) Return(s string) *PluginIcon_SvgIcon_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PluginIcon_SvgIcon_Call) RunAndReturn(run func() string) *PluginIcon_SvgIcon_Call {
	_c.Call.Return(run)
	return _c
}
