// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/dal"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginSource creates a new instance of PluginSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginSource {
	mock := &PluginSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginSource is an autogenerated mock type for the PluginSource type
type PluginSource struct {
	mock.Mock
}

type PluginSource_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginSource) EXPECT() *PluginSource_Expecter {
	return &PluginSource_Expecter{mock: &_m.Mock}
}

// Connection provides a mock function for the type PluginSource
func (_mock *PluginSource) Connection() dal.Tabler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connection")
	}

	var r0 dal.Tabler
	if returnFunc, ok := ret.Get(0).(func() dal.Tabler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Tabler)
		}
	}
	return r0
}

// PluginSource_Connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connection'
type PluginSource_Connection_Call struct {
	*mock.Call
}

// Connection is a helper method to define mock.On call
func (_e *PluginSource_Expecter) Connection() *PluginSource_Connection_Call {
	return &PluginSource_Connection_Call{Call: _e.mock.On("Connection")}
}

func (_c *PluginSource_Connection_Call) Run(run func()) *PluginSource_Connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginSource_Connection_Call) Return(tabler dal.Tabler) *PluginSource_Connection_Call {
	_c.Call.Return(tabler)
	return _c
}

func (_c *PluginSource_Connection_Call) RunAndReturn(run func() dal.Tabler) *PluginSource_Connection_Call {
	_c.Call.Return(run)
	return _c
}

// Scope provides a mock function for the type PluginSource
func (_mock *PluginSource) Scope() plugin.ToolLayerScope {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scope")
	}

	var r0 plugin.ToolLayerScope
	if returnFunc, ok := ret.Get(0).(func() plugin.ToolLayerScope); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.ToolLayerScope)
		}
	}
	return r0
}

// PluginSource_Scope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scope'
type PluginSource_Scope_Call struct {
	*mock.Call
}

// Scope is a helper method to define mock.On call
func (_e *PluginSource_Expecter) Scope() *PluginSource_Scope_Call {
	return &PluginSource_Scope_Call{Call: _e.mock.On("Scope")}
}

func (_c *PluginSource_Scope_Call) Run(run func()) *PluginSource_Scope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginSource_Scope_Call) Return(toolLayerScope plugin.ToolLayerScope) *PluginSource_Scope_Call {
	_c.Call.Return(toolLayerScope)
	return _c
}

func (_c *PluginSource_Scope_Call) RunAndReturn(run func() plugin.ToolLayerScope) *PluginSource_Scope_Call {
	_c.Call.Return(run)
	return _c
}

// ScopeConfig provides a mock function for the type PluginSource
func (_mock *PluginSource) ScopeConfig() dal.Tabler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeConfig")
	}

	var r0 dal.Tabler
	if returnFunc, ok := ret.Get(0).(func() dal.Tabler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Tabler)
		}
	}
	return r0
}

// PluginSource_ScopeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeConfig'
type PluginSource_ScopeConfig_Call struct {
	*mock.Call
}

// ScopeConfig is a helper method to define mock.On call
func (_e *PluginSource_Expecter) ScopeConfig() *PluginSource_ScopeConfig_Call {
	return &PluginSource_ScopeConfig_Call{Call: _e.mock.On("ScopeConfig")}
}

func (_c *PluginSource_ScopeConfig_Call) Run(run func()) *PluginSource_ScopeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginSource_ScopeConfig_Call) Return(tabler dal.Tabler) *PluginSource_ScopeConfig_Call {
	_c.Call.Return(tabler)
	return _c
}

func (_c *PluginSource_ScopeConfig_Call) RunAndReturn(run func() dal.Tabler) *PluginSource_ScopeConfig_Call {
	_c.Call.Return(run)
	return _c
}
