// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/dal"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginModel creates a new instance of PluginModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginModel {
	mock := &PluginModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginModel is an autogenerated mock type for the PluginModel type
type PluginModel struct {
	mock.Mock
}

type PluginModel_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginModel) EXPECT() *PluginModel_Expecter {
	return &PluginModel_Expecter{mock: &_m.Mock}
}

// GetTablesInfo provides a mock function for the type PluginModel
func (_mock *PluginModel) GetTablesInfo() []dal.Tabler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTablesInfo")
	}

	var r0 []dal.Tabler
	if returnFunc, ok := ret.Get(0).(func() []dal.Tabler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dal.Tabler)
		}
	}
	return r0
}

// PluginModel_GetTablesInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTablesInfo'
type PluginModel_GetTablesInfo_Call struct {
	*mock.Call
}

// GetTablesInfo is a helper method to define mock.On call
func (_e *PluginModel_Expecter) GetTablesInfo() *PluginModel_GetTablesInfo_Call {
	return &PluginModel_GetTablesInfo_Call{Call: _e.mock.On("GetTablesInfo")}
}

func (_c *PluginModel_GetTablesInfo_Call) Run(run func()) *PluginModel_GetTablesInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginModel_GetTablesInfo_Call) Return(tablers []dal.Tabler) *PluginModel_GetTablesInfo_Call {
	_c.Call.Return(tablers)
	return _c
}

func (_c *PluginModel_GetTablesInfo_Call) RunAndReturn(run func() []dal.Tabler) *PluginModel_GetTablesInfo_Call {
	_c.Call.Return(run)
	return _c
}
