// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginApi creates a new instance of PluginApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginApi {
	mock := &PluginApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginApi is an autogenerated mock type for the PluginApi type
type PluginApi struct {
	mock.Mock
}

type PluginApi_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginApi) EXPECT() *PluginApi_Expecter {
	return &PluginApi_Expecter{mock: &_m.Mock}
}

// ApiResources provides a mock function for the type PluginApi
func (_mock *PluginApi) ApiResources() map[string]map[string]plugin.ApiResourceHandler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApiResources")
	}

	var r0 map[string]map[string]plugin.ApiResourceHandler
	if returnFunc, ok := ret.Get(0).(func() map[string]map[string]plugin.ApiResourceHandler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]plugin.ApiResourceHandler)
		}
	}
	return r0
}

// PluginApi_ApiResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApiResources'
type PluginApi_ApiResources_Call struct {
	*mock.Call
}

// ApiResources is a helper method to define mock.On call
func (_e *PluginApi_Expecter) ApiResources() *PluginApi_ApiResources_Call {
	return &PluginApi_ApiResources_Call{Call: _e.mock.On("ApiResources")}
}

func (_c *PluginApi_ApiResources_Call) Run(run func()) *PluginApi_ApiResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginApi_ApiResources_Call) Return(stringToStringToApiResourceHandler map[string]map[string]plugin.ApiResourceHandler) *PluginApi_ApiResources_Call {
	_c.Call.Return(stringToStringToApiResourceHandler)
	return _c
}

func (_c *PluginApi_ApiResources_Call) RunAndReturn(run func() map[string]map[string]plugin.ApiResourceHandler) *PluginApi_ApiResources_Call {
	_c.Call.Return(run)
	return _c
}
