// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewPrepareApiClient creates a new instance of PrepareApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrepareApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrepareApiClient {
	mock := &PrepareApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrepareApiClient is an autogenerated mock type for the PrepareApiClient type
type PrepareApiClient struct {
	mock.Mock
}

type PrepareApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PrepareApiClient) EXPECT() *PrepareApiClient_Expecter {
	return &PrepareApiClient_Expecter{mock: &_m.Mock}
}

// PrepareApiClient provides a mock function for the type PrepareApiClient
func (_mock *PrepareApiClient) PrepareApiClient(apiClient plugin.ApiClient) errors.Error {
	ret := _mock.Called(apiClient)

	if len(ret) == 0 {
		panic("no return value specified for PrepareApiClient")
	}

	var r0 errors.Error
	if returnFunc, ok := ret.Get(0).(func(plugin.ApiClient) errors.Error); ok {
		r0 = returnFunc(apiClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}
	return r0
}

// PrepareApiClient_PrepareApiClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareApiClient'
type PrepareApiClient_PrepareApiClient_Call struct {
	*mock.Call
}

// PrepareApiClient is a helper method to define mock.On call
//   - apiClient plugin.ApiClient
func (_e *PrepareApiClient_Expecter) PrepareApiClient(apiClient any) *PrepareApiClient_PrepareApiClient_Call {
	return &PrepareApiClient_PrepareApiClient_Call{Call: _e.mock.On("PrepareApiClient", apiClient)}
}

func (_c *PrepareApiClient_PrepareApiClient_Call) Run(run func(apiClient plugin.ApiClient)) *PrepareApiClient_PrepareApiClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.ApiClient
		if args[0] != nil {
			arg0 = args[0].(plugin.ApiClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrepareApiClient_PrepareApiClient_Call) Return(error errors.Error) *PrepareApiClient_PrepareApiClient_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *PrepareApiClient_PrepareApiClient_Call) RunAndReturn(run func(apiClient plugin.ApiClient) errors.Error) *PrepareApiClient_PrepareApiClient_Call {
	_c.Call.Return(run)
	return _c
}
