// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewScope creates a new instance of Scope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScope(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scope {
	mock := &Scope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Scope is an autogenerated mock type for the Scope type
type Scope struct {
	mock.Mock
}

type Scope_Expecter struct {
	mock *mock.Mock
}

func (_m *Scope) EXPECT() *Scope_Expecter {
	return &Scope_Expecter{mock: &_m.Mock}
}

// ScopeId provides a mock function for the type Scope
func (_mock *Scope) ScopeId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Scope_ScopeId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeId'
type Scope_ScopeId_Call struct {
	*mock.Call
}

// ScopeId is a helper method to define mock.On call
func (_e *Scope_Expecter) ScopeId() *Scope_ScopeId_Call {
	return &Scope_ScopeId_Call{Call: _e.mock.On("ScopeId")}
}

func (_c *Scope_ScopeId_Call) Run(run func()) *Scope_ScopeId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Scope_ScopeId_Call) Return(s string) *Scope_ScopeId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Scope_ScopeId_Call) RunAndReturn(run func() string) *Scope_ScopeId_Call {
	_c.Call.Return(run)
	return _c
}

// ScopeName provides a mock function for the type Scope
func (_mock *Scope) ScopeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Scope_ScopeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeName'
type Scope_ScopeName_Call struct {
	*mock.Call
}

// ScopeName is a helper method to define mock.On call
func (_e *Scope_Expecter) ScopeName() *Scope_ScopeName_Call {
	return &Scope_ScopeName_Call{Call: _e.mock.On("ScopeName")}
}

func (_c *Scope_ScopeName_Call) Run(run func()) *Scope_ScopeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Scope_ScopeName_Call) Return(s string) *Scope_ScopeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Scope_ScopeName_Call) RunAndReturn(run func() string) *Scope_ScopeName_Call {
	_c.Call.Return(run)
	return _c
}

// TableName provides a mock function for the type Scope
func (_mock *Scope) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Scope_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type Scope_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *Scope_Expecter) TableName() *Scope_TableName_Call {
	return &Scope_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *Scope_TableName_Call) Run(run func()) *Scope_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Scope_TableName_Call) Return(s string) *Scope_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Scope_TableName_Call) RunAndReturn(run func() string) *Scope_TableName_Call {
	_c.Call.Return(run)
	return _c
}
