// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/apache/devlake/core/config"
	context0 "github.com/apache/devlake/core/context"
	"github.com/apache/devlake/core/dal"
	"github.com/apache/devlake/core/log"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewSubTaskContext creates a new instance of SubTaskContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubTaskContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubTaskContext {
	mock := &SubTaskContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubTaskContext is an autogenerated mock type for the SubTaskContext type
type SubTaskContext struct {
	mock.Mock
}

type SubTaskContext_Expecter struct {
	mock *mock.Mock
}

func (_m *SubTaskContext) EXPECT() *SubTaskContext_Expecter {
	return &SubTaskContext_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetConfig(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SubTaskContext_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type SubTaskContext_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - name string
func (_e *SubTaskContext_Expecter) GetConfig(name any) *SubTaskContext_GetConfig_Call {
	return &SubTaskContext_GetConfig_Call{Call: _e.mock.On("GetConfig", name)}
}

func (_c *SubTaskContext_GetConfig_Call) Run(run func(name string)) *SubTaskContext_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubTaskContext_GetConfig_Call) Return(s string) *SubTaskContext_GetConfig_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SubTaskContext_GetConfig_Call) RunAndReturn(run func(name string) string) *SubTaskContext_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigReader provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetConfigReader() config.ConfigReader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigReader")
	}

	var r0 config.ConfigReader
	if returnFunc, ok := ret.Get(0).(func() config.ConfigReader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ConfigReader)
		}
	}
	return r0
}

// SubTaskContext_GetConfigReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigReader'
type SubTaskContext_GetConfigReader_Call struct {
	*mock.Call
}

// GetConfigReader is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetConfigReader() *SubTaskContext_GetConfigReader_Call {
	return &SubTaskContext_GetConfigReader_Call{Call: _e.mock.On("GetConfigReader")}
}

func (_c *SubTaskContext_GetConfigReader_Call) Run(run func()) *SubTaskContext_GetConfigReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetConfigReader_Call) Return(configReader config.ConfigReader) *SubTaskContext_GetConfigReader_Call {
	_c.Call.Return(configReader)
	return _c
}

func (_c *SubTaskContext_GetConfigReader_Call) RunAndReturn(run func() config.ConfigReader) *SubTaskContext_GetConfigReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// SubTaskContext_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type SubTaskContext_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetContext() *SubTaskContext_GetContext_Call {
	return &SubTaskContext_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *SubTaskContext_GetContext_Call) Run(run func()) *SubTaskContext_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetContext_Call) Return(context1 context.Context) *SubTaskContext_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *SubTaskContext_GetContext_Call) RunAndReturn(run func() context.Context) *SubTaskContext_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetDal provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetDal() dal.Dal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDal")
	}

	var r0 dal.Dal
	if returnFunc, ok := ret.Get(0).(func() dal.Dal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Dal)
		}
	}
	return r0
}

// SubTaskContext_GetDal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDal'
type SubTaskContext_GetDal_Call struct {
	*mock.Call
}

// GetDal is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetDal() *SubTaskContext_GetDal_Call {
	return &SubTaskContext_GetDal_Call{Call: _e.mock.On("GetDal")}
}

func (_c *SubTaskContext_GetDal_Call) Run(run func()) *SubTaskContext_GetDal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetDal_Call) Return(dal1 dal.Dal) *SubTaskContext_GetDal_Call {
	_c.Call.Return(dal1)
	return _c
}

func (_c *SubTaskContext_GetDal_Call) RunAndReturn(run func() dal.Dal) *SubTaskContext_GetDal_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetData() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// SubTaskContext_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type SubTaskContext_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetData() *SubTaskContext_GetData_Call {
	return &SubTaskContext_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *SubTaskContext_GetData_Call) Run(run func()) *SubTaskContext_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetData_Call) Return(ifaceVal interface{}) *SubTaskContext_GetData_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *SubTaskContext_GetData_Call) RunAndReturn(run func() interface{}) *SubTaskContext_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetLogger() log.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 log.Logger
	if returnFunc, ok := ret.Get(0).(func() log.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}
	return r0
}

// SubTaskContext_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type SubTaskContext_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetLogger() *SubTaskContext_GetLogger_Call {
	return &SubTaskContext_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *SubTaskContext_GetLogger_Call) Run(run func()) *SubTaskContext_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetLogger_Call) Return(logger log.Logger) *SubTaskContext_GetLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *SubTaskContext_GetLogger_Call) RunAndReturn(run func() log.Logger) *SubTaskContext_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SubTaskContext_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type SubTaskContext_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetName() *SubTaskContext_GetName_Call {
	return &SubTaskContext_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *SubTaskContext_GetName_Call) Run(run func()) *SubTaskContext_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetName_Call) Return(s string) *SubTaskContext_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SubTaskContext_GetName_Call) RunAndReturn(run func() string) *SubTaskContext_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgress provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) GetProgress() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProgress")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// SubTaskContext_GetProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgress'
type SubTaskContext_GetProgress_Call struct {
	*mock.Call
}

// GetProgress is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) GetProgress() *SubTaskContext_GetProgress_Call {
	return &SubTaskContext_GetProgress_Call{Call: _e.mock.On("GetProgress")}
}

func (_c *SubTaskContext_GetProgress_Call) Run(run func()) *SubTaskContext_GetProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_GetProgress_Call) Return(n int) *SubTaskContext_GetProgress_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *SubTaskContext_GetProgress_Call) RunAndReturn(run func() int) *SubTaskContext_GetProgress_Call {
	_c.Call.Return(run)
	return _c
}

// IncProgress provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) IncProgress(quantity int) {
	_mock.Called(quantity)
	return
}

// SubTaskContext_IncProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncProgress'
type SubTaskContext_IncProgress_Call struct {
	*mock.Call
}

// IncProgress is a helper method to define mock.On call
//   - quantity int
func (_e *SubTaskContext_Expecter) IncProgress(quantity any) *SubTaskContext_IncProgress_Call {
	return &SubTaskContext_IncProgress_Call{Call: _e.mock.On("IncProgress", quantity)}
}

func (_c *SubTaskContext_IncProgress_Call) Run(run func(quantity int)) *SubTaskContext_IncProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubTaskContext_IncProgress_Call) Return() *SubTaskContext_IncProgress_Call {
	_c.Call.Return()
	return _c
}

func (_c *SubTaskContext_IncProgress_Call) RunAndReturn(run func(quantity int)) *SubTaskContext_IncProgress_Call {
	_c.Run(run)
	return _c
}

// NestedLogger provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) NestedLogger(name string) context0.BasicRes {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for NestedLogger")
	}

	var r0 context0.BasicRes
	if returnFunc, ok := ret.Get(0).(func(string) context0.BasicRes); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context0.BasicRes)
		}
	}
	return r0
}

// SubTaskContext_NestedLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NestedLogger'
type SubTaskContext_NestedLogger_Call struct {
	*mock.Call
}

// NestedLogger is a helper method to define mock.On call
//   - name string
func (_e *SubTaskContext_Expecter) NestedLogger(name any) *SubTaskContext_NestedLogger_Call {
	return &SubTaskContext_NestedLogger_Call{Call: _e.mock.On("NestedLogger", name)}
}

func (_c *SubTaskContext_NestedLogger_Call) Run(run func(name string)) *SubTaskContext_NestedLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubTaskContext_NestedLogger_Call) Return(basicRes context0.BasicRes) *SubTaskContext_NestedLogger_Call {
	_c.Call.Return(basicRes)
	return _c
}

func (_c *SubTaskContext_NestedLogger_Call) RunAndReturn(run func(name string) context0.BasicRes) *SubTaskContext_NestedLogger_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceLogger provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) ReplaceLogger(logger log.Logger) context0.BasicRes {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceLogger")
	}

	var r0 context0.BasicRes
	if returnFunc, ok := ret.Get(0).(func(log.Logger) context0.BasicRes); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context0.BasicRes)
		}
	}
	return r0
}

// SubTaskContext_ReplaceLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceLogger'
type SubTaskContext_ReplaceLogger_Call struct {
	*mock.Call
}

// ReplaceLogger is a helper method to define mock.On call
//   - logger log.Logger
func (_e *SubTaskContext_Expecter) ReplaceLogger(logger any) *SubTaskContext_ReplaceLogger_Call {
	return &SubTaskContext_ReplaceLogger_Call{Call: _e.mock.On("ReplaceLogger", logger)}
}

func (_c *SubTaskContext_ReplaceLogger_Call) Run(run func(logger log.Logger)) *SubTaskContext_ReplaceLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SubTaskContext_ReplaceLogger_Call) Return(basicRes context0.BasicRes) *SubTaskContext_ReplaceLogger_Call {
	_c.Call.Return(basicRes)
	return _c
}

func (_c *SubTaskContext_ReplaceLogger_Call) RunAndReturn(run func(logger log.Logger) context0.BasicRes) *SubTaskContext_ReplaceLogger_Call {
	_c.Call.Return(run)
	return _c
}

// SetProgress provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) SetProgress(current int, total int) {
	_mock.Called(current, total)
	return
}

// SubTaskContext_SetProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProgress'
type SubTaskContext_SetProgress_Call struct {
	*mock.Call
}

// SetProgress is a helper method to define mock.On call
//   - current int
//   - total int
func (_e *SubTaskContext_Expecter) SetProgress(current any, total any) *SubTaskContext_SetProgress_Call {
	return &SubTaskContext_SetProgress_Call{Call: _e.mock.On("SetProgress", current, total)}
}

func (_c *SubTaskContext_SetProgress_Call) Run(run func(current int, total int)) *SubTaskContext_SetProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubTaskContext_SetProgress_Call) Return() *SubTaskContext_SetProgress_Call {
	_c.Call.Return()
	return _c
}

func (_c *SubTaskContext_SetProgress_Call) RunAndReturn(run func(current int, total int)) *SubTaskContext_SetProgress_Call {
	_c.Run(run)
	return _c
}

// TaskContext provides a mock function for the type SubTaskContext
func (_mock *SubTaskContext) TaskContext() plugin.TaskContext {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TaskContext")
	}

	var r0 plugin.TaskContext
	if returnFunc, ok := ret.Get(0).(func() plugin.TaskContext); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.TaskContext)
		}
	}
	return r0
}

// SubTaskContext_TaskContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TaskContext'
type SubTaskContext_TaskContext_Call struct {
	*mock.Call
}

// TaskContext is a helper method to define mock.On call
func (_e *SubTaskContext_Expecter) TaskContext() *SubTaskContext_TaskContext_Call {
	return &SubTaskContext_TaskContext_Call{Call: _e.mock.On("TaskContext")}
}

func (_c *SubTaskContext_TaskContext_Call) Run(run func()) *SubTaskContext_TaskContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubTaskContext_TaskContext_Call) Return(taskContext plugin.TaskContext) *SubTaskContext_TaskContext_Call {
	_c.Call.Return(taskContext)
	return _c
}

func (_c *SubTaskContext_TaskContext_Call) RunAndReturn(run func() plugin.TaskContext) *SubTaskContext_TaskContext_Call {
	_c.Call.Return(run)
	return _c
}
