// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/apache/devlake/core/config"
	context0 "github.com/apache/devlake/core/context"
	"github.com/apache/devlake/core/dal"
	"github.com/apache/devlake/core/errors"
	"github.com/apache/devlake/core/log"
	"github.com/apache/devlake/core/models"
	"github.com/apache/devlake/core/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewTaskContext creates a new instance of TaskContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskContext {
	mock := &TaskContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskContext is an autogenerated mock type for the TaskContext type
type TaskContext struct {
	mock.Mock
}

type TaskContext_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskContext) EXPECT() *TaskContext_Expecter {
	return &TaskContext_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type TaskContext
func (_mock *TaskContext) GetConfig(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TaskContext_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type TaskContext_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - name string
func (_e *TaskContext_Expecter) GetConfig(name any) *TaskContext_GetConfig_Call {
	return &TaskContext_GetConfig_Call{Call: _e.mock.On("GetConfig", name)}
}

func (_c *TaskContext_GetConfig_Call) Run(run func(name string)) *TaskContext_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_GetConfig_Call) Return(s string) *TaskContext_GetConfig_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TaskContext_GetConfig_Call) RunAndReturn(run func(name string) string) *TaskContext_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigReader provides a mock function for the type TaskContext
func (_mock *TaskContext) GetConfigReader() config.ConfigReader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigReader")
	}

	var r0 config.ConfigReader
	if returnFunc, ok := ret.Get(0).(func() config.ConfigReader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ConfigReader)
		}
	}
	return r0
}

// TaskContext_GetConfigReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigReader'
type TaskContext_GetConfigReader_Call struct {
	*mock.Call
}

// GetConfigReader is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetConfigReader() *TaskContext_GetConfigReader_Call {
	return &TaskContext_GetConfigReader_Call{Call: _e.mock.On("GetConfigReader")}
}

func (_c *TaskContext_GetConfigReader_Call) Run(run func()) *TaskContext_GetConfigReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetConfigReader_Call) Return(configReader config.ConfigReader) *TaskContext_GetConfigReader_Call {
	_c.Call.Return(configReader)
	return _c
}

func (_c *TaskContext_GetConfigReader_Call) RunAndReturn(run func() config.ConfigReader) *TaskContext_GetConfigReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type TaskContext
func (_mock *TaskContext) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// TaskContext_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type TaskContext_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetContext() *TaskContext_GetContext_Call {
	return &TaskContext_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *TaskContext_GetContext_Call) Run(run func()) *TaskContext_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetContext_Call) Return(context1 context.Context) *TaskContext_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *TaskContext_GetContext_Call) RunAndReturn(run func() context.Context) *TaskContext_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetDal provides a mock function for the type TaskContext
func (_mock *TaskContext) GetDal() dal.Dal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDal")
	}

	var r0 dal.Dal
	if returnFunc, ok := ret.Get(0).(func() dal.Dal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dal.Dal)
		}
	}
	return r0
}

// TaskContext_GetDal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDal'
type TaskContext_GetDal_Call struct {
	*mock.Call
}

// GetDal is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetDal() *TaskContext_GetDal_Call {
	return &TaskContext_GetDal_Call{Call: _e.mock.On("GetDal")}
}

func (_c *TaskContext_GetDal_Call) Run(run func()) *TaskContext_GetDal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetDal_Call) Return(dal1 dal.Dal) *TaskContext_GetDal_Call {
	_c.Call.Return(dal1)
	return _c
}

func (_c *TaskContext_GetDal_Call) RunAndReturn(run func() dal.Dal) *TaskContext_GetDal_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type TaskContext
func (_mock *TaskContext) GetData() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// TaskContext_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type TaskContext_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetData() *TaskContext_GetData_Call {
	return &TaskContext_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *TaskContext_GetData_Call) Run(run func()) *TaskContext_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetData_Call) Return(ifaceVal interface{}) *TaskContext_GetData_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *TaskContext_GetData_Call) RunAndReturn(run func() interface{}) *TaskContext_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type TaskContext
func (_mock *TaskContext) GetLogger() log.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 log.Logger
	if returnFunc, ok := ret.Get(0).(func() log.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}
	return r0
}

// TaskContext_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type TaskContext_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetLogger() *TaskContext_GetLogger_Call {
	return &TaskContext_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *TaskContext_GetLogger_Call) Run(run func()) *TaskContext_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetLogger_Call) Return(logger log.Logger) *TaskContext_GetLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *TaskContext_GetLogger_Call) RunAndReturn(run func() log.Logger) *TaskContext_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type TaskContext
func (_mock *TaskContext) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TaskContext_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type TaskContext_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetName() *TaskContext_GetName_Call {
	return &TaskContext_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *TaskContext_GetName_Call) Run(run func()) *TaskContext_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetName_Call) Return(s string) *TaskContext_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TaskContext_GetName_Call) RunAndReturn(run func() string) *TaskContext_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgress provides a mock function for the type TaskContext
func (_mock *TaskContext) GetProgress() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProgress")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// TaskContext_GetProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgress'
type TaskContext_GetProgress_Call struct {
	*mock.Call
}

// GetProgress is a helper method to define mock.On call
func (_e *TaskContext_Expecter) GetProgress() *TaskContext_GetProgress_Call {
	return &TaskContext_GetProgress_Call{Call: _e.mock.On("GetProgress")}
}

func (_c *TaskContext_GetProgress_Call) Run(run func()) *TaskContext_GetProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_GetProgress_Call) Return(n int) *TaskContext_GetProgress_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TaskContext_GetProgress_Call) RunAndReturn(run func() int) *TaskContext_GetProgress_Call {
	_c.Call.Return(run)
	return _c
}

// IncProgress provides a mock function for the type TaskContext
func (_mock *TaskContext) IncProgress(quantity int) {
	_mock.Called(quantity)
	return
}

// TaskContext_IncProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncProgress'
type TaskContext_IncProgress_Call struct {
	*mock.Call
}

// IncProgress is a helper method to define mock.On call
//   - quantity int
func (_e *TaskContext_Expecter) IncProgress(quantity any) *TaskContext_IncProgress_Call {
	return &TaskContext_IncProgress_Call{Call: _e.mock.On("IncProgress", quantity)}
}

func (_c *TaskContext_IncProgress_Call) Run(run func(quantity int)) *TaskContext_IncProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_IncProgress_Call) Return() *TaskContext_IncProgress_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskContext_IncProgress_Call) RunAndReturn(run func(quantity int)) *TaskContext_IncProgress_Call {
	_c.Run(run)
	return _c
}

// NestedLogger provides a mock function for the type TaskContext
func (_mock *TaskContext) NestedLogger(name string) context0.BasicRes {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for NestedLogger")
	}

	var r0 context0.BasicRes
	if returnFunc, ok := ret.Get(0).(func(string) context0.BasicRes); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context0.BasicRes)
		}
	}
	return r0
}

// TaskContext_NestedLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NestedLogger'
type TaskContext_NestedLogger_Call struct {
	*mock.Call
}

// NestedLogger is a helper method to define mock.On call
//   - name string
func (_e *TaskContext_Expecter) NestedLogger(name any) *TaskContext_NestedLogger_Call {
	return &TaskContext_NestedLogger_Call{Call: _e.mock.On("NestedLogger", name)}
}

func (_c *TaskContext_NestedLogger_Call) Run(run func(name string)) *TaskContext_NestedLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_NestedLogger_Call) Return(basicRes context0.BasicRes) *TaskContext_NestedLogger_Call {
	_c.Call.Return(basicRes)
	return _c
}

func (_c *TaskContext_NestedLogger_Call) RunAndReturn(run func(name string) context0.BasicRes) *TaskContext_NestedLogger_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceLogger provides a mock function for the type TaskContext
func (_mock *TaskContext) ReplaceLogger(logger log.Logger) context0.BasicRes {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceLogger")
	}

	var r0 context0.BasicRes
	if returnFunc, ok := ret.Get(0).(func(log.Logger) context0.BasicRes); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context0.BasicRes)
		}
	}
	return r0
}

// TaskContext_ReplaceLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceLogger'
type TaskContext_ReplaceLogger_Call struct {
	*mock.Call
}

// ReplaceLogger is a helper method to define mock.On call
//   - logger log.Logger
func (_e *TaskContext_Expecter) ReplaceLogger(logger any) *TaskContext_ReplaceLogger_Call {
	return &TaskContext_ReplaceLogger_Call{Call: _e.mock.On("ReplaceLogger", logger)}
}

func (_c *TaskContext_ReplaceLogger_Call) Run(run func(logger log.Logger)) *TaskContext_ReplaceLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 log.Logger
		if args[0] != nil {
			arg0 = args[0].(log.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_ReplaceLogger_Call) Return(basicRes context0.BasicRes) *TaskContext_ReplaceLogger_Call {
	_c.Call.Return(basicRes)
	return _c
}

func (_c *TaskContext_ReplaceLogger_Call) RunAndReturn(run func(logger log.Logger) context0.BasicRes) *TaskContext_ReplaceLogger_Call {
	_c.Call.Return(run)
	return _c
}

// SetData provides a mock function for the type TaskContext
func (_mock *TaskContext) SetData(data interface{}) {
	_mock.Called(data)
	return
}

// TaskContext_SetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetData'
type TaskContext_SetData_Call struct {
	*mock.Call
}

// SetData is a helper method to define mock.On call
//   - data interface{}
func (_e *TaskContext_Expecter) SetData(data any) *TaskContext_SetData_Call {
	return &TaskContext_SetData_Call{Call: _e.mock.On("SetData", data)}
}

func (_c *TaskContext_SetData_Call) Run(run func(data interface{})) *TaskContext_SetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_SetData_Call) Return() *TaskContext_SetData_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskContext_SetData_Call) RunAndReturn(run func(data interface{})) *TaskContext_SetData_Call {
	_c.Run(run)
	return _c
}

// SetProgress provides a mock function for the type TaskContext
func (_mock *TaskContext) SetProgress(current int, total int) {
	_mock.Called(current, total)
	return
}

// TaskContext_SetProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProgress'
type TaskContext_SetProgress_Call struct {
	*mock.Call
}

// SetProgress is a helper method to define mock.On call
//   - current int
//   - total int
func (_e *TaskContext_Expecter) SetProgress(current any, total any) *TaskContext_SetProgress_Call {
	return &TaskContext_SetProgress_Call{Call: _e.mock.On("SetProgress", current, total)}
}

func (_c *TaskContext_SetProgress_Call) Run(run func(current int, total int)) *TaskContext_SetProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskContext_SetProgress_Call) Return() *TaskContext_SetProgress_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskContext_SetProgress_Call) RunAndReturn(run func(current int, total int)) *TaskContext_SetProgress_Call {
	_c.Run(run)
	return _c
}

// SetSyncPolicy provides a mock function for the type TaskContext
func (_mock *TaskContext) SetSyncPolicy(syncPolicy *models.SyncPolicy) {
	_mock.Called(syncPolicy)
	return
}

// TaskContext_SetSyncPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSyncPolicy'
type TaskContext_SetSyncPolicy_Call struct {
	*mock.Call
}

// SetSyncPolicy is a helper method to define mock.On call
//   - syncPolicy *models.SyncPolicy
func (_e *TaskContext_Expecter) SetSyncPolicy(syncPolicy any) *TaskContext_SetSyncPolicy_Call {
	return &TaskContext_SetSyncPolicy_Call{Call: _e.mock.On("SetSyncPolicy", syncPolicy)}
}

func (_c *TaskContext_SetSyncPolicy_Call) Run(run func(syncPolicy *models.SyncPolicy)) *TaskContext_SetSyncPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.SyncPolicy
		if args[0] != nil {
			arg0 = args[0].(*models.SyncPolicy)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_SetSyncPolicy_Call) Return() *TaskContext_SetSyncPolicy_Call {
	_c.Call.Return()
	return _c
}

func (_c *TaskContext_SetSyncPolicy_Call) RunAndReturn(run func(syncPolicy *models.SyncPolicy)) *TaskContext_SetSyncPolicy_Call {
	_c.Run(run)
	return _c
}

// SubTaskContext provides a mock function for the type TaskContext
func (_mock *TaskContext) SubTaskContext(subtask string) (plugin.SubTaskContext, errors.Error) {
	ret := _mock.Called(subtask)

	if len(ret) == 0 {
		panic("no return value specified for SubTaskContext")
	}

	var r0 plugin.SubTaskContext
	var r1 errors.Error
	if returnFunc, ok := ret.Get(0).(func(string) (plugin.SubTaskContext, errors.Error)); ok {
		return returnFunc(subtask)
	}
	if returnFunc, ok := ret.Get(0).(func(string) plugin.SubTaskContext); ok {
		r0 = returnFunc(subtask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.SubTaskContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) errors.Error); ok {
		r1 = returnFunc(subtask)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}
	return r0, r1
}

// TaskContext_SubTaskContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubTaskContext'
type TaskContext_SubTaskContext_Call struct {
	*mock.Call
}

// SubTaskContext is a helper method to define mock.On call
//   - subtask string
func (_e *TaskContext_Expecter) SubTaskContext(subtask any) *TaskContext_SubTaskContext_Call {
	return &TaskContext_SubTaskContext_Call{Call: _e.mock.On("SubTaskContext", subtask)}
}

func (_c *TaskContext_SubTaskContext_Call) Run(run func(subtask string)) *TaskContext_SubTaskContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskContext_SubTaskContext_Call) Return(subTaskContext plugin.SubTaskContext, error errors.Error) *TaskContext_SubTaskContext_Call {
	_c.Call.Return(subTaskContext, error)
	return _c
}

func (_c *TaskContext_SubTaskContext_Call) RunAndReturn(run func(subtask string) (plugin.SubTaskContext, errors.Error)) *TaskContext_SubTaskContext_Call {
	_c.Call.Return(run)
	return _c
}

// SyncPolicy provides a mock function for the type TaskContext
func (_mock *TaskContext) SyncPolicy() *models.SyncPolicy {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncPolicy")
	}

	var r0 *models.SyncPolicy
	if returnFunc, ok := ret.Get(0).(func() *models.SyncPolicy); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SyncPolicy)
		}
	}
	return r0
}

// TaskContext_SyncPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPolicy'
type TaskContext_SyncPolicy_Call struct {
	*mock.Call
}

// SyncPolicy is a helper method to define mock.On call
func (_e *TaskContext_Expecter) SyncPolicy() *TaskContext_SyncPolicy_Call {
	return &TaskContext_SyncPolicy_Call{Call: _e.mock.On("SyncPolicy")}
}

func (_c *TaskContext_SyncPolicy_Call) Run(run func()) *TaskContext_SyncPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskContext_SyncPolicy_Call) Return(syncPolicy *models.SyncPolicy) *TaskContext_SyncPolicy_Call {
	_c.Call.Return(syncPolicy)
	return _c
}

func (_c *TaskContext_SyncPolicy_Call) RunAndReturn(run func() *models.SyncPolicy) *TaskContext_SyncPolicy_Call {
	_c.Call.Return(run)
	return _c
}
