// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewToolLayerApiConnection creates a new instance of ToolLayerApiConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolLayerApiConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolLayerApiConnection {
	mock := &ToolLayerApiConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToolLayerApiConnection is an autogenerated mock type for the ToolLayerApiConnection type
type ToolLayerApiConnection struct {
	mock.Mock
}

type ToolLayerApiConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolLayerApiConnection) EXPECT() *ToolLayerApiConnection_Expecter {
	return &ToolLayerApiConnection_Expecter{mock: &_m.Mock}
}

// ConnectionId provides a mock function for the type ToolLayerApiConnection
func (_mock *ToolLayerApiConnection) ConnectionId() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionId")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// ToolLayerApiConnection_ConnectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionId'
type ToolLayerApiConnection_ConnectionId_Call struct {
	*mock.Call
}

// ConnectionId is a helper method to define mock.On call
func (_e *ToolLayerApiConnection_Expecter) ConnectionId() *ToolLayerApiConnection_ConnectionId_Call {
	return &ToolLayerApiConnection_ConnectionId_Call{Call: _e.mock.On("ConnectionId")}
}

func (_c *ToolLayerApiConnection_ConnectionId_Call) Run(run func()) *ToolLayerApiConnection_ConnectionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerApiConnection_ConnectionId_Call) Return(v uint64) *ToolLayerApiConnection_ConnectionId_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ToolLayerApiConnection_ConnectionId_Call) RunAndReturn(run func() uint64) *ToolLayerApiConnection_ConnectionId_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpoint provides a mock function for the type ToolLayerApiConnection
func (_mock *ToolLayerApiConnection) GetEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolLayerApiConnection_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type ToolLayerApiConnection_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
func (_e *ToolLayerApiConnection_Expecter) GetEndpoint() *ToolLayerApiConnection_GetEndpoint_Call {
	return &ToolLayerApiConnection_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint")}
}

func (_c *ToolLayerApiConnection_GetEndpoint_Call) Run(run func()) *ToolLayerApiConnection_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerApiConnection_GetEndpoint_Call) Return(s string) *ToolLayerApiConnection_GetEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolLayerApiConnection_GetEndpoint_Call) RunAndReturn(run func() string) *ToolLayerApiConnection_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetProxy provides a mock function for the type ToolLayerApiConnection
func (_mock *ToolLayerApiConnection) GetProxy() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProxy")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolLayerApiConnection_GetProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProxy'
type ToolLayerApiConnection_GetProxy_Call struct {
	*mock.Call
}

// GetProxy is a helper method to define mock.On call
func (_e *ToolLayerApiConnection_Expecter) GetProxy() *ToolLayerApiConnection_GetProxy_Call {
	return &ToolLayerApiConnection_GetProxy_Call{Call: _e.mock.On("GetProxy")}
}

func (_c *ToolLayerApiConnection_GetProxy_Call) Run(run func()) *ToolLayerApiConnection_GetProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerApiConnection_GetProxy_Call) Return(s string) *ToolLayerApiConnection_GetProxy_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolLayerApiConnection_GetProxy_Call) RunAndReturn(run func() string) *ToolLayerApiConnection_GetProxy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimitPerHour provides a mock function for the type ToolLayerApiConnection
func (_mock *ToolLayerApiConnection) GetRateLimitPerHour() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimitPerHour")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// ToolLayerApiConnection_GetRateLimitPerHour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimitPerHour'
type ToolLayerApiConnection_GetRateLimitPerHour_Call struct {
	*mock.Call
}

// GetRateLimitPerHour is a helper method to define mock.On call
func (_e *ToolLayerApiConnection_Expecter) GetRateLimitPerHour() *ToolLayerApiConnection_GetRateLimitPerHour_Call {
	return &ToolLayerApiConnection_GetRateLimitPerHour_Call{Call: _e.mock.On("GetRateLimitPerHour")}
}

func (_c *ToolLayerApiConnection_GetRateLimitPerHour_Call) Run(run func()) *ToolLayerApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerApiConnection_GetRateLimitPerHour_Call) Return(n int) *ToolLayerApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *ToolLayerApiConnection_GetRateLimitPerHour_Call) RunAndReturn(run func() int) *ToolLayerApiConnection_GetRateLimitPerHour_Call {
	_c.Call.Return(run)
	return _c
}

// TableName provides a mock function for the type ToolLayerApiConnection
func (_mock *ToolLayerApiConnection) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolLayerApiConnection_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type ToolLayerApiConnection_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *ToolLayerApiConnection_Expecter) TableName() *ToolLayerApiConnection_TableName_Call {
	return &ToolLayerApiConnection_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *ToolLayerApiConnection_TableName_Call) Run(run func()) *ToolLayerApiConnection_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerApiConnection_TableName_Call) Return(s string) *ToolLayerApiConnection_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolLayerApiConnection_TableName_Call) RunAndReturn(run func() string) *ToolLayerApiConnection_TableName_Call {
	_c.Call.Return(run)
	return _c
}
