// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewToolLayerScopeConfig creates a new instance of ToolLayerScopeConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolLayerScopeConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolLayerScopeConfig {
	mock := &ToolLayerScopeConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToolLayerScopeConfig is an autogenerated mock type for the ToolLayerScopeConfig type
type ToolLayerScopeConfig struct {
	mock.Mock
}

type ToolLayerScopeConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolLayerScopeConfig) EXPECT() *ToolLayerScopeConfig_Expecter {
	return &ToolLayerScopeConfig_Expecter{mock: &_m.Mock}
}

// ScopeConfigConnectionId provides a mock function for the type ToolLayerScopeConfig
func (_mock *ToolLayerScopeConfig) ScopeConfigConnectionId() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeConfigConnectionId")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// ToolLayerScopeConfig_ScopeConfigConnectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeConfigConnectionId'
type ToolLayerScopeConfig_ScopeConfigConnectionId_Call struct {
	*mock.Call
}

// ScopeConfigConnectionId is a helper method to define mock.On call
func (_e *ToolLayerScopeConfig_Expecter) ScopeConfigConnectionId() *ToolLayerScopeConfig_ScopeConfigConnectionId_Call {
	return &ToolLayerScopeConfig_ScopeConfigConnectionId_Call{Call: _e.mock.On("ScopeConfigConnectionId")}
}

func (_c *ToolLayerScopeConfig_ScopeConfigConnectionId_Call) Run(run func()) *ToolLayerScopeConfig_ScopeConfigConnectionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerScopeConfig_ScopeConfigConnectionId_Call) Return(v uint64) *ToolLayerScopeConfig_ScopeConfigConnectionId_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ToolLayerScopeConfig_ScopeConfigConnectionId_Call) RunAndReturn(run func() uint64) *ToolLayerScopeConfig_ScopeConfigConnectionId_Call {
	_c.Call.Return(run)
	return _c
}

// ScopeConfigId provides a mock function for the type ToolLayerScopeConfig
func (_mock *ToolLayerScopeConfig) ScopeConfigId() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScopeConfigId")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// ToolLayerScopeConfig_ScopeConfigId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeConfigId'
type ToolLayerScopeConfig_ScopeConfigId_Call struct {
	*mock.Call
}

// ScopeConfigId is a helper method to define mock.On call
func (_e *ToolLayerScopeConfig_Expecter) ScopeConfigId() *ToolLayerScopeConfig_ScopeConfigId_Call {
	return &ToolLayerScopeConfig_ScopeConfigId_Call{Call: _e.mock.On("ScopeConfigId")}
}

func (_c *ToolLayerScopeConfig_ScopeConfigId_Call) Run(run func()) *ToolLayerScopeConfig_ScopeConfigId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerScopeConfig_ScopeConfigId_Call) Return(v uint64) *ToolLayerScopeConfig_ScopeConfigId_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ToolLayerScopeConfig_ScopeConfigId_Call) RunAndReturn(run func() uint64) *ToolLayerScopeConfig_ScopeConfigId_Call {
	_c.Call.Return(run)
	return _c
}

// TableName provides a mock function for the type ToolLayerScopeConfig
func (_mock *ToolLayerScopeConfig) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolLayerScopeConfig_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type ToolLayerScopeConfig_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *ToolLayerScopeConfig_Expecter) TableName() *ToolLayerScopeConfig_TableName_Call {
	return &ToolLayerScopeConfig_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *ToolLayerScopeConfig_TableName_Call) Run(run func()) *ToolLayerScopeConfig_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerScopeConfig_TableName_Call) Return(s string) *ToolLayerScopeConfig_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolLayerScopeConfig_TableName_Call) RunAndReturn(run func() string) *ToolLayerScopeConfig_TableName_Call {
	_c.Call.Return(run)
	return _c
}
