// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewToolLayerConnection creates a new instance of ToolLayerConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolLayerConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolLayerConnection {
	mock := &ToolLayerConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToolLayerConnection is an autogenerated mock type for the ToolLayerConnection type
type ToolLayerConnection struct {
	mock.Mock
}

type ToolLayerConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolLayerConnection) EXPECT() *ToolLayerConnection_Expecter {
	return &ToolLayerConnection_Expecter{mock: &_m.Mock}
}

// ConnectionId provides a mock function for the type ToolLayerConnection
func (_mock *ToolLayerConnection) ConnectionId() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionId")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// ToolLayerConnection_ConnectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionId'
type ToolLayerConnection_ConnectionId_Call struct {
	*mock.Call
}

// ConnectionId is a helper method to define mock.On call
func (_e *ToolLayerConnection_Expecter) ConnectionId() *ToolLayerConnection_ConnectionId_Call {
	return &ToolLayerConnection_ConnectionId_Call{Call: _e.mock.On("ConnectionId")}
}

func (_c *ToolLayerConnection_ConnectionId_Call) Run(run func()) *ToolLayerConnection_ConnectionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerConnection_ConnectionId_Call) Return(v uint64) *ToolLayerConnection_ConnectionId_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ToolLayerConnection_ConnectionId_Call) RunAndReturn(run func() uint64) *ToolLayerConnection_ConnectionId_Call {
	_c.Call.Return(run)
	return _c
}

// TableName provides a mock function for the type ToolLayerConnection
func (_mock *ToolLayerConnection) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ToolLayerConnection_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type ToolLayerConnection_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *ToolLayerConnection_Expecter) TableName() *ToolLayerConnection_TableName_Call {
	return &ToolLayerConnection_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *ToolLayerConnection_TableName_Call) Run(run func()) *ToolLayerConnection_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolLayerConnection_TableName_Call) Return(s string) *ToolLayerConnection_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ToolLayerConnection_TableName_Call) RunAndReturn(run func() string) *ToolLayerConnection_TableName_Call {
	_c.Call.Return(run)
	return _c
}
